[Diplomacy]
; Allow Puppet Trade:
; 0 = Vanilla behavior (puppets can only trade with their master)
; 1 = Free trade (puppets can trade with any nation not at war)
; 2 = Free trade with Master Veto (puppets trade freely, but automatically respect master trade embargoes and master war enemies)
AllowPuppetTrade = 2

