


#####################
# Country main data #
#####################

country =
{ tag                    = GER
  ai_settings			 = { flags = { Depression = 6 WARDebt = 2 } }
  belligerence			 = 4
  capital                = 300
	manpower               = 794.5
	transports             = 450 
	escorts                = 23 

	# Resource Reserves 
	energy                 = 16000 
	metal                  = 8000 
	rare_materials         = 4000 
	oil                    = 4000  
	supplies               = 500 
	money                  = 70 
  diplomacy =
  { relation = { tag = ARG value = 75 }
    relation = { tag = AST value = 1 }
    relation =
    { tag        = AUS
      value      = 100
    }
    relation = { tag = BEL value = 20 }
    relation = { tag = BHU value = 1 }
    relation = { tag = BOL value = 15 }
    relation = { tag = BRA value = 50 }
    relation =
    { tag        = BUL
      value      = 25
    }
    relation = { tag = CAN value = 1 }
    relation = { tag = CHL value = 50 }
    relation = { tag = COL value = -20 }
    relation =
    { tag        = CZE
      value      = -25
    }
    relation = { tag = ENG value = 1 }
    relation =
    { tag        = DEN
      value      = 25
    }
    relation = { tag = EST value = 10 }
    relation =
    { tag        = FIN
      value      = 25
    }
    relation = { tag = FRA value = -35 }
    relation = { tag = GRE value = 15 }
    relation = { tag = HOL value = 1 }
    relation = { tag = HUN value = 100 }
    relation = { tag = IRE value = 15 }
    relation = { tag = IRQ value = 25 }
    relation =
    { tag        = ITA
      value      = 50
    }
    relation = { tag = JAP value = 20 }
    relation = { tag = LAT value = 10 }
    relation = { tag = LIT value = 10 }
    relation = { tag = LUX value = -50 }
    relation = { tag = MAN value = 20 }
    relation = { tag = NEP value = 1 }
    relation = { tag = NZL value = 1 }
    relation = { tag = OMN value = 1 }
    relation =
    { tag        = POL
      value      = -10
    }
    relation = { tag = POR value = 75 }
    relation =
    { tag        = ROM
      value      = 50
    }
    relation = { tag = SAF value = 1 }
    relation =
    { tag        = SCH
      value      = 50
    }
    relation = { tag = SOV value = 1 }
    relation = { tag = SPR value = -50 }
    relation =
    { tag        = SWE
      value      = 50
    }
    relation =
    { tag        = TUR
      value      = 10
    }
    relation = { tag = USA value = -10 }
    relation = { tag = YEM value = 1 }
    relation =
    { tag        = YUG
      value      = 50
    }
  }
  SpyInfo                = { country = "ENG" NumberOfSpies = 3 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 4 }
  SpyInfo                = { country = "SOV" NumberOfSpies = 2 }
  SpyInfo                = { country = "CZE" NumberOfSpies = 4 }
  SpyInfo                = { country = "AUS" NumberOfSpies = 5 }
  SpyInfo                = { country = "SPR" NumberOfSpies = 2 }
  SpyInfo                = { country = "POL" NumberOfSpies = 3 }
  SpyInfo                = { country = "SWE" NumberOfSpies = 3 }
  SpyInfo                = { country = "NOR" NumberOfSpies = 4 }
  SpyInfo                = { country = "FIN" NumberOfSpies = 2 }
  SpyInfo                = { country = "YUG" NumberOfSpies = 2 }
  SpyInfo                = { country = "HUN" NumberOfSpies = 3 }
  SpyInfo                = { country = "BUL" NumberOfSpies = 2 }
  SpyInfo                = { country = "BEL" NumberOfSpies = 3 }
  SpyInfo                = { country = "DEN" NumberOfSpies = 5 }
  SpyInfo                = { country = "HOL" NumberOfSpies = 3 }
  SpyInfo                = { country = "ARG" NumberOfSpies = 3 }
  SpyInfo                = { country = "USA" NumberOfSpies = 3 }
  SpyInfo                = { country = "ALB" NumberOfSpies = 1 }
  SpyInfo                = { country = "GRE" NumberOfSpies = 1 }
  SpyInfo                = { country = "BRA" NumberOfSpies = 1 }
  SpyInfo                = { country = "JAP" NumberOfSpies = 2 }
  SpyInfo                = { country = "ROM" NumberOfSpies = 2 }
  SpyInfo                = { country = "LIT" NumberOfSpies = 2 }
  SpyInfo                = { country = "LUX" NumberOfSpies = 1 }
  SpyInfo                = { country = "POR" NumberOfSpies = 1 }
  SpyInfo                = { country = "ITA" NumberOfSpies = 4 }
  SpyInfo                = { country = "CHI" NumberOfSpies = 4 }
  SpyInfo                = { country = "MEX" NumberOfSpies = 1 }
  nationalprovinces      = { 
							 307 208 3264 483 #Poland
							 456 3363 494 3370 495 430 3382 197 205 3715 1839 3717 3463 #Foreign germans
							 66  67  74  75  76  80  81  82  83  84  85  86  87  88  
							 89  90  296 297 298 299 300 301 302 304 308 309 310 311 312 313
                             314 315 374 375 376 473 482 510 73 71 72 316 
							 223 1779 1810 1811 1400 1623 1595
							 1405 546 547 1014 970 989 1018 1016 1015
							 303 2606 533 532 486 2381 2292 2597 1904 2370
							 2627 2647
							 3238	3239	3240	3241	3242	3243	3244	3245	3246	
							 3247	3248	3249	3250	3251	3252	3253	3254	3255	
							 3256	3257	3258	3259	3260	3261
							 3216 3214 3215 2273 373 377 1408 462 461 3217 460 2329 463 2328 2327 465 464 467 53 466 3262 471 472 3376 3375
							 6500 6519 6520 6521 6518
							 6917
							 7045 7046 7047 7177 7178 7179 7180 7181 7182 7183 7184 7185 7186 7187 7188 7189 7190 7260 7266 7986
							 7040 459
                           }
  claimedprovinces = { 91 371 470 3228 469 1888 468 3229 475 474 3263 483 3264 208 307 3265 306 6560 2628 2296 7122 
	193 194 195 196 199 1886 3286 3394 #Estonia
	205 204 203 197 202 198 3283 3284 3285 #Latvia
	380 7124 666 2326 1082 2289
	#70
  }
  ownedprovinces         = { 66  67  74  75  76  80  81  82  83  84  85  86  87  88  89  90  296 297 298 299 300 301 302 304 308 309 310 311 312 313
                             314 315 374 375 376 473 482 510
							 223 1779 1810 1811 1400 1623 1595
							 1405 546 547 1014 970 989 1018 1016 1015 2381 2597 1904 2370
							 2627 2647
							 3238	3239	3240	3241	3242	3243	3244	3245	3246	
							 3247	3248	3249	3250	3251	3252	3253	3254	3255	
							 3256	3257	3258	3259	3260	3261
							 6500 6519 6520 6521
							 6917
							 7045 7046 7047 7177 7178 7179 7180 7181 7182 7183 7184 7185 7186 7187 7188 7189 7190 7260 7266 7986
                           }
  controlledprovinces    = { 66  67  74  75  76  80  81  82  83  84  85  86  87  88  89  90  296 297 298 299 300 301 302 304 308 309 310 311 312 313
                             314 315 374 375 376 473 482 510
							 223 1779 1810 1811 1400 1623 1595
							 1405 546 547 1014 970 989 1018 1016 1015 2381 2597 1904 2370
							 2627 2647
							 3238	3239	3240	3241	3242	3243	3244	3245	3246	
							 3247	3248	3249	3250	3251	3252	3253	3254	3255	
							 3256	3257	3258	3259	3260	3261
							 6500 6519 6520 6521
							 6917
							 7045 7046 7047 7177 7178 7179 7180 7181 7182 7183 7184 7185 7186 7187 7188 7189 7190 7260 7266 7986
                           }

  # Germany 1936 techs
  # ######################
	techapps = { 
	#Early Infantry Division  
	1010 1020 1030 1040 1050 1060 1070 1080 1090
	#SEMI-MOTORIZED CAVALRY 
	13060 13070 13080 1310 1320 1330 1340 1350 1360 1370 1380 
	# Motorized Infantry
	1396
	#Early Mountain Division 
	1160  1170 1180 1190 1200 1210 1220 1230 1240
	#Engineers
	1830 1840 1850 1860
	#Interbellum 1930 Supply
	1910 1920 1930 1940 1950 1960 1970 1980

	#Basic Armoured Car  
	2860 2870 2880 2020 2150
	#Early Tank 
	7600 7610 2620 2010 2630 2640 2646 2650 2030
	#Early Field Artillery 
	2290 2300 2310 2900 2910 2920 2930
	#Early Static Anti-Air Artillery 
	2800 2450 21180 21190 21200
	#Basic Anti-Air Artillery Brigade 
	2810 2820 2510

	#Improved Destroyer 
	3010 3020 3030 3040 3050 3060
	#Basic Light Cruiser 
	3110 3120 3130 3140 3150 3160
	#Improved Heavy Cruiser 
	3210 3220 3230 3240 3250 3260  
	#Early Battlecruiser
	3310 3320 3330 3340
	#Early Battleship 
	3410 3420 3430 3440 3450 3456 3460 3470
	#Improved Submarine 
	3610 3620 3630 3640 3650
	#Great War Air Carrier 
	3510
	#CAG
	4900
	#Improved Light carrier 
	12100 12110
	#Torpedo & ASW 18
	3720 3730 3736 3740 3750 3900
	#Troopships
	3810 3820

	#Basic Air Transport 
	4290 4250
	#Multirole fighter
	4300 4310 4320 4330 4340
	#CAS
	4400
	#ww1 strategic bomber
	4800 4810 4820
	#ww1 navalbomber
	4700 4710
	#Early Fighter  
	4500 4510 4520 4530 4540 4550 4010 4020
	#Early Bomber
	4600 4610 4620 4630 4120 4130
	#SEAPLANES
	4740 4750 4760

	#Manufacturing
	5810 5820 5050 5830 5060
	#Improved Construction Engineering 
	5800 5080 5090
	#Basic Oil Refining
	5190 5200
	#Computers & cryptografi
	5310 54010 54020 54030 5316 5326
	#Exp. Rocket
	5560
	#Mechanized Agriculture 
	5700 5710 5010 5020
	#Medicine
	5600 5610 5620 5630

	# Great War Land Doctrines (central powers)
	6500 6510 6530 6550 6590 6600 6620 6650 6670 6610 6680 6690 6700 6710 6910
	# WW2 Land Doctrines
	6210 6220 6230 6250 6900
	#Great War Hospital System 
	14000 14010 14020

	#Air Doctrines - ww2 techs
	27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040 9050 9090

	#Naval Doctrines
	8010 8020 8030 8040 8050 8060 8070 8080
	# Amphib
	82300
	# Naval Logistics
	82500
	# Naval Interdiction
	8500 8510 8520 8550 8560 8570
	# Trade Interdiction Submarine
	8600 8610
	# Indirect Approach
	81300 81310 81320 81330 81340 81350
	# Naval Supremacy
	8100 8110 8120 8150 8160 8170 8200 8210
	# rocket test facilities
	7550
}

inventions = { 3000027 3000028 }
blueprints = { 6240 6260 6270 7560 } # Elastic Defense, Combined Arms Off. and Kampfgruppe doctrines
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 1 
     political_left    = 1 
     free_market       = 1
     freedom           = 9 
     professional_army = 4 
     defense_lobby     = 5 
     interventionism   = 8
  }
   headofstate            = {  type = 9 id = 1  } 
   headofgovernment       = {  type = 9 id = 2  } 
   foreignminister        = {  type = 9 id = 3  } 
   armamentminister       = {  type = 9 id = 56 } 
   ministerofsecurity     = {  type = 9 id = 5  } 
   ministerofintelligence = {  type = 9 id = 6  } 
   chiefofstaff           = {  type = 9 id = 7  } 
   chiefofarmy            = {  type = 9 id = 8  } 
   chiefofnavy            = {  type = 9 id = 9  } 
   chiefofair             = {  type = 9 id = 10 } 
   dormant_leaders        = {  36 44 54 66 67 223 226 292 352 473 479 526
							   542 543 544 546 547 549 550 551 553 558 559 560 561 562 563 
							   567 571 572 573 578 595 686 712 746 749 816 821 909 983 992
							   576 1007 1008 #Vlassov Zverev Budyho
							}
 


 landunit = 
   {  location = 300 
     name     = "I. Armeekorps" 
     id       = {  type = 14500 id = 34  } 
     Division = 
     {  id       = {  type = 14500 id = 35  } 
       name     = "1. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 36  } 
       name          = "11. Infanterie-Division" 
       type          = infantry 
       model         = 8
       extra         = artillery 
       brigade_model = 6
       strength      = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 37  } 
       name     = "21. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1001  } 
       name     = "61. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1002  } 
       name     = "206. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1003  } 
       name     = "217. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1004  } 
       name     = "228. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 300 
     name     = "II. Armeekorps" 
     id       = {  type = 14500 id = 38  } 
     Division = 
     {  id       = {  type = 14500 id = 39  } 
       name     = "75. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 40  } 
       name     = "207. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 41  } 
       name     = "12. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
       extra    = artillery 
	   brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 14500 id = 1005  } 
       name     = "258. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 300 
      leader   = 608 # von Fritsch
     name     = "III. Armeekorps" 
     id       = {  type = 14500 id = 42  } 
     Division = 
     {  id       = {  type = 14500 id = 1706  } 
       name     = "Oberkommando des Heeres" 
       type     = hq 
       model    = 2 
       strength = 50 
      } 
     Division = 
     {  id       = {  type = 14500 id = 43  } 
       name     = "3. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 44  } 
       name     = "23. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
       extra    = engineer
	   brigade_model = 3	
      } 
     Division = 
     {  id       = {  type = 14500 id = 1006  } 
       name     = "50. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1007  } 
       name     = "68. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1008  } 
       name     = "76. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1009  } 
       name     = "208. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1010  } 
       name     = "218. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1011  } 
       name     = "257. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1012  } 
       name     = "93. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 300 
     name     = "VIII. Armeekorps" 
     id       = {  type = 14500 id = 45  } 
     Division = 
     {  id       = {  type = 14500 id = 46  } 
       name     = "8. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 47  } 
       name     = "62. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 48  } 
       name     = "18. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
       extra    = engineer
	   brigade_model = 3	   
      } 
     Division = 
     {  id       = {  type = 14500 id = 1013  } 
       name     = "213. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1014  } 
       name     = "221. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1015  } 
       name     = "252. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 300 
     name     = "V. Armeekorps" 
     id       = {  type = 14500 id = 49  } 
     Division = 
     {  id       = {  type = 14500 id = 50  } 
       name     = "78. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id            = {  type = 14500 id = 51  } 
       name          = "5. Infanterie-Division" 
       type          = infantry 
       model         = 8
       strength      = 90 
       extra         = artillery 
       brigade_model = 7
      } 
     Division = 
     {  id       = {  type = 14500 id = 52  } 
       name     = "260. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 300 
     name     = "VI. Armeekorps" 
     id       = {  type = 14500 id = 53  } 
     Division = 
     {  id       = {  type = 14500 id = 54  } 
       name     = "6. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 55  } 
       name     = "16. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
       extra    = artillery 
	   brigade_model = 5
      } 
     Division = 
     {  id       = {  type = 14500 id = 56  } 
       name     = "69. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1016  } 
       name     = "86. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1017  } 
       name     = "211. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1018  } 
       name     = "227. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1019  } 
       name     = "253. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1020  } 
       name     = "254. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 300 
     name     = "IX. Armeekorps" 
     id       = {  type = 14500 id = 57  } 
     Division = 
     {  id       = {  type = 14500 id = 58  } 
       name     = "9. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 59  } 
       name     = "15. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
       extra    = anti_air 
	   brigade_model = 2
      } 
     Division = 
     {  id       = {  type = 14500 id = 60  } 
       name     = "52. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1021  } 
       name     = "214. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1022  } 
       name     = "239. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1023  } 
       name     = "251. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1024  } 
       name     = "95. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 300 
     name     = "XII. Armeekorps" 
     id       = {  type = 14500 id = 61  } 
     Division = 
     {  id       = {  type = 14500 id = 62  } 
       name     = "79. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 63  } 
       name     = "246. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 64  } 
       name     = "262. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1025  } 
       name     = "263. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 300 
     name     = "IV. Armeekorps" 
     id       = {  type = 14500 id = 65  } 
     Division = 
     {  id       = {  type = 14500 id = 66  } 
       name     = "4. Infanterie-Division" 
       type     = infantry 
       model    = 8
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 67  } 
       name          = "14. Infanterie-Division" 
       type          = infantry 
       model         = 8 
       strength      = 90 
       extra         = artillery 
       brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 14500 id = 68  } 
       name     = "24. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1026  } 
       name     = "56. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1027  } 
       name     = "87. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1028  } 
       name     = "209. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1029  } 
       name     = "223. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1030  } 
       name     = "255. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1031  } 
       name     = "256. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1032  } 
       name     = "94. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 300 
     name     = "VII. Armeekorps" 
     id       = {  type = 14500 id = 69  } 
     Division = 
     {  id       = {  type = 14500 id = 70  } 
       name     = "57. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 71  } 
       name     = "7. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
       extra    = artillery 
	   brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 14500 id = 72  } 
       name     = "163. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 73  } 
       name     = "168. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 300 
     name     = "X. Armeekorps" 
     id       = {  type = 14500 id = 74  } 
     Division = 
     {  id       = {  type = 14500 id = 75  } 
       name     = "58. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id            = {  type = 14500 id = 76  } 
       name          = "22. Infanterie-Division" 
       type          = infantry 
       model         = 8 
       strength      = 90 
       extra         = artillery 
       brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 14500 id = 77  } 
       name     = "170. Infanterie-Division" 
       type     = infantry 
       model    = 6 
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1033  } 
       name     = "215. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1034  } 
       name     = "181. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1035  } 
       name     = "269. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 300 
     name     = "XI. Armeekorps" 
     id       = {  type = 14500 id = 78  } 
     Division = 
     {  id       = {  type = 14500 id = 79  } 
       name     = "71. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 80  } 
       name     = "19. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
       extra    = anti_air 
	   brigade_model = 2
      } 
     Division = 
     {  id       = {  type = 14500 id = 81  } 
       name     = "216. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1036  } 
       name     = "196. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1037  } 
       name     = "96. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
    } 
   landunit = 
   {  location = 300
     name     = "XVI. Armeekorps" 
     id       = {  type = 14500 id = 82  } 
     Division = 
     {  id       = {  type = 14500 id = 83  } 
       name     = "1. Panzer-Division" 
       type     = light_armor 
       model    = 0
       strength = 100 
      } 
     Division = 
     {  id       = {  type = 14500 id = 84  } 
       name     = "2. Panzer-Division" 
       type     = light_armor 
       model    = 0
       strength = 100 
      } 
     Division = 
     {  id           = {  type = 14500 id = 85  } 
       name         = "3. Panzer-Division" 
       type         = light_armor 
       model        = 0
       strength     = 65 
       organisation = 30
      } 
    } 
   landunit = 
   {  location = 300 
     name     = "XIII. Armeekorps" 
     id       = {  type = 14500 id = 1038  } 
     Division = 
     {  id       = {  type = 14500 id = 1039  } 
       name     = "17. Infanterie-Division" 
       type     = infantry 
       model    = 8 
       strength = 90 
      } 
     Division = 
     {  id            = {  type = 14500 id = 1040  } 
       name          = "10. Infanterie-Division" 
       type          = infantry 
       model         = 8 
       strength      = 90 
       extra         = artillery 
       brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 14500 id = 1041  } 
       name     = "73. Infanterie-Division" 
       type     = infantry 
       model    = 7
       strength = 10 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1042  } 
       name     = "231. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1043  } 
       name     = "198. Infanterie-Division" 
       type     = infantry 
       model    = 6
       strength = 5 
      } 
     Division = 
     {  id       = {  type = 14500 id = 1044  } 
       name    		 = "1. Leichte Division" 
       type     	 = infantry
       model    	 = 6 
       strength 	 = 50 
       extra    	 = light_armor_brigade
	   brigade_model = 3	
      } 
    } 
   navalunit = 
   {  name     = "Kriegsmarine" 
     id       = {  type = 14500 id = 1  } 
     location = 90 
     base     = 90 
     Division = 
     {  id    = {  type = 14500 id = 2  } 
       name  = "Deutschland" 
       type  = heavy_cruiser 
       model = 4
      } 
     Division = 
     {  id    = {  type = 14500 id = 3  } 
       name  = "Admiral Scheer" 
       type  = heavy_cruiser 
       model = 4
      } 
     Division = 
     {  id    = {  type = 14500 id = 4  } 
       name  = "Nürnberg" 
       type  = light_cruiser 
       model = 4 
      } 
     Division = 
     {  id    = {  type = 14500 id = 5  } 
       name  = "Leipzig" 
       type  = light_cruiser 
       model = 3 
      } 
     Division = 
     {  id    = {  type = 14500 id = 6  } 
       name  = "Königsberg" 
       type  = light_cruiser 
       model = 3 
      } 
     Division = 
     {  id    = {  type = 14500 id = 7  } 
       name  = "Karlsruhe" 
       type  = light_cruiser 
       model = 3 
      } 
     Division = 
     {  id    = {  type = 14500 id = 8  } 
       name  = "Köln" 
       type  = light_cruiser 
       model = 3 
      } 
     Division = 
     {  id    = {  type = 14500 id = 9  } 
       name  = "Emden" 
       type  = light_cruiser 
       model = 3 
      } 
     Division = 
     {  id    = {  type = 14500 id = 10  } 
       name  = "3. Zerstörergeschwader" 
       type  = destroyer 
       model = 4
      } 
     Division = 
     {  id    = {  type = 14500 id = 33  } 
       name  = "4. Zerstörergeschwader" 
       type  = destroyer 
       model = 4 
      } 
    } 
 navalunit = 
   {  name     = "I. Truppentransporter Flotte" 
     id       = {  type = 14500 id = 104  } 
     location = 90 
     base     = 90 
     Division = 
     {  id    = {  type = 14500 id = 105  } 
       name  = "1. Truppentransporterflottille" 
       type = transport
	model = 1 
      } 
     Division = 
     {  id    = {  type = 14500 id = 106  } 
       name  = "2. Truppentransporterflottille" 
       type = transport 
	model = 1 
      } 
     Division = 
     {  id    = {  type = 14500 id = 107  } 
       name  = "3. Truppentransporterflottille" 
       type = transport 
	model = 1 
      } 
    } 
   navalunit = 
   {  name     = "II. Unterseebootsflotte" 
     id       = {  type = 14500 id = 20  } 
     location = 90 
     base     = 90 
     Division = 
     {  id    = {  type = 14500 id = 21  } 
       name  = "2. Unterseebootsflottille" 
       type  = submarine 
       model = 4 
      } 
     Division = 
     {  id    = {  type = 14500 id = 25  } 
       name  = "3. Unterseebootsflottille" 
       type  = submarine 
       model = 4 
      } 
    } 
   navalunit = 
   {  name     = "I. Unterseebootsflotte" 
     id       = {  type = 14500 id = 26  } 
     location = 90 
     base     = 90 
     Division = 
     {  id    = {  type = 14500 id = 27  } 
       name  = "1. Unterseebootsflottille" 
       type  = submarine 
       model = 4 
      } 
     Division = 
     {  id    = {  type = 14500 id = 200 } 
       name  = "4. Unterseebootsflottille" 
       type  = submarine 
       model = 4 
      } 
    } 
   navalunit = 
   {  name     = "Baltische Flotte" 
     id       = {  type = 14500 id = 28  } 
     location = 90 
     base     = 90 
     Division = 
     {  id    = {  type = 14500 id = 29  } 
       name  = "Schleswig-Holstein" 
       type  = battleship 
       model = 1
      } 
     Division = 
     {  id    = {  type = 14500 id = 30  } 
       name  = "Schlesien" 
       type  = battleship 
       model = 1
      } 
     Division = 
     {  id    = {  type = 14500 id = 157  } 
       name  = "Hannover" 
       type  = battleship 
       model = 1
      } 
     Division = 
     {  id    = {  type = 14500 id = 31  } 
       name  = "1. Zerstörergeschwader" 
       type  = destroyer 
       model = 1
      } 
     Division = 
     {  id    = {  type = 14500 id = 32  } 
       name  = "2. Zerstörergeschwader" 
       type  = destroyer 
       model = 1 
      } 
     Division = 
     {  id    = {  type = 14500 id = 155 } 
       name  = "5. Zerstörergeschwader" 
       type  = destroyer 
       model = 0
      } 
     Division = 
     {  id    = {  type = 14500 id = 156  } 
       name  = "6. Zerstörergeschwader" 
       type  = destroyer 
       model = 0
      } 
    } 
   # ######### Luftwaffe ############## 
   airunit = 
   {  location = 300 
     id       = {  type = 14500 id = 86  } 
     name     = "Luftflotte II" 
     base     = 300 
     Division = 
     {  id       = {  type = 14500 id = 87  } 
       name     = "KG 2 'Holzhammer'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 88  } 
       name     = "KG 3 'Blitz'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 89  } 
       name     = "Sturzkampfgeschwader 51" 
       strength = 100 
       type     = CAS 
       model    = 0
      } 
     Division = 
     {  id            = {  type = 14500 id = 90  } 
       name          = "JG 2 'Richthofen'" 
       strength      = 100 
       type          = interceptor 
       model         = 7
      } 
     Division = 
     {  id            = {  type = 14500 id = 91  } 
       name          = "JG 26 'Schlageter'" 
       strength      = 100 
       type          = interceptor 
       model         = 7
      } 
    } 
   airunit = 
   {  location = 300 
     id       = {  type = 14500 id = 95  } 
     name     = "Luftflotte III" 
     base     = 300 
     Division = 
     {  id       = {  type = 14500 id = 96  } 
       name     = "KG 53 'Legion Condor'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 97  } 
       name     = "Kampfgeschwader 25" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 98  } 
       name     = "KG 30 'Adler'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
    } 
   airunit = 
   {  location = 300 
     id       = {  type = 14500 id = 99  } 
     name     = "Luftflotte IV" 
     base     = 300 
     Division = 
     {  id       = {  type = 14500 id = 100  } 
       name     = "KG 1 'Hindenburg'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
     Division = 
     {  id       = {  type = 14500 id = 101  } 
       name     = "JG 3 'Udet'" 
       strength = 100 
       type     = interceptor 
       model    = 7
      } 
    } 
   airunit = 
   {  location = 300 
     id       = {  type = 14500 id = 102  } 
     name     = "Luftflotte V" 
     base     = 300 
     Division = 
     {  id       = {  type = 14500 id = 103  } 
       name     = "KG 4 'General Wever'" 
       strength = 100 
       type     = tactical_bomber 
       model    = 4
      } 
    } 

landdivision = { dormant = yes id = { type = 14500 id = 2027 }  name = "1. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2028 }  name = "2. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2029 }  name = "3. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2030 }  name = "4. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2031 }  name = "5. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2032 }  name = "6. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2033 }  name = "7. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2034 }  name = "8. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2035 }  name = "9. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2036 }  name = "10. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2037 }  name = "11. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2038 }  name = "12. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2039 }  name = "13. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2040 }  name = "14. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2041 }  name = "15. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2042 }  name = "16. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2043 }  name = "17. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2044 }  name = "18. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }
landdivision = { dormant = yes id = { type = 14500 id = 2045 }  name = "19. Festung Europa"  type = garrison model = 5 extra = artillery brigade_model = 9   }

	# ####under developement##### 
	division_development = {
		name  = "Admiral Graf Spee" 
		type  = heavy_cruiser
		model = 4
		new_model = no
		cost  = 0.2 
		id    = {  type = 14500 id = 500  } 
		date  = {  year = 1936 month = january day = 6  } 
	} 
	division_development = {
		name  = "Admiral Hipper" 
		type  = heavy_cruiser
		model = 5
		new_model = no
		cost  = 0.2 
		size  = 2
		id    = {  type = 14500 id = 501  } 
		date  = {  year = 1939 month = april day = 25  } 
	} 
	division_development = {
		name  = "Blücher" 
		type  = heavy_cruiser
		model = 5
		new_model = no
		cost  = 0.2 
		size  = 2		
		id    = {  type = 14500 id = 502  } 
		date  = {  year = 1939 month = september day = 20  } 
	} 
	division_development = {
		name  = "Gneisenau" 
		type  = battlecruiser
		model = 3
		new_model = no
		cost  = 0.3 
		id    = {  type = 14500 id = 503  } 
		date  = {  year = 1938 month = may day = 21  } 
	} 
	division_development = {
		name  = "Scharnhorst" 
		type  = battlecruiser
		model = 3
		new_model = no
		cost  = 0.3 
		id    = {  type = 14500 id = 504  } 
		date  = {  year = 1939 month = january day = 7  } 
	} 
	division_development = {
		name  = "7. Zerstörergeschwader" 
		type  = destroyer 
		model = 5 
		cost  = 0.1
		size  = 6
		id    = {  type = 14500 id = 565  } 
		date  = {  year = 1936 month = march day = 1  } 
	}
	division_development = {
		name  = "8. Zerstörergeschwader" 
		type  = destroyer 
		model = 5 
		cost  = 0.1
		size  = 6
		id    = {  type = 14500 id = 566  } 
		date  = {  year = 1936 month = april day = 1  } 
	}
	division_development = {
		name  = "9. Zerstörergeschwader" 
		type  = destroyer 
		model = 5 
		cost  = 0.1
		size  = 6
		id    = {  type = 14500 id = 567  } 
		date  = {  year = 1936 month = may day = 1  } 
	}
	division_development = {
		name = "5. Unterseebootsflottille"
		type = submarine
		model = 4
		cost = 0.1
		id = { type = 14500 id = 603 }
		date = { year = 1936 month = march day = 30 }
	}
	division_development = {
		name = "6. Unterseebootsflottille"
		type = submarine
		model = 4
		cost = 0.1
		id = { type = 14500 id = 604 }
		date = { year = 1936 month = april day = 30 }
	}
	division_development = {
		name = "7. Unterseebootsflottille"
		type = submarine
		model = 4
		cost = 0.1
		id = { type = 14500 id = 605 }
		date = { year = 1936 month = may day = 30 }
	}
	
division_development = {
		name  = "32. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 507  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "26. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 508  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "36. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 509  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "25. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 510  } 
		date  = {  year = 1936 month = april day = 1  } 
	} 
division_development = {
		name  = "35. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 511  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "27. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 512  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "28. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 513  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "30. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 514  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "31. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 515  } 
		date  = {  year = 1936 month = october day = 1  } 
	} 
division_development = {
		name  = "33. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 516  } 
		date  = {  year = 1936 month = april day = 1  } 
	} 
division_development = {
		name  = "34. Infanterie-Division" 
		type  = infantry
		model = 8
		cost  = 0.1 
		id    = {  type = 14500 id = 517  } 
		date  = {  year = 1936 month = april day = 1  } 
	} 
division_development = {
		name  = "2. Infanterie-Division (mot.)" 
		type  = motorized
		model = 0
		cost  = 0.1 
		id    = {  type = 14500 id = 518  } 
		date  = {  year = 1937 month = october day = 1  } 
	} 
division_development = {
		name  = "13. Infanterie-Division (mot.)" 
		type  = motorized
		model = 0
		cost  = 0.1 
		id    = {  type = 14500 id = 519  } 
		date  = {  year = 1937 month = october day = 1  } 
	} 
division_development = {
		name  = "20. Infanterie-Division (mot.)" 
		type  = motorized
		model = 0
		cost  = 0.1 
		id    = {  type = 14500 id = 520  } 
		date  = {  year = 1937 month = october day = 1  } 
	} 
division_development = {
		name  = "29. Infanterie-Division (mot.)" 
		type  = motorized
		model = 0
		cost  = 0.1 
		id    = {  type = 14500 id = 521  } 
		date  = {  year = 1937 month = october day = 1  } 
	} 
	province_development = { 
		id = { type = 14500 id = 540 } 
		location = 315 
		cost = 0.1 
		size = 3 
		type = land_fort 
		date  = {  year = 1964 } 
		} 
	province_development = { 
		id = { type = 14500 id = 541 } 
		location = 3250 
		cost = 0.1 
		size = 3 
		type = land_fort 
		date  = {  year = 1964 } 
		} 		
	province_development = { 
		id = { type = 14500 id = 542 } 
		location = 7189 
		cost = 0.1 
		size = 3 
		type = land_fort 
		date  = {  year = 1964 } 
		} 	
	province_development = { 
		id = { type = 14500 id = 543 } 
		location = 74 
		cost = 0.1 
		size = 3 
		type = land_fort 
		date  = {  year = 1964 } 
		} 	
	province_development = { 
		id = { type = 14500 id = 544 } 
		location = 3256 
		cost = 0.1 
		size = 2 
		type = coastal_fort 
		date  = {  year = 1964 } 
		} 	
	convoy_development = { 
		id = { type = 14500 id = 545 } 
		cost = 0.1
		size = 20 
		type = escorts 
		date  = {  year = 1964 } 
		} 
	convoy_development = { 
		id = { type = 14500 id = 546 } 
		cost = 0.1
		size = 20
		type = transports 
		date  = {  year = 1964 } 
		} 
		
landdivision = { dormant = yes id = { type = 14500 id = 11100 }  name = "2. Gebirgs-Division"   	 type = bergsjaeger		model = 8 	extra = artillery			brigade_model = 9 }
landdivision = { dormant = yes id = { type = 14500 id = 11101 }  name = "3. Gebirgs-Division"   	 type = bergsjaeger		model = 8 	extra = artillery			brigade_model = 9 }
landdivision = { dormant = yes id = { type = 14500 id = 11102 }  name = "181. Infanterie-Division"   type = infantry		model = 10 }
landdivision = { dormant = yes id = { type = 14500 id = 11103 }  name = "69. Infanterie-Division"    type = infantry		model = 10 }
landdivision = { dormant = yes id = { type = 14500 id = 11104 }  name = "170. Infanterie-Division"   type = infantry		model = 10 }
landdivision = { dormant = yes id = { type = 14500 id = 11105 }  name = "163. Infanterie-Division"   type = infantry		model = 10	extra = artillery			brigade_model = 9 }
landdivision = { dormant = yes id = { type = 14500 id = 11106 }  name = "214. Infanterie-Division"   type = infantry		model = 10 }
landdivision = { dormant = yes id = { type = 14500 id = 11107 }  name = "198. Infanterie-Division"   type = infantry		model = 10	extra = armored_car	brigade_model = 5 }
landdivision = { dormant = yes id = { type = 14500 id = 11108 }  name = "196. Infanterie-Division"   type = infantry 		model = 10 }
landdivision = { dormant = yes id = { type = 14500 id = 11109 }  name = "7. Flieger-Division"   	 type = paratrooper		model = 1 }

landdivision = { dormant = yes id = { type = 14500 id = 11120 }  name = "107. Infanterie-Division"   type = garrison		model = 5 locked = yes }

landdivision = { dormant = yes id = { type = 14500 id = 11130 }  name = "AOK Lappland"               type = hq				model = 4	extra = anti_air			brigade_model = 3 }
landdivision = { dormant = yes id = { type = 14500 id = 11131 }  name = "169. Infanterie-Division"   type = infantry		model = 2	extra = light_armor_brigade	brigade_model = 7 }
landdivision = { dormant = yes id = { type = 14500 id = 11132 }  name = "163. Infanterie-Division"   type = infantry		model = 2	extra = artillery			brigade_model = 9 }	
landdivision = { dormant = yes id = { type = 14500 id = 11133 }  name = "2. Gebirgs-Division"   	 type = bergsjaeger		model = 8	extra = artillery			brigade_model = 9 }
landdivision = { dormant = yes id = { type = 14500 id = 11134 }  name = "3. Gebirgs-Division"        type = bergsjaeger		model = 8	extra = artillery			brigade_model = 9 }
landdivision = { dormant = yes id = { type = 14500 id = 11135 }  name = "6. Gebirgs-Division"        type = bergsjaeger		model = 8 	extra = artillery			brigade_model = 9 }
landdivision = { dormant = yes id = { type = 14500 id = 11136 }  name = "7. Gebirgs-Division"        type = bergsjaeger		model = 8 	extra = artillery			brigade_model = 9 }
landdivision = { dormant = yes id = { type = 14500 id = 11137 }  name = "6. SS-Gebirgs-Division 'Nord'" type = bergsjaeger	model = 8	extra = artillery			brigade_model = 9 }

} 
