province = { id = 6916 naval_base = { size = 1 current_size = 1 } anti_air = 1 }
province = { id = 3558 naval_base = { size = 1 current_size = 1 } }
province = { id = 549 naval_base = { size = 4 current_size = 4 } }
province = { id = 556 naval_base = { size = 10 current_size = 10 } }
province = { id = 541 naval_base = { size = 10 current_size = 10 } }
province = { id = 780 naval_base = { size = 10 current_size = 10 } }
province = { id = 765 naval_base = { size = 10 current_size = 10 } }
province = { id = 762 naval_base = { size = 8 current_size = 8 } }
province = { id = 761 naval_base = { size = 10 current_size = 10 } }
province = { id = 751 naval_base = { size = 4 current_size = 4 } }
province = { id = 2649 naval_base = { size = 4 current_size = 4 } }
province = { id = 759 naval_base = { size = 1 current_size = 1 } }
province = { id = 4299 naval_base = { size = 4 current_size = 4 } }
province = { id = 539 naval_base = { size = 1 current_size = 1 } }
province = { id = 540 naval_base = { size = 10 current_size = 10 } }
province = { id = 814 naval_base = { size = 3 current_size = 3 } }
province = { id = 830 naval_base = { size = 3 current_size = 3 } }
province = { id = 856 naval_base = { size = 8 current_size = 8 } }
province = { id = 866 naval_base = { size = 5 current_size = 5 } }
province = { id = 857 naval_base = { size = 6 current_size = 6 } }
province = { id = 667 naval_base = { size = 8 current_size = 8 } }
province = { id = 851 naval_base = { size = 3 current_size = 3 } }
province = { id = 849 naval_base = { size = 6 current_size = 6 } }
province = { id = 4053 naval_base = { size = 8 current_size = 8 } }
province = { id = 6491 naval_base = { size = 6 current_size = 6 } }
province = { id = 885 naval_base = { size = 6 current_size = 6 } }
province = { id = 804 naval_base = { size = 6 current_size = 6 } }
province = { id = 890 naval_base = { size = 2 current_size = 2 } }
province = { id = 893 naval_base = { size = 2 current_size = 2 } }
province = { id = 892 naval_base = { size = 4 current_size = 4 } }
province = { id = 894 naval_base = { size = 8 current_size = 8 } }
province = { id = 654 naval_base = { size = 4 current_size = 4 } }
province = { id = 888 naval_base = { size = 3 current_size = 3 } }
province = { id = 889 naval_base = { size = 4 current_size = 4 } }
province = { id = 748 naval_base = { size = 8 current_size = 8 } }
province = { id = 651 naval_base = { size = 10 current_size = 10 } }
province = { id = 538 naval_base = { size = 4 current_size = 4 } }
province = { id = 632 naval_base = { size = 10 current_size = 10 } }
province = { id = 6464 naval_base = { size = 5 current_size = 5 } }
province = { id = 607 naval_base = { size = 6 current_size = 6 } }
province = { id = 608 naval_base = { size = 8 current_size = 8 } }
province = { id = 602 naval_base = { size = 10 current_size = 10 } }
province = { id = 601 naval_base = { size = 8 current_size = 8 } }
province = { id = 600 naval_base = { size = 10 current_size = 10 } }
province = { id = 579 naval_base = { size = 10 current_size = 10 } }
province = { id = 574 naval_base = { size = 10 current_size = 10 } }
province = { id = 576 naval_base = { size = 10 current_size = 10 } }
province = { id = 1 naval_base = { size = 4 current_size = 4 } }
province = { id = 30 naval_base = { size = 10 current_size = 10 } }
province = { id = 5 naval_base = { size = 10 current_size = 10 } }
province = { id = 3044 naval_base = { size = 5 current_size = 5 } }
province = { id = 1166 naval_base = { size = 4 current_size = 4 } }
province = { id = 28 naval_base = { size = 5 current_size = 5 } }
province = { id = 12 naval_base = { size = 8 current_size = 8 } }
province = { id = 23 naval_base = { size = 10 current_size = 10 } }
province = { id = 21 naval_base = { size = 10 current_size = 10 } }
province = { id = 20 naval_base = { size = 10 current_size = 10 } }
province = { id = 17 naval_base = { size = 10 current_size = 10 } }
province = { id = 154 naval_base = { size = 3 current_size = 3 } }
province = { id = 133 naval_base = { size = 7 current_size = 7 } }
province = { id = 2276 naval_base = { size = 3 current_size = 3 } }
province = { id = 3294 naval_base = { size = 10 current_size = 10 } }
province = { id = 98 naval_base = { size = 5 current_size = 5 } }
province = { id = 101 naval_base = { size = 5 current_size = 5 } }
province = { id = 141 naval_base = { size = 6 current_size = 6 } }
province = { id = 142 naval_base = { size = 4 current_size = 4 } }
province = { id = 187 naval_base = { size = 10 current_size = 10 } }
province = { id = 194 naval_base = { size = 4 current_size = 4 } }
province = { id = 197 naval_base = { size = 3 current_size = 3 } }
province = { id = 2606 naval_base = { size = 2 current_size = 2 } }
province = { id = 510 naval_base = { size = 10 current_size = 10 } }
province = { id = 303 naval_base = { size = 8 current_size = 8 } }
province = { id = 306 naval_base = { size = 8 current_size = 8 } }
province = { id = 296 naval_base = { size = 10 current_size = 10 } }
province = { id = 90 naval_base = { size = 10 current_size = 10 } }
province = { id = 294 naval_base = { size = 10 current_size = 10 } }
province = { id = 88 naval_base = { size = 10 current_size = 10 } }
province = { id = 87 naval_base = { size = 5 current_size = 5 } }
province = { id = 3256 naval_base = { size = 10 current_size = 10 } }
province = { id = 47 naval_base = { size = 10 current_size = 10 } }
province = { id = 46 naval_base = { size = 10 current_size = 10 } }
province = { id = 50 naval_base = { size = 10 current_size = 10 } }
province = { id = 45 naval_base = { size = 3 current_size = 3 } }
province = { id = 43 naval_base = { size = 3 current_size = 3 } }
province = { id = 38 naval_base = { size = 6 current_size = 6 } }
province = { id = 32 naval_base = { size = 10 current_size = 10 } }
province = { id = 3157 naval_base = { size = 6 current_size = 6 } }
province = { id = 35 naval_base = { size = 2 current_size = 2 } }
province = { id = 323 naval_base = { size = 6 current_size = 6 } }
province = { id = 334 naval_base = { size = 7 current_size = 7 } }
province = { id = 336 naval_base = { size = 10 current_size = 10 } }
province = { id = 1867 naval_base = { size = 3 current_size = 3 } }
province = { id = 1157 naval_base = { size = 7 current_size = 7 } }
province = { id = 348 naval_base = { size = 10 current_size = 10 } }
province = { id = 354 naval_base = { size = 3 current_size = 3 } }
province = { id = 535 naval_base = { size = 7 current_size = 7 } }
province = { id = 356 naval_base = { size = 7 current_size = 7 } }
province = { id = 364 naval_base = { size = 5 current_size = 5 } }
province = { id = 545 naval_base = { size = 6 current_size = 6 } }
province = { id = 534 naval_base = { size = 4 current_size = 4 } }
province = { id = 368 naval_base = { size = 10 current_size = 10 } }
province = { id = 521 naval_base = { size = 6 current_size = 6 } }
province = { id = 525 naval_base = { size = 2 current_size = 2 } }
province = { id = 3057 naval_base = { size = 4 current_size = 4 } }
province = { id = 523 naval_base = { size = 10 current_size = 10 } }
province = { id = 2621 naval_base = { size = 4 current_size = 4 } }
province = { id = 514 naval_base = { size = 2 current_size = 2 } }
province = { id = 378 naval_base = { size = 6 current_size = 6 } }
province = { id = 666 naval_base = { size = 4 current_size = 4 } }
province = { id = 3357 naval_base = { size = 6 current_size = 6 } }
province = { id = 384 naval_base = { size = 3 current_size = 3 } }
province = { id = 389 naval_base = { size = 3 current_size = 3 } }
province = { id = 391 naval_base = { size = 4 current_size = 4 } }
province = { id = 396 naval_base = { size = 2 current_size = 2 } }
province = { id = 398 naval_base = { size = 6 current_size = 6 } }
province = { id = 401 naval_base = { size = 10 current_size = 10 } }
province = { id = 439 naval_base = { size = 10 current_size = 10 } }
province = { id = 422 naval_base = { size = 5 current_size = 5 } }
province = { id = 423 naval_base = { size = 3 current_size = 3 } }
province = { id = 234 naval_base = { size = 4 current_size = 4 } }
province = { id = 253 naval_base = { size = 10 current_size = 10 } }
province = { id = 3431 naval_base = { size = 3 current_size = 3 } }
province = { id = 1159 naval_base = { size = 4 current_size = 4 } }
province = { id = 1794 naval_base = { size = 2 current_size = 2 } }
province = { id = 1798 naval_base = { size = 2 current_size = 2 } }
province = { id = 907 naval_base = { size = 10 current_size = 10 } }
province = { id = 901 naval_base = { size = 2 current_size = 2 } }
province = { id = 900 naval_base = { size = 1 current_size = 1 } }
province = { id = 920 naval_base = { size = 6 current_size = 6 } }
province = { id = 924 naval_base = { size = 2 current_size = 2 } }
province = { id = 31 naval_base = { size = 5 current_size = 5 } }
province = { id = 932 naval_base = { size = 2 current_size = 2 } }
province = { id = 939 naval_base = { size = 3 current_size = 3 } }
province = { id = 940 naval_base = { size = 2 current_size = 2 } }
province = { id = 949 naval_base = { size = 2 current_size = 2 } }
province = { id = 950 naval_base = { size = 6 current_size = 6 } }
province = { id = 958 naval_base = { size = 4 current_size = 4 } }
province = { id = 972 naval_base = { size = 2 current_size = 2 } }
province = { id = 963 naval_base = { size = 1 current_size = 1 } }
province = { id = 1146 naval_base = { size = 3 current_size = 3 } }
province = { id = 981 naval_base = { size = 2 current_size = 2 } }
province = { id = 983 naval_base = { size = 3 current_size = 3 } }
province = { id = 988 naval_base = { size = 2 current_size = 2 } }
province = { id = 992 naval_base = { size = 2 current_size = 2 } }
province = { id = 1090 naval_base = { size = 1 current_size = 1 } }
province = { id = 1093 naval_base = { size = 3 current_size = 3 } }
province = { id = 2750 naval_base = { size = 1 current_size = 1 } }
province = { id = 1094 naval_base = { size = 1 current_size = 1 } }
province = { id = 2751 naval_base = { size = 3 current_size = 3 } }
province = { id = 1101 naval_base = { size = 3 current_size = 3 } }
province = { id = 2643 naval_base = { size = 3 current_size = 3 } }
province = { id = 1116 naval_base = { size = 10 current_size = 10 } }
province = { id = 1118 naval_base = { size = 3 current_size = 3 } }
province = { id = 1123 naval_base = { size = 3 current_size = 3 } }
province = { id = 1137 naval_base = { size = 3 current_size = 3 } }
province = { id = 1058 naval_base = { size = 2 current_size = 2 } }
province = { id = 1056 naval_base = { size = 2 current_size = 2 } }
province = { id = 1037 naval_base = { size = 1 current_size = 1 } }
province = { id = 1038 naval_base = { size = 4 current_size = 4 } }
province = { id = 1033 naval_base = { size = 4 current_size = 4 } }
province = { id = 2862 naval_base = { size = 3 current_size = 3 } }
province = { id = 1813 naval_base = { size = 2 current_size = 2 } }
province = { id = 1819 naval_base = { size = 3 current_size = 3 } }
province = { id = 1823 naval_base = { size = 4 current_size = 4 } }
province = { id = 1497 naval_base = { size = 3 current_size = 3 } }
province = { id = 1481 naval_base = { size = 5 current_size = 5 } }
province = { id = 1505 naval_base = { size = 7 current_size = 7 } }
province = { id = 1517 naval_base = { size = 10 current_size = 10 } }
province = { id = 1817 naval_base = { size = 10 current_size = 10 } }
province = { id = 1299 naval_base = { size = 10 current_size = 10 } }
province = { id = 1353 naval_base = { size = 10 current_size = 10 } }
province = { id = 3128 naval_base = { size = 10 current_size = 10 } }
province = { id = 1337 naval_base = { size = 4 current_size = 4 } }
province = { id = 1333 naval_base = { size = 4 current_size = 4 } }
province = { id = 1359 naval_base = { size = 7 current_size = 7 } }
province = { id = 1613 naval_base = { size = 3 current_size = 3 } }
province = { id = 1632 naval_base = { size = 7 current_size = 7 } }
province = { id = 1658 naval_base = { size = 3 current_size = 3 } }
province = { id = 1653 naval_base = { size = 3 current_size = 3 } }
province = { id = 1737 naval_base = { size = 8 current_size = 8 } }
province = { id = 1739 naval_base = { size = 2 current_size = 2 } }
province = { id = 1665 naval_base = { size = 1 current_size = 1 } }
province = { id = 1668 naval_base = { size = 2 current_size = 2 } }
province = { id = 1666 naval_base = { size = 2 current_size = 2 } }
province = { id = 1677 naval_base = { size = 4 current_size = 4 } }
province = { id = 1670 naval_base = { size = 7 current_size = 7 } }
province = { id = 1669 naval_base = { size = 2 current_size = 2 } }
province = { id = 1682 naval_base = { size = 1 current_size = 1 } }
province = { id = 1622 naval_base = { size = 1 current_size = 1 } }
province = { id = 1683 naval_base = { size = 1 current_size = 1 } }
province = { id = 1689 naval_base = { size = 1 current_size = 1 } }
province = { id = 1692 naval_base = { size = 3 current_size = 3 } }
province = { id = 1703 naval_base = { size = 10 current_size = 10 } }
province = { id = 1712 naval_base = { size = 10 current_size = 10 } }
province = { id = 1723 naval_base = { size = 10 current_size = 10 } }
province = { id = 1722 naval_base = { size = 10 current_size = 10 } }
province = { id = 1871 naval_base = { size = 5 current_size = 5 } }
province = { id = 1609 naval_base = { size = 2 current_size = 2 } }
province = { id = 1753 naval_base = { size = 1 current_size = 1 } }
province = { id = 1755 naval_base = { size = 1 current_size = 1 } }
province = { id = 1769 naval_base = { size = 1 current_size = 1 } }
province = { id = 1766 naval_base = { size = 1 current_size = 1 } }
province = { id = 7242 naval_base = { size = 10 current_size = 10 } }
province = { id = 662 naval_base = { size = 1 current_size = 1 } }
province = { id = 1607 naval_base = { size = 1 current_size = 1 } }
province = { id = 1686 naval_base = { size = 1 current_size = 1 } }
province = { id = 1603 naval_base = { size = 1 current_size = 1 } }
province = { id = 1602 naval_base = { size = 2 current_size = 2 } }
province = { id = 1617 naval_base = { size = 2 current_size = 2 } }
province = { id = 1600 naval_base = { size = 1 current_size = 1 } }
province = { id = 1601 naval_base = { size = 2 current_size = 2 } }
province = { id = 1604 naval_base = { size = 2 current_size = 2 } }
province = { id = 1618 naval_base = { size = 10 current_size = 10 } }
province = { id = 1620 naval_base = { size = 2 current_size = 2 } }
province = { id = 1621 naval_base = { size = 1 current_size = 1 } }
province = { id = 1786 naval_base = { size = 4 current_size = 4 } }
province = { id = 1624 naval_base = { size = 4 current_size = 4 } }
province = { id = 1627 naval_base = { size = 2 current_size = 2 } }
province = { id = 1785 naval_base = { size = 1 current_size = 1 } }
province = { id = 1599 naval_base = { size = 1 current_size = 1 } }
province = { id = 1321 naval_base = { size = 10 current_size = 10 } }
province = { id = 1318 naval_base = { size = 5 current_size = 5 } }
province = { id = 1313 naval_base = { size = 5 current_size = 5 } }
province = { id = 1316 naval_base = { size = 3 current_size = 3 } }
province = { id = 1315 naval_base = { size = 10 current_size = 10 } }
province = { id = 1323 naval_base = { size = 4 current_size = 4 } }
province = { id = 1237 naval_base = { size = 10 current_size = 10 } }
province = { id = 2529 naval_base = { size = 4 current_size = 4 } }
province = { id = 3090 naval_base = { size = 5 current_size = 5 } }
province = { id = 1197 naval_base = { size = 10 current_size = 10 } }
province = { id = 1193 naval_base = { size = 6 current_size = 6 } }
province = { id = 1190 naval_base = { size = 10 current_size = 10 } }
province = { id = 1189 naval_base = { size = 10 current_size = 10 } }
province = { id = 1188 naval_base = { size = 10 current_size = 10 } }
province = { id = 1187 naval_base = { size = 10 current_size = 10 } }
province = { id = 1174 naval_base = { size = 10 current_size = 10 } }
province = { id = 1185 naval_base = { size = 10 current_size = 10 } }
province = { id = 1184 naval_base = { size = 10 current_size = 10 } }
province = { id = 1181 naval_base = { size = 10 current_size = 10 } }
province = { id = 1372 naval_base = { size = 10 current_size = 10 } }

province = { id = 332 air_base = { size = 1 current_size = 1 } }
province = { id = 1726 air_base = { size = 1 current_size = 1 } }
province = { id = 3184 air_base = { size = 1 current_size = 1 } }
province = { id = 962 air_base = { size = 1 current_size = 1 } }
province = { id = 1532 air_base = { size = 2 current_size = 2 } }
province = { id = 330 air_base = { size = 2 current_size = 2 } }
province = { id = 350 air_base = { size = 1 current_size = 1 } }
province = { id = 1161 air_base = { size = 1 current_size = 1 } }
province = { id = 2019 air_base = { size = 1 current_size = 1 } }
province = { id = 2885 air_base = { size = 1 current_size = 1 } }
province = { id = 2496 air_base = { size = 2 current_size = 2 } }
province = { id = 4157 air_base = { size = 2 current_size = 2 } }
province = { id = 1823 air_base = { size = 2 current_size = 2 } }
province = { id = 1267 air_base = { size = 1 current_size = 1 } }
province = { id = 1232 air_base = { size = 2 current_size = 2 } }
province = { id = 1276 air_base = { size = 1 current_size = 1 } }
province = { id = 1433 air_base = { size = 1 current_size = 1 } }
province = { id = 1237 air_base = { size = 3 current_size = 3 } }
province = { id = 5628 air_base = { size = 1 current_size = 1 } }
province = { id = 1397 air_base = { size = 2 current_size = 2 } }
province = { id = 549 air_base = { size = 4 current_size = 4 } }
province = { id = 541 air_base = { size = 10 current_size = 10 } }
province = { id = 797 air_base = { size = 4 current_size = 4 } }
province = { id = 569 air_base = { size = 5 current_size = 5 } }
province = { id = 588 air_base = { size = 6 current_size = 6 } }
province = { id = 574 air_base = { size = 3 current_size = 3 } }
province = { id = 579 air_base = { size = 5 current_size = 5 } }
province = { id = 576 air_base = { size = 6 current_size = 6 } }
province = { id = 600 air_base = { size = 10 current_size = 10 } }
province = { id = 595 air_base = { size = 4 current_size = 4 } }
province = { id = 592 air_base = { size = 4 current_size = 4 } }
province = { id = 602 air_base = { size = 10 current_size = 10 } }
province = { id = 538 air_base = { size = 4 current_size = 4 } }
province = { id = 614 air_base = { size = 4 current_size = 4 } }
province = { id = 606 air_base = { size = 10 current_size = 10 } }
province = { id = 632 air_base = { size = 10 current_size = 10 } }
province = { id = 640 air_base = { size = 4 current_size = 4 } }
province = { id = 620 air_base = { size = 10 current_size = 10 } }
province = { id = 616 air_base = { size = 4 current_size = 4 } }
province = { id = 621 air_base = { size = 4 current_size = 4 } }
province = { id = 693 air_base = { size = 4 current_size = 4 } }
province = { id = 689 air_base = { size = 4 current_size = 4 } }
province = { id = 673 air_base = { size = 4 current_size = 4 } }
province = { id = 637 air_base = { size = 4 current_size = 4 } }
province = { id = 644 air_base = { size = 4 current_size = 4 } }
province = { id = 670 air_base = { size = 4 current_size = 4 } }
province = { id = 678 air_base = { size = 4 current_size = 4 } }
province = { id = 648 air_base = { size = 4 current_size = 4 } }
province = { id = 651 air_base = { size = 10 current_size = 10 } }
province = { id = 748 air_base = { size = 6 current_size = 6 } }
province = { id = 716 air_base = { size = 4 current_size = 4 } }
province = { id = 793 air_base = { size = 4 current_size = 4 } }
province = { id = 789 air_base = { size = 4 current_size = 4 } }
province = { id = 707 air_base = { size = 4 current_size = 4 } }
province = { id = 725 air_base = { size = 4 current_size = 4 } }
province = { id = 730 air_base = { size = 4 current_size = 4 } }
province = { id = 733 air_base = { size = 10 current_size = 10 } }
province = { id = 761 air_base = { size = 10 current_size = 10 } }
province = { id = 762 air_base = { size = 4 current_size = 4 } }
province = { id = 765 air_base = { size = 10 current_size = 10 } }
province = { id = 764 air_base = { size = 4 current_size = 4 } }
province = { id = 780 air_base = { size = 10 current_size = 10 } }
province = { id = 698 air_base = { size = 4 current_size = 4 } }
province = { id = 754 air_base = { size = 2 current_size = 2 } }
province = { id = 894 air_base = { size = 4 current_size = 4 } }
province = { id = 889 air_base = { size = 4 current_size = 4 } }
province = { id = 890 air_base = { size = 1 current_size = 1 } }
province = { id = 804 air_base = { size = 1 current_size = 1 } }
province = { id = 873 air_base = { size = 4 current_size = 4 } }
province = { id = 815 air_base = { size = 1 current_size = 1 } }
province = { id = 830 air_base = { size = 1 current_size = 1 } }
province = { id = 832 air_base = { size = 4 current_size = 4 } }
province = { id = 846 air_base = { size = 4 current_size = 4 } }
province = { id = 860 air_base = { size = 4 current_size = 4 } }
province = { id = 866 air_base = { size = 2 current_size = 2 } }
province = { id = 667 air_base = { size = 3 current_size = 3 } }
province = { id = 851 air_base = { size = 3 current_size = 3 } }
province = { id = 849 air_base = { size = 1 current_size = 1 } }
province = { id = 4053 air_base = { size = 4 current_size = 4 } }
province = { id = 886 air_base = { size = 4 current_size = 4 } }
province = { id = 885 air_base = { size = 4 current_size = 4 } }
province = { id = 1116 air_base = { size = 10 current_size = 10 } }
province = { id = 1118 air_base = { size = 1 current_size = 1 } }
province = { id = 2798 air_base = { size = 1 current_size = 1 } }
province = { id = 1123 air_base = { size = 1 current_size = 1 } }
province = { id = 1101 air_base = { size = 1 current_size = 1 } }
province = { id = 2751 air_base = { size = 1 current_size = 1 } }
province = { id = 1094 air_base = { size = 1 current_size = 1 } }
province = { id = 1061 air_base = { size = 4 current_size = 4 } }
province = { id = 1058 air_base = { size = 2 current_size = 2 } }
province = { id = 1056 air_base = { size = 2 current_size = 2 } }
province = { id = 1038 air_base = { size = 2 current_size = 2 } }
province = { id = 1033 air_base = { size = 4 current_size = 4 } }
province = { id = 1046 air_base = { size = 2 current_size = 2 } }
province = { id = 1066 air_base = { size = 4 current_size = 4 } }
province = { id = 903 air_base = { size = 2 current_size = 2 } }
province = { id = 907 air_base = { size = 7 current_size = 7 } }
province = { id = 1075 air_base = { size = 1 current_size = 1 } }
province = { id = 1098 air_base = { size = 1 current_size = 1 } }
province = { id = 1008 air_base = { size = 4 current_size = 4 } }
province = { id = 1002 air_base = { size = 4 current_size = 4 } }
province = { id = 988 air_base = { size = 4 current_size = 4 } }
province = { id = 981 air_base = { size = 4 current_size = 4 } }
province = { id = 1146 air_base = { size = 1 current_size = 1 } }
province = { id = 1867 air_base = { size = 4 current_size = 4 } }
province = { id = 963 air_base = { size = 2 current_size = 2 } }
province = { id = 972 air_base = { size = 2 current_size = 2 } }
province = { id = 958 air_base = { size = 4 current_size = 4 } }
province = { id = 953 air_base = { size = 4 current_size = 4 } }
province = { id = 950 air_base = { size = 4 current_size = 4 } }
province = { id = 939 air_base = { size = 4 current_size = 4 } }
province = { id = 932 air_base = { size = 4 current_size = 4 } }
province = { id = 924 air_base = { size = 4 current_size = 4 } }
province = { id = 920 air_base = { size = 4 current_size = 4 } }
province = { id = 31 air_base = { size = 4 current_size = 4 } }
province = { id = 336 air_base = { size = 10 current_size = 10 } }
province = { id = 347 air_base = { size = 4 current_size = 4 } }
province = { id = 354 air_base = { size = 2 current_size = 2 } }
province = { id = 341 air_base = { size = 2 current_size = 2 } }
province = { id = 356 air_base = { size = 4 current_size = 4 } }
province = { id = 535 air_base = { size = 4 current_size = 4 } }
province = { id = 334 air_base = { size = 4 current_size = 4 } }
province = { id = 59 air_base = { size = 5 current_size = 5 } }
province = { id = 364 air_base = { size = 3 current_size = 3 } }
province = { id = 365 air_base = { size = 4 current_size = 4 } }
province = { id = 529 air_base = { size = 3 current_size = 3 } }
province = { id = 61 air_base = { size = 6 current_size = 6 } }
province = { id = 38 air_base = { size = 2 current_size = 2 } }
province = { id = 56 air_base = { size = 6 current_size = 6 } }
province = { id = 63 air_base = { size = 3 current_size = 3 } }
province = { id = 55 air_base = { size = 3 current_size = 3 } }
province = { id = 72 air_base = { size = 6 current_size = 6 } }
province = { id = 51 air_base = { size = 6 current_size = 6 } }
province = { id = 50 air_base = { size = 3 current_size = 3 } }
province = { id = 532 air_base = { size = 4 current_size = 4 } }
province = { id = 47 air_base = { size = 10 current_size = 10 } }
province = { id = 30 air_base = { size = 4 current_size = 4 } }
province = { id = 23 air_base = { size = 10 current_size = 10 } }
province = { id = 22 air_base = { size = 4 current_size = 4 } }
province = { id = 21 air_base = { size = 10 current_size = 10 } }
province = { id = 20 air_base = { size = 10 current_size = 10 } }
province = { id = 17 air_base = { size = 10 current_size = 10 } }
province = { id = 13 air_base = { size = 10 current_size = 10 } }
province = { id = 9 air_base = { size = 4 current_size = 4 } }
province = { id = 5 air_base = { size = 4 current_size = 4 } }
province = { id = 1 air_base = { size = 4 current_size = 4 } }
province = { id = 3294 air_base = { size = 5 current_size = 5 } }
province = { id = 107 air_base = { size = 4 current_size = 4 } }
province = { id = 2276 air_base = { size = 1 current_size = 1 } }
province = { id = 101 air_base = { size = 3 current_size = 3 } }
province = { id = 98 air_base = { size = 3 current_size = 3 } }
province = { id = 292 air_base = { size = 4 current_size = 4 } }
province = { id = 294 air_base = { size = 10 current_size = 10 } }
province = { id = 90 air_base = { size = 4 current_size = 4 } }
province = { id = 296 air_base = { size = 4 current_size = 4 } }
province = { id = 300 air_base = { size = 10 current_size = 10 } }
province = { id = 473 air_base = { size = 10 current_size = 10 } }
province = { id = 87 air_base = { size = 2 current_size = 2 } }
province = { id = 3256 air_base = { size = 4 current_size = 4 } }
province = { id = 67 air_base = { size = 4 current_size = 4 } }
province = { id = 313 air_base = { size = 4 current_size = 4 } }
province = { id = 82 air_base = { size = 10 current_size = 10 } }
province = { id = 314 air_base = { size = 4 current_size = 4 } }
province = { id = 376 air_base = { size = 10 current_size = 10 } }
province = { id = 510 air_base = { size = 10 current_size = 10 } }
province = { id = 377 air_base = { size = 4 current_size = 4 } }
province = { id = 463 air_base = { size = 10 current_size = 10 } }
province = { id = 469 air_base = { size = 3 current_size = 3 } }
province = { id = 476 air_base = { size = 1 current_size = 1 } }
province = { id = 457 air_base = { size = 8 current_size = 8 } }
province = { id = 303 air_base = { size = 4 current_size = 4 } }
province = { id = 306 air_base = { size = 4 current_size = 4 } }
province = { id = 483 air_base = { size = 4 current_size = 4 } }
province = { id = 480 air_base = { size = 3 current_size = 3 } }
province = { id = 229 air_base = { size = 4 current_size = 4 } }
province = { id = 485 air_base = { size = 6 current_size = 6 } }
province = { id = 1876 air_base = { size = 3 current_size = 3 } }
province = { id = 207 air_base = { size = 2 current_size = 2 } }
province = { id = 2606 air_base = { size = 1 current_size = 1 } }
province = { id = 197 air_base = { size = 1 current_size = 1 } }
province = { id = 194 air_base = { size = 2 current_size = 2 } }
province = { id = 142 air_base = { size = 3 current_size = 3 } }
province = { id = 141 air_base = { size = 2 current_size = 2 } }
province = { id = 3327 air_base = { size = 5 current_size = 5 } }
province = { id = 139 air_base = { size = 4 current_size = 4 } }
province = { id = 137 air_base = { size = 2 current_size = 2 } }
province = { id = 132 air_base = { size = 1 current_size = 1 } }
province = { id = 424 air_base = { size = 5 current_size = 5 } }
province = { id = 423 air_base = { size = 1 current_size = 1 } }
province = { id = 422 air_base = { size = 4 current_size = 4 } }
province = { id = 453 air_base = { size = 6 current_size = 6 } }
province = { id = 384 air_base = { size = 2 current_size = 2 } }
province = { id = 390 air_base = { size = 2 current_size = 2 } }
province = { id = 401 air_base = { size = 4 current_size = 4 } }
province = { id = 396 air_base = { size = 2 current_size = 2 } }
province = { id = 398 air_base = { size = 4 current_size = 4 } }
province = { id = 3357 air_base = { size = 1 current_size = 1 } }
province = { id = 666 air_base = { size = 2 current_size = 2 } }
province = { id = 378 air_base = { size = 6 current_size = 6 } }
province = { id = 370 air_base = { size = 10 current_size = 10 } }
province = { id = 531 air_base = { size = 8 current_size = 8 } }
province = { id = 368 air_base = { size = 10 current_size = 10 } }
province = { id = 545 air_base = { size = 4 current_size = 4 } }
province = { id = 534 air_base = { size = 4 current_size = 4 } }
province = { id = 514 air_base = { size = 2 current_size = 2 } }
province = { id = 515 air_base = { size = 10 current_size = 10 } }
province = { id = 521 air_base = { size = 4 current_size = 4 } }
province = { id = 2621 air_base = { size = 4 current_size = 4 } }
province = { id = 523 air_base = { size = 10 current_size = 10 } }
province = { id = 525 air_base = { size = 4 current_size = 4 } }
province = { id = 3057 air_base = { size = 6 current_size = 6 } }
province = { id = 444 air_base = { size = 4 current_size = 4 } }
province = { id = 439 air_base = { size = 6 current_size = 6 } }
province = { id = 448 air_base = { size = 6 current_size = 6 } }
province = { id = 1848 air_base = { size = 4 current_size = 4 } }
province = { id = 1838 air_base = { size = 4 current_size = 4 } }
province = { id = 163 air_base = { size = 4 current_size = 4 } }
province = { id = 253 air_base = { size = 6 current_size = 6 } }
province = { id = 1827 air_base = { size = 2 current_size = 2 } }
province = { id = 233 air_base = { size = 4 current_size = 4 } }
province = { id = 249 air_base = { size = 2 current_size = 2 } }
province = { id = 258 air_base = { size = 4 current_size = 4 } }
province = { id = 269 air_base = { size = 2 current_size = 2 } }
province = { id = 248 air_base = { size = 2 current_size = 2 } }
province = { id = 236 air_base = { size = 2 current_size = 2 } }
province = { id = 227 air_base = { size = 1 current_size = 1 } }
province = { id = 238 air_base = { size = 8 current_size = 8 } }
province = { id = 273 air_base = { size = 2 current_size = 2 } }
province = { id = 220 air_base = { size = 8 current_size = 8 } }
province = { id = 217 air_base = { size = 2 current_size = 2 } }
province = { id = 264 air_base = { size = 2 current_size = 2 } }
province = { id = 281 air_base = { size = 3 current_size = 3 } }
province = { id = 282 air_base = { size = 5 current_size = 5 } }
province = { id = 1597 air_base = { size = 4 current_size = 4 } }
province = { id = 219 air_base = { size = 2 current_size = 2 } }
province = { id = 181 air_base = { size = 3 current_size = 3 } }
province = { id = 175 air_base = { size = 10 current_size = 10 } }
province = { id = 174 air_base = { size = 2 current_size = 2 } }
province = { id = 201 air_base = { size = 6 current_size = 6 } }
province = { id = 187 air_base = { size = 10 current_size = 10 } }
province = { id = 190 air_base = { size = 2 current_size = 2 } }
province = { id = 133 air_base = { size = 4 current_size = 4 } }
province = { id = 154 air_base = { size = 4 current_size = 4 } }
province = { id = 1832 air_base = { size = 3 current_size = 3 } }
province = { id = 3711 air_base = { size = 2 current_size = 2 } }
province = { id = 1828 air_base = { size = 4 current_size = 4 } }
province = { id = 1574 air_base = { size = 1 current_size = 1 } }
province = { id = 1552 air_base = { size = 1 current_size = 1 } }
province = { id = 1544 air_base = { size = 2 current_size = 2 } }
province = { id = 1416 air_base = { size = 3 current_size = 3 } }
province = { id = 1520 air_base = { size = 2 current_size = 2 } }
province = { id = 1525 air_base = { size = 1 current_size = 1 } }
province = { id = 1368 air_base = { size = 1 current_size = 1 } 
anti_air = 2 
naval_base = { size = 2 current_size = 2 } }
province = { id = 1366 air_base = { size = 4 current_size = 4 } }
province = { id = 1372 air_base = { size = 10 current_size = 10 } }
province = { id = 1404 air_base = { size = 1 current_size = 1 } }
province = { id = 1794 air_base = { size = 4 current_size = 4 } }
province = { id = 1798 air_base = { size = 4 current_size = 4 } }
province = { id = 1866 air_base = { size = 4 current_size = 4 } }
province = { id = 1804 air_base = { size = 1 current_size = 1 } }
province = { id = 1819 air_base = { size = 1 current_size = 1 } }
province = { id = 1497 air_base = { size = 1 current_size = 1 } }
province = { id = 1481 air_base = { size = 5 current_size = 5 } }
province = { id = 1469 air_base = { size = 2 current_size = 2 } }
province = { id = 1467 air_base = { size = 2 current_size = 2 } }
province = { id = 1505 air_base = { size = 7 current_size = 7 } }
province = { id = 1514 air_base = { size = 4 current_size = 4 } }
province = { id = 1817 air_base = { size = 6 current_size = 6 } }
province = { id = 1517 air_base = { size = 10 current_size = 10 } }
province = { id = 1516 air_base = { size = 2 current_size = 2 } }
province = { id = 1457 air_base = { size = 4 current_size = 4 } }
province = { id = 1296 air_base = { size = 4 current_size = 4 } }
province = { id = 1299 air_base = { size = 4 current_size = 4 } }
province = { id = 1345 air_base = { size = 4 current_size = 4 } }
province = { id = 1333 air_base = { size = 4 current_size = 4 } }
province = { id = 1337 air_base = { size = 4 current_size = 4 } }
province = { id = 1353 air_base = { size = 8 current_size = 8 } }
province = { id = 1644 air_base = { size = 4 current_size = 4 } }
province = { id = 1359 air_base = { size = 4 current_size = 4 } }
province = { id = 1613 air_base = { size = 4 current_size = 4 } }
province = { id = 1658 air_base = { size = 1 current_size = 1 } }
province = { id = 1653 air_base = { size = 2 current_size = 2 } }
province = { id = 1737 air_base = { size = 1 current_size = 1 } }
province = { id = 1739 air_base = { size = 5 current_size = 5 } }
province = { id = 1321 air_base = { size = 6 current_size = 6 } }
province = { id = 1313 air_base = { size = 3 current_size = 3 } }
province = { id = 1922 air_base = { size = 1 current_size = 1 } }
province = { id = 559  air_base = { size = 2 current_size = 2 } }
province = { id = 1316 air_base = { size = 1 current_size = 1 } }
province = { id = 1315 air_base = { size = 4 current_size = 4 } }
province = { id = 1323 air_base = { size = 8 current_size = 8 } }
province = { id = 1360 air_base = { size = 3 current_size = 3 } }
province = { id = 2569 air_base = { size = 4 current_size = 4 } }
province = { id = 1244 air_base = { size = 1 current_size = 1 } }
province = { id = 1238 air_base = { size = 4 current_size = 4 } }
province = { id = 2533 air_base = { size = 4 current_size = 4 } }
province = { id = 1205 air_base = { size = 5 current_size = 5 } anti_air = 2 }
province = { id = 1379 air_base = { size = 2 current_size = 2 } }
province = { id = 3090 air_base = { size = 7 current_size = 7 } }
province = { id = 1391 air_base = { size = 4 current_size = 4 } }
province = { id = 1197 air_base = { size = 10 current_size = 10 } }
province = { id = 1181 air_base = { size = 10 current_size = 10 } }
province = { id = 1184 air_base = { size = 10 current_size = 10 } }
province = { id = 1185 air_base = { size = 10 current_size = 10 } }
province = { id = 1186 air_base = { size = 10 current_size = 10 } }
province = { id = 1187 air_base = { size = 10 current_size = 10 } }
province = { id = 1189 air_base = { size = 10 current_size = 10 } }
province = { id = 1188 air_base = { size = 10 current_size = 10 } }
province = { id = 1190 air_base = { size = 10 current_size = 10 } }
province = { id = 1193 air_base = { size = 6 current_size = 6 } }
province = { id = 1599 air_base = { size = 1 current_size = 1 } }
province = { id = 1785 air_base = { size = 1 current_size = 1 } }
province = { id = 1627 air_base = { size = 4 current_size = 4 } }
province = { id = 1624 air_base = { size = 4 current_size = 4 } }
province = { id = 1681 air_base = { size = 1 current_size = 1 } }
province = { id = 1666 air_base = { size = 2 current_size = 2 } }
province = { id = 1672 air_base = { size = 1 current_size = 1 } }
province = { id = 1677 air_base = { size = 2 current_size = 2 } }
province = { id = 5856 air_base = { size = 1 current_size = 1 } }
province = { id = 1670 air_base = { size = 2 current_size = 2 } }
province = { id = 1703 air_base = { size = 10 current_size = 10 } }
province = { id = 1712 air_base = { size = 10 current_size = 10 } }
province = { id = 1727 air_base = { size = 10 current_size = 10 } }
province = { id = 1722 air_base = { size = 10 current_size = 10 } }
province = { id = 1871 air_base = { size = 3 current_size = 3 } }
province = { id = 1622 air_base = { size = 1 current_size = 1 } }
province = { id = 1689 air_base = { size = 1 current_size = 1 } }
province = { id = 1609 air_base = { size = 1 current_size = 1 } }
province = { id = 1621 air_base = { size = 2 current_size = 2 } }
province = { id = 1620 air_base = { size = 1 current_size = 1 } }
province = { id = 1619 air_base = { size = 1 current_size = 1 } }
province = { id = 7196 air_base = { size = 10 current_size = 10 } }
province = { id = 1618 air_base = { size = 1 current_size = 1 } }
province = { id = 1601 air_base = { size = 4 current_size = 4 } }
province = { id = 1602 air_base = { size = 4 current_size = 4 } }
province = { id = 1608 air_base = { size = 2 current_size = 2 } }
province = { id = 1603 air_base = { size = 2 current_size = 2 } }
province = { id = 1605 air_base = { size = 1 current_size = 1 } }
province = { id = 1607 air_base = { size = 1 current_size = 1 } }
province = { id = 1786 air_base = { size = 4 current_size = 4 } }
province = { id = 662 air_base = { size = 2 current_size = 2 } }
province = { id = 1766 air_base = { size = 1 current_size = 1 } }
province = { id = 660 air_base = { size = 1 current_size = 1 } }
province = { id = 7242 air_base = { size = 10 current_size = 10 } }
province = { id = 659 air_base = { size = 2 current_size = 2 } }
province = { id = 658 air_base = { size = 1 current_size = 1 } }
province = { id = 1765 air_base = { size = 1 current_size = 1 } }
province = { id = 1760 air_base = { size = 1 current_size = 1 } }

 #.#.# Abyssinia 
 
province = { id = 1046   # Addis Abeba - North Ethiopia - Ethiopia
   anti_air = 1 
 } 
 
province = { id = 1054   # Kelafo - Ethiopian Highland - Ethiopia
   landfort = 1 
 } 
 
province = { id = 1051   # Harer - Ethiopian Highland - Ethiopia
   landfort = 1 
 } 
 
 #.#.# Albania 
 
province = { id = 390   # Tirana - Albania - Balkan
   anti_air = 1 
 } 
 
province = { id = 391   # Vlore - Albania - Balkan
   anti_air = 1 
 } 
 
 #.#.# Argentina 
 
province = { id = 667   # La Plata - La Plata - Rio de la Plata
   anti_air = 2 
 } 
 
province = { id = 851   # Buenos Aires - La Plata - Rio de la Plata
   anti_air = 3 
 } 
 
province = { id = 857   # Mar del Plata - La Plata - Rio de la Plata
   anti_air = 3 
 }  
 
 #.#.# Australia 

province = { id = 5856   # Samarai - Lae - New Guinea
   anti_air = 1 
 } 

province = { id = 1677   # Port Moresby - Port Moresby - New Guinea
   anti_air = 1 
 } 
 
province = { id = 1712   # Bunbury - Perth - Australia
   anti_air = 5 
   coastalfort = 1 
 } 
 
province = { id = 1703   # Darwin - Darwin - Australia
   anti_air = 5 
 } 
 
province = { id = 1722   # Brisbane - Brisbane - Australia
   anti_air = 4 
 } 
 
province = { id = 1724   # Wollongong - Sydney - Australia
   anti_air = 3 
   coastalfort = 2 
 } 
 
province = { id = 1727   # Canberra - Sydney - Australia
   anti_air = 4 
 } 
 
province = { id = 1730   # Melbourne - Melbourne - Australia
   coastalfort = 1 
   anti_air = 3 
 } 
 
province = { id = 1718   # Adelaide - Adelaide - Australia
   anti_air = 1 
 } 
 
province = { id = 1733   # Mount Gambier - Adelaide - Australia
   anti_air = 2 
 } 
 
province = { id = 1670   # Rabaul - Rabaul - Bismarck Archipelago
   anti_air = 2 
 } 
 
 #.#.# Austria 
 
province = { id = 377   # Innsbruck - Austria - Austria
   anti_air = 2 
 } 
 
province = { id = 461   # Klagenfurt - Austria - Austria
   anti_air = 1 
 } 
 
province = { id = 463   # Vienna - Austria - Austria
   anti_air = 4 
 } 
 
 #.#.# Belgium 
 
province = { id = 45   # Bruges - Flanders - Benelux
   anti_air = 1 
 } 
 
province = { id = 50   # Antwerpen - Flanders - Benelux
   anti_air = 2 
 } 
 
province = { id = 51   # Brussels - Flanders - Benelux
   anti_air = 1 
 } 
 
province = { id = 68   # Liege - Wallonia - Benelux
   landfort = 2 
   anti_air = 2 
 } 
 
 #.#.# Bolivia 
 
province = { id = 832   # Nuestra Senora de La Paz - La Paz - Andes
   anti_air = 1 
 } 
 
 #.#.# Brazil 
 
province = { id = 847   # Curitiba - Sao Paulo - Brazilian Highlands
   anti_air = 1 
 } 
 
province = { id = 848   # Porto Alegre - Sao Paulo - Brazilian Highlands
   anti_air = 2 
 } 
 
province = { id = 886   # Sao Paulo - Sao Paulo - Brazilian Highlands
   anti_air = 1 
 } 
 
province = { id = 883   # Goiania - Brasilia - Brazilian Highlands
   anti_air = 2 
 } 
 
province = { id = 885   # Rio de Janeiro - Rio de Janeiro - Brazilian Highlands
   anti_air = 1 
 } 
 
 #.#.# British Raj 
 
province = { id = 1296   # Lahri: - North Burma - Indochine
   anti_air = 1 
 } 
 
province = { id = 1299   # Rangoon - Burma - Indochine
   anti_air = 3 
 } 
 
province = { id = 1457   # Calcutta - Bengal - India
   anti_air = 2 
 } 
 
province = { id = 1469   # Delhi - Delhi - India
   anti_air = 2 
 } 
 
province = { id = 1514   # Trivandrum - Western Ghat - India
   anti_air = 1 
 } 
 
province = { id = 1505   # Bombay - Bombay - India
   anti_air = 3 
 } 
 
province = { id = 1467   # Gwalior - Rajastan - India
   anti_air = 1 
 } 
 
province = { id = 1481   # Karachi - Pakistan - India
   anti_air = 1 
 } 
 
 #.#.# Bulgaria 
 
province = { id = 417   # Sofia - Bulgaria - Balkan
   anti_air = 2 
 } 
 
province = { id = 422   # Burgas - Bulgaria - Balkan
   anti_air = 2 
 } 
 
 #.#.# Canada 
 
province = { id = 541   # Vancouver - British Columbia - Western Canada
   anti_air = 3 
 }

province = { id = 556   # Victoria - British Columbia - Western Canada
   anti_air = 2  
   coastalfort = 2 
 }  
 
province = { id = 797   # Calgary - Alberta - Western Canada
   anti_air = 1 
 } 
 
province = { id = 569   # Winnipeg - Manitoba - Canada
   anti_air = 1 
 } 
 
province = { id = 588   # Ottawa - Ontario - Canada
   anti_air = 3 
 } 
 
province = { id = 589   # Toronto - Ontario - Canada
   anti_air = 2 
 } 

province = { id = 574   # Quebec city - Quebec - Eastern Canada
   anti_air = 3 
   landfort = 6
   coastalfort = 2 
 }  

province = { id = 585   # Montreal - Quebec - Eastern Canada
   anti_air = 2 
 } 
 
province = { id = 579   # Halifax - Nova Scotia - Eastern Canada
   anti_air = 1 
   coastalfort = 6 
 }
 
 #.#.# Chile 
 
province = { id = 860   # Santiago de Chile - Chile - Andes
   anti_air = 2 
 } 
 
 #.#.# China com 

province = { id = 5581
   landfort = 3 
 } 
province = { id = 5583
   landfort = 3 
 } 
province = { id = 5584
   landfort = 3 
 } 
  
 #.#.# China Fengtian 
 
province = { id = 1321   # Qiongshan - Guangdong - China
   anti_air = 2 
 } 
 
 #.#.# China National 

province = { id = 2533   # Jinan - Shandong - China
   anti_air = 2 
 } 
 
 province = { id = 1267   # Xian
   landfort = 2
   anti_air = 1
 } 
 
 province = { id = 1235   # Nanjing
   landfort = 2
   anti_air = 2
 } 
 
 province = { id = 1232   # Wuhan
   landfort = 2
 } 

 #.#.# Columbia 
 
province = { id = 890   # Barranquilla - Panaman Ridge - Grand Colombia
   anti_air = 2 
 } 
 
province = { id = 812   # Santa Fe de Bogota - Maracaibo - Grand Colombia
   anti_air = 2 
 } 
 
 #.#.# Costa Rica 
 
province = { id = 540   # San Jose - Nicaragua - Central America
   anti_air = 1 
 } 
 
 #.#.# Cuba 
 
province = { id = 654   # Havana - Cuba - Caribbean
   anti_air = 1 
 } 
 
 #.#.# Czechoslovakia 
 
province = { id = 475   # Brno - Bohemia - Czechoslovakia
   anti_air = 2 
 } 
  
province = { id = 468   # Hradec Kralove - Bohemia - Czechoslovakia
   landfort = 2 
 } 
 
province = { id = 467   # Znojmo - Bohemia - Czechoslovakia
   landfort = 5 
 } 
 
province = { id = 471   # Liberec - Bohemia - Czechoslovakia
   landfort = 3 
 } 
 
 province = { id = 3262   # Usti nad Labem - Bohemia - Czechoslovakia
   landfort = 3 
 } 
 
province = { id = 2296   # Tesin - Bohemia - Czechoslovakia
   landfort = 3 
 } 
 
province = { id = 53   # Prachatice - Bohemia - Czechoslovakia
   landfort = 4 
 } 
 
province = { id = 466   # Karlovy Vary - Bohemia - Czechoslovakia
   landfort = 4 
 } 
 
province = { id = 472   # Opava - Bohemia - Czechoslovakia
   landfort = 6 
 } 
  
province = { id = 6518   # Sumperk - Bohemia - Czechoslovakia
   landfort = 6 
 }
 
province = { id = 469   # Prague - Bohemia - Czechoslovakia
   anti_air = 2 
 } 
 
province = { id = 476   # Bratislava - Slovakia - Czechoslovakia
   anti_air = 2 
   landfort = 3 
 } 
 
province = { id = 490   # Kosice - Slovakia - Czechoslovakia
   landfort = 3 
 } 
 
province = { id = 1889   # Komarno - Slovakia - Czechoslovakia
   landfort = 2 
 } 
 
province = { id = 2302   # Uzhorod - Slovakia - Czechoslovakia
   landfort = 1 
 } 
 
 # Spain
 
province = { id = 350   # Granada - East Andalucia - Spain
   anti_air = 2 
   landfort = 2 
 } 
 
 #.#.# Denmark 
 
province = { id = 1   # Reykjavik - Iceland - Iceland
   anti_air = 1 
 } 
 
province = { id = 292   # Frederikshavn - Denmark - Denmark
   anti_air = 1 
 } 
 
province = { id = 294   # Copenhagen - Denmark - Denmark
   anti_air = 2 
 } 
 
 #.#.# Ecuador 
 
province = { id = 815   # San Francisco de Quito - Quito - Andes
   anti_air = 2 
 } 
 
 #.#.# Egypt 
 
province = { id = 903   # Cairo - Delta - Egypt
   anti_air = 2 
 } 
 
province = { id = 907   # Alexandria - Delta - Egypt
   anti_air = 5 
 } 
 
province = { id = 901   # Port Said - Suez Channel Area - Egypt
   anti_air = 2 
 } 
 
 #.#.# Estonia 
 
province = { id = 194   # Tallinn - Estonia - Baltic States
   anti_air = 2 
 } 
 
 #.#.# Finland 

province = { id = 137   # Oulu - Central Finland - Finland
   anti_air = 1 
 } 
 
province = { id = 141   # Turku - Oesterbotten - Finland
   coastalfort = 2 
   anti_air = 2 
 } 
 
province = { id = 142   # Helsinki - South Finland - Finland
   coastalfort = 2 
   anti_air = 4 
 } 
 
province = { id = 103   # Maarianhamina - Oesterbotten - Finland
   coastalfort = 2 
 } 
 
province = { id = 2305   # Hanko
   coastalfort = 2 
   anti_air = 1 
} 
 
province = { id = 2630   # Kirkknonummi
   coastalfort = 2 
} 

province = { id = 139   # Tampere - South Finland - Finland
   anti_air = 2 
 } 
 
province = { id = 3327   # Mikkeli - South Finland - Finland
   anti_air = 2 
 } 
 
province = { id = 148   # Lahti - South Finland - Finland
   anti_air = 1 
 } 
 
province = { id = 145   # Viipuri - Karelia - Finland
   landfort = 3 
   anti_air = 1  
   coastalfort = 1
 } 
 
province = { id = 146   # Sortavala - Karelia - Finland
   anti_air = 2 
   landfort = 1 
   coastalfort = 1
 }  
 
province = { id = 3336   # Kainau - Finland
   landfort = 1  
 } 
 
 
#.#.# France 
 
province = { id = 32   # Brest - Brittany - France
   anti_air = 4 
 } 
 
province = { id = 3157   # Saint-Nazaire - Brittany - France
   anti_air = 2 
 } 
 
province = { id = 38   # Cherbourg - Normandy - France
   anti_air = 3 
 } 
 
province = { id = 39   # Caen - Normandy - France
   anti_air = 1 
 } 
 
province = { id = 44   # Lille - Pas de Calais - France
   anti_air = 1 
 } 
 
province = { id = 56   # Paris - Paris - France
   anti_air = 5 
 } 

province = { id = 323   # La Rochelle - Aquitaine - France
   anti_air = 4 
 } 
 
province = { id = 320   # Chateauroux - Limousin_Auvergne - France
   anti_air = 1 
 } 

province = { id = 365   # Toulon - Alpes_Provence - France
   anti_air = 3 
 } 
 
province = { id = 366   # Nice - Alpes_Provence - France
   landfort = 5 
 } 
 
province = { id = 364   # Marseille - Alpes_Provence - France
   anti_air = 2 
 } 
 
province = { id = 527   # Grenoble - Alpes_Provence - France
   landfort = 3 
 } 
 
province = { id = 3137   # Chambery - Alpes_Provence - France
   landfort = 3 
 } 
 
province = { id = 3172   # Longwy - Bourgogne_Champagne - France
   landfort = 2 
 } 

province = { id = 72   # Metz - Lorraine_Alsace - France
   anti_air = 3 
   landfort = 10 
 } 
 
province = { id = 316   # Mulhouse - Lorraine_Alsace - France
   anti_air = 2 
   landfort = 10 
 } 
 
province = { id = 73   # Strasbourg - Lorraine_Alsace - France
   anti_air = 2 
   landfort = 10 
 } 
 
province = { id = 958   # Rabat - Morocco - Morocco
   anti_air = 3 
 } 
 
province = { id = 949   # Algiers - Oran - Algeria
   anti_air = 2 
 } 
 
province = { id = 950   # Oran - Oran - Algeria
   anti_air = 4 
 } 
 
province = { id = 953   # Tlemcen - Oran - Algeria
   anti_air = 2 
 } 
 
province = { id = 939   # Tunis - Tunis - Tunisia
   anti_air = 4 
 } 
 
province = { id = 1037   # Djibouti - Somaliland - Horn of Africa
   anti_air = 1 
 } 
 
province = { id = 993   # Abidjan - Ivory Coast - West Africa
   anti_air = 2 
 } 
 
province = { id = 981   # Dakar - Senegambia - West Africa
   anti_air = 3 
 } 
 
province = { id = 1137   # Toamasina - Madagascar - Madagascar
   anti_air = 1 
 } 

province = { id = 1692   # Nouvelle-Caledonie - South New Hebrides - South Solomon Islands
   anti_air = 1 
 } 
 
 #.#.# Germany 
 
province = { id = 308   # Meseritz - Germany
   landfort = 2 
 } 
 
province = { id = 74   # Saarbrucken - Rhineland - Germany
   anti_air = 2 
   landfort = 1 
 } 
 
province = { id = 7189   # Ludwigshafen am Rhein - Rhineland - Germany
   landfort = 1 
 } 
 
province = { id = 315   # Freiburg - Baden_Wurttemberg - Germany
   landfort = 1 
 } 
  
province = { id = 3250   # Baden-Baden - Baden_Wurttemberg - Germany
   landfort = 1 
 } 
   
province = { id = 1014   # Karlsruhe - Baden_Wurttemberg - Germany
   landfort = 1 
 } 
 
province = { id = 314   # Stuttgart - Baden_Wurttemberg - Germany
   anti_air = 2 
 } 
 
province = { id = 82   # Kassel - Hessen - Germany
   anti_air = 2 
 } 
 
province = { id = 313   # Frankfurt/Main - Hessen - Germany
   anti_air = 3 
 } 

province = { id = 3256   # Oldenburg - Hannover_Magdeburg - Germany
   anti_air = 2 
 } 

province = { id = 87   # Bremen
   anti_air = 1
} 
 
province = { id = 89   # Lubeck - Holstein_Mecklemburg - Germany
   anti_air = 1 
 } 
 
province = { id = 90   # Kiel - Holstein_Mecklemburg - Germany
   anti_air = 1  
 } 
 
province = { id = 296   # Rostock - Holstein_Mecklemburg - Germany
   anti_air = 2 
 } 
 
province = { id = 88   # Hamburg - Holstein_Mecklemburg - Germany
   anti_air = 2 
 } 
 
province = { id = 1779   # Stolp - Brandenburg - Germany
   landfort = 1 
 } 

province = { id = 302   # Stettin - Brandenburg - Germany
   landfort = 1 
 } 

province = { id = 1810   # Schneidemuehl - Brandenburg - Germany
   landfort = 1 
 } 

province = { id = 300   # West-Berlin - Brandenburg - Germany
   anti_air = 2 
 } 
 
 province = { id = 7266   # Ost-Berlin - Brandenburg - Germany
   anti_air = 2 
 } 
 
province = { id = 473   # Breslau - Silesia - Germany
   anti_air = 2 
 } 
 
province = { id = 3243   # Magdeburg - Sachsen - Germany
   anti_air = 2 
 } 
 
province = { id = 310   # Leipzig - Sachsen - Germany
   anti_air = 1 
 } 
 
province = { id = 312   # Nuremberg - Bavaria - Germany
   anti_air = 1 
 } 
 
province = { id = 376   # Munich - Bavaria - Germany
   anti_air = 2 
 } 
 
province = { id = 510   # Koenigsberg - East Prussia - Germany
   anti_air = 4 
   landfort = 4 
 } 
 
#.#.# Greece 
 
province = { id = 412   # Thessaloniki - Thrace - Balkan
   landfort = 5 
   anti_air = 2 
 } 
 
province = { id = 392   # Ioannina - Thrace - Balkan
   landfort = 5 
 } 
 
province = { id = 2319   # Kastoria - Thrace - Balkan
   landfort = 5 
 } 
 
province = { id = 7319   # Kozani - Thrace - Balkan
   landfort = 5 
 } 
 
province = { id = 401   # Athens - Attica - Balkan
   anti_air = 1 
 } 
 
province = { id = 396   # Irakleio - Greek Island - Balkan
   anti_air = 1 
 } 
 
#.#.# Guatemala 
 
province = { id = 757   # Ciudad de Guatemala - Central Rainforests - Central America
   anti_air = 1 
 } 
 
#.#.# Haiti 
 
province = { id = 892   # Port-au-Prince - Hispaniola - Caribbean
   anti_air = 1 
 } 
 
#.#.# Holland 
 
province = { id = 49   # Eindhoven - Netherlands - Benelux
   anti_air = 2 
 } 
 
province = { id = 47   # Amsterdam - Netherlands - Benelux
   anti_air = 2 
 } 
 
province = { id = 46   # Rotterdam - Netherlands - Benelux
   anti_air = 2 
 } 

province = { id = 1359   # Bengkulu - Sumatra - Indonesia
   anti_air = 2 
 } 
 
province = { id = 1613   # Batavia - West Java - Indonesia
   anti_air = 2 
 } 
 
province = { id = 1632   # Soerabaja - East Java - Indonesia
   anti_air = 2 
 } 
 
province = { id = 1653   # Manado - Celebes - Indonesia
   anti_air = 2 
 } 
 
 #.#.# Honduras 
 
province = { id = 760   # Tegucigalpa - Nicaragua - Central America
   anti_air = 1 
 } 
 
 #.#.# Hungary 
 
province = { id = 457   # Budapest - Eastern Hungary - Hungary
   anti_air = 2 
 } 
 
 #.#.# Iraq 
 
province = { id = 1823   # Basrah - Iraq - Middle East
   anti_air = 2 
 } 
 
province = { id = 1864   # El Hillah - Iraq - Middle East
   anti_air = 1 
 } 
 
province = { id = 1866   # Kut - Iraq - Middle East
   anti_air = 2 
 } 
 
 #.#.# Ireland 
 
province = { id = 30   # Dublin - Eire - Ireland
   anti_air = 2 
 } 
 
 #.#.# Italy 
 
province = { id = 398   # Kalymnos - Greek Island - Balkan
   anti_air = 1 
   coastalfort = 4 
 } 
 
province = 
 { id = 399   # Rodos - Greek Island - Balkan
   anti_air = 1 
 } 
 
province = { id = 368   # Genoa - North Italy - Italy
   landfort = 4 
   anti_air = 3 
 } 
 
province = { id = 531   # Turin - North Italy - Italy
   landfort = 4 
   anti_air = 1 
 } 
 
province = { id = 378   # Venice - North Italy - Italy
   coastalfort = 2 
   anti_air = 2 
 } 

province = { id = 2326   # Capodistria - North Italy - Italy
   landfort = 2 
 } 
 
province = 
 { id = 666   # Trieste - North Italy - Italy
   anti_air = 2 
 } 
 
province = { id = 3357   # Pola - North Italy - Italy
   anti_air = 1 
   landfort = 2 
 } 
 
province = { id = 370   # Milan - North Italy - Italy
   anti_air = 3 
 } 
 
province = { id = 369   # Parma - Appennine Ridge - Italy
   anti_air = 1 
 } 
 
 
province = { id = 512   # Bologna - Appennine Ridge - Italy
   anti_air = 1 
 } 
 
province = { id = 514   # Ancona - Appennine Ridge - Italy
   anti_air = 1 
   coastalfort = 1 
 } 
 
province = { id = 515   # Rome - Central Italy - Italy
   anti_air = 3 
 } 
 
province = { id = 521   # Naples - South Italy - Italy
   anti_air = 1 
 } 
 
province = { id = 523   # Taranto - South Italy - Italy
   anti_air = 3 
   #coastalfort = 3 
 } 
 
province = { id = 2621   # Bari - South Italy - Italy
   anti_air = 1 
 } 
 
province = { id = 525   # Palermo - Sicilian Gap - Italy
   anti_air = 2 
 } 
 
province = { id = 3057   # Siracuse - Sicilian Gap - Italy
   anti_air = 2 
 } 
 
province = { id = 534   # Cagliari - Ligurian Islands - Italy
   anti_air = 2 
   coastalfort = 1 
 } 
 
province = { id = 545   # Sassari - Ligurian Islands - Italy
   anti_air = 1 
} 
 
province = 
 { id = 932   # Tripoli - Tripoli - Libya
   anti_air = 1 
 } 
 
province = 
 { id = 924   # Benghazi - Bengazi - Libya
   anti_air = 1 
 } 
 
province = 
 { id = 920   # Tobruk - Tobruk - Libya
   anti_air = 2 
   landfort = 3 
   coastalfort = 2 
 } 
 
province = 
 { id = 1033   # Massawa - Red Sea Coast - Ethiopia
   anti_air = 1 
 
 } 
 
province = 
 { id = 1038   # Assab - Red Sea Coast - Ethiopia
   anti_air = 1 
 } 
 
province = { id = 1056   # Mogadishu - Somalia - Horn of Africa
   anti_air = 1 
 } 

#.#.# Japan 
 
province = { id = 3090   # Lushunkou - Liaoning - China
   anti_air = 4 
 } 
 
province = { id = 1391   # Ganggye - Pyongyang - Korea
   anti_air = 2 
 } 
 
province = { id = 1199   # Seoul - Seoul - Korea
   anti_air = 3 
 } 
 
province = { id = 1197   # Busan - Seoul - Korea
   anti_air = 2 
 } 

province = { id = 1182   # Yokohama - Tohoku - Japan
   anti_air = 2 
 } 
 
province = { id = 1181   # Niigata - Tohoku - Japan
   anti_air = 2 
 } 
 
province = { id = 1184   # Tokyo - Tohoku - Japan
   anti_air = 2 
 } 
 
province = { id = 1187   # Osaka - Honshu - Japan
   anti_air = 2 
 } 
 
province = { id = 1188   # Hiroshima - Honshu - Japan
   anti_air = 4 
 } 
 
province = { id = 1185   # Nagoya - Honshu - Japan
   anti_air = 2 
 } 
 
province = { id = 1186   # Kyoto - Honshu - Japan
   anti_air = 2  
 } 
 
province = { id = 1189   # Matsuyama - Kyushu_Shikoku - Japan
   anti_air = 2 
 } 
 
province = { id = 1190   # Fukuoka - Kyushu_Shikoku - Japan
   anti_air = 2 
 } 
 
province = { id = 1193   # Naha - Ryukyusland - Japan
   anti_air = 2 
 } 

province = { id = 1784   # Ogasawara - Bonin - Asian Pacific
   anti_air = 2 
 } 
 
province = { id = 1620   # Truk - Carolinese - Asian Pacific
   anti_air = 5 
 } 
 
province = { id = 1619   # Woleai - Carolinese - Asian Pacific
   anti_air = 3 
 } 

province = { id = 1621   # Peleliu
   anti_air = 1 
 } 

province = 
 { id = 1601   # Eniwetok - Marshalls - Asian Pacific
   anti_air = 5 
 } 
 
province = { id = 1602   # Kwajalein - Marshalls - Asian Pacific
   anti_air = 5 
 } 
 
province = { id = 1603   # Majuro
   anti_air = 1 
 } 

province = { id = 1627   # Saipan
   anti_air = 5 
 } 
 
province = { id = 7194   # Pagan - North Marianes - Asian Pacific
   anti_air = 3 
 } 
 
#.#.# Latvia 
 
province = { id = 197   # Riga - Latvia - Baltic States
   anti_air = 1 
 } 
 
#.#.# Liberia 
 
province = { id = 992   # Monrovia - Guinean Coast - West Africa
   anti_air = 1 
 } 
 
 #Lithuania 
 
province = { id = 2606   # Klaipeda - Lithuania - Baltic States
   anti_air = 1 
 } 

 #.#.# Manchuko 
 
province = { id = 1379   # Harbin - Heilongjiang - China
   anti_air = 2 
 } 
 
 #.#.# Syria 
 
province = { id = 1794   # Beirut - Lebanon_Syria - Middle East
   anti_air = 2 
 } 
 
#.#.# Mexico 
 
province = { id = 747   # Leon de los Aldama - Mexico City - Mexico
   anti_air = 1 
 } 
 
province = { id = 751   # Acapulco de Juarez - Mexico City - Mexico
   anti_air = 1 
 } 
 
province = { id = 752   # Mexico City - Mexico City - Mexico
   anti_air = 2 
 } 
 
province = { id = 754   # Oaxaca de Juarez - Vera Cruz - Mexico
   anti_air = 2 
 } 
 
 #.#.# NewZealand 
 
province = { id = 1871   # Wellington - New Zealand - Australia
   anti_air = 2 
 } 

#.#.# Norway 
 
province = { id = 107   # Oslo - Southern Norway - Norway
   anti_air = 2 
   coastalfort = 3 
 } 
 
province = { id = 3294   # Alesund - Southcentral Norway - Norway
   anti_air = 2 
   coastalfort = 3 
 } 
 
province = { id = 118   # Trondheim - Central Norway - Norway
   coastalfort = 2 
 } 
 
province = { id = 2276   # Narvik - Central Norway - Norway
   anti_air = 1 
 } 
 
#.#.# Oman 
 
province = { id = 1819   # Masqat - Yemenite Mountains - Middle East
   anti_air = 2 
 } 
 
#.#.# Panama 
 
province = { id = 888   # Ciudad de Panama - Panaman Ridge - Central America
   anti_air = 2 
 } 
 
#.#.# Paraquay 
 
province = { id = 846   # Nuestra Senora de la Asuncion - Asuncion - Gran Chaco
   anti_air = 1 
 } 
 
#.#.# Persia 
 
province = { id = 1497   # Gameroon - East Persia - Persia
   anti_air = 2 
 } 
 
#.#.# Peru 
 
province = { id = 830   # Lima - Lima - Andes
   anti_air = 2 
 } 
 
#.#.# Philipines 
 
province = { id = 1737   # Manila - Luzon - Philippines
   anti_air = 2 
 } 
 
province = { id = 1739   # Angeles - Luzon - Philippines
   anti_air = 4 
 } 
 
 #.#.# Poland 
 
province = 
 { id = 7050   # Modlin
   landfort = 2 
 } 
 
province = { id = 307   # Torun - Poznan - Poland
   anti_air = 2 
 } 
 
province = 
 { id = 483   # Poznan - Poznan - Poland
   anti_air = 4 
 } 
 
province = { id = 208   # Bydgoszcz - Poznan - Poland
   anti_air = 1 
 } 
 
province = { id = 306   # Gdynia - Poznan - Poland
   anti_air = 2 
 } 
 
province = { id = 480   # Czestochowa - Poznan - Poland
   anti_air = 3 
 } 

province = { id = 305   # Plock - Warsaw - Poland
   anti_air = 1 
 } 
 
province = { id = 485   # Warsaw - Warsaw - Poland
   anti_air = 2 
 } 
 
province = { id = 479   # Krakow - Krakow - Poland
   anti_air = 2 
 } 
 
province = { id = 509   # Suwalki - Polotsk - Poland
   anti_air = 1 
 } 
 
#.#.# Portugal 
 
province = { id = 336   # Lisbon - Portugal - Portugal
   anti_air = 4 
 } 
 
province = { id = 335   # Porto - Portugal - Portugal
   anti_air = 1 
 } 
 
province = { id = 1090   # Sao Tome - Cameroonian Jungle - Central Africa
   anti_air = 2 
 } 
 
province = { id = 983   # Bissau - Guinean Coast - West Africa
   anti_air = 2 
 } 
 
province = { id = 1867   # The Azores - The Azores - Portugal
   anti_air = 2 
 } 

#.#.# Romania 
 
province = { id = 423   # Bazargic - South Romania - Romania
   anti_air = 2 
 } 
 
province = { id = 431   # Ploesti - South Romania - Romania
   anti_air = 3 
 } 
 
province = { id = 424   # Bucharest - South Romania - Romania
   anti_air = 2 
 } 

 #.#.# Saudi Arabia 
 
province = { id = 1804   # Medina - Hedjaz - Middle East
   anti_air = 2 
 } 
 
#.#.# Siam 
 
province = { id = 1345   # Nakhon Sawan - Siam - Indochine
   anti_air = 2 
 } 
 
#.#.# South Africa 
 
province = { id = 1119   # Pretoria - Transvaal_Natal - South Africa
   anti_air = 3 
 } 
 
province = { id = 1120   # Johannesburg - Transvaal_Natal - South Africa
   anti_air = 3 
 } 
 
province = { id = 1116   # Cape Town - Cape - South Africa
   anti_air = 4 
 } 
 
province = { id = 1117   # Port Elizabeth - Cape - South Africa
   anti_air = 1 
 } 
 
province = { id = 2643   # Walvis bay - Namibia - Southwest Africa
   anti_air = 2 
 } 
 
#.#.# Soviet Union 
 
province = { id = 133   # Murmansk - Kola - White Sea Tundra
   anti_air = 4 
 } 
 
province = { id = 154   # Arkhangelsk - Arkhangelsk - Northern Russia
   anti_air = 4 
 } 
 
province = { id = 7003   # Kirjasali
   landfort = 2 
} 

province = { id = 7003   # Kirjasali
   landfort = 1 
} 
 
province = { id = 188   # Kingisepp - Novgorod - Western Russia
   landfort = 1 
} 
 
province = { id = 192   # Gdov - Novgorod - Western Russia
   landfort = 1 
 } 
  
province = { id = 7002   # Luga - Western Russia
   landfort = 1 
 }   
 
province = { id = 3400   # Lepiel - Western Russia
   landfort = 2 
 } 
  
province = { id = 7065   # Starobin - Western Russia
   landfort = 2
 } 
   
province = { id = 3401   # Pietrykau - Western Russia
   landfort = 2 
 } 
   
province = { id = 3406   # Ovruc - Western Russia
   landfort = 2 
 } 
    
province = { id = 3455   # Nevel - Western Russia
   landfort = 1 
 } 
  
province = { id = 187   # Leningrad - Leningrad - Russia
   anti_air = 6 
   landfort = 5 
   coastalfort = 5 
 } 
 
province = { id = 191   # Staraya Russa - Pskov - Western Russia
   anti_air = 1 
 } 

province = { id = 1564   # Opochka - Pskov - Western Russia
   landfort = 1 
 } 
 
province = { id = 201   # Pskov - Pskov - Western Russia
   landfort = 2 
 } 
 
province = { id = 175   # Moscow - Moscow - Russia
   landfort = 5 
   anti_air = 4 
 } 
 
province = { id = 277   # Klintsy - Smolensk - Western Russia
   anti_air = 2 
 } 
 
province = { id = 219   # Smolensk - Smolensk - Western Russia
   anti_air = 3 
 } 
 
province = { id = 217   # Vitebsk - Minsk - Belarus
   anti_air = 2 
 } 
 
province = { id = 1153   # Borisov - Minsk - Belarus
   landfort = 2 
} 
 
province = { id = 1874   # Polotsk - Minsk - Belarus
   landfort = 2 
 } 
 
province = { id = 225   # Mozyr - Mozyr - Belarus
   landfort = 2 
 } 
 
province = { id = 503   # Brest Fort - Belarus
   landfort = 3 
 } 
 
province = { id = 272   # Slutsk - Rogachev - Belarus
   landfort = 1 
 } 
province = { id = 273   # Luban - Mozyr - Belarus
   landfort = 2 
 } 
 
province = { id = 212   # Minsk - Minsk - Belarus
   landfort = 2 
 } 
 
province = { id = 267   # Proskurov - Transnistria - Ukraine
   landfort = 1 
 } 
 
province = { id = 226   # Novograd-Volynsky - Transnistria - Ukraine
   landfort = 2 
} 
 
province = { id = 238   # Kiev - Kiev - Ukraine
   anti_air = 3 
   landfort = 2 
 } 
 
province = { id = 161   # Kamenets-Podolsky - Transnistria - Ukraine
   landfort = 1 
 } 
 
province = { id = 231   # Mogilev-Podolsky
   landfort = 1 
 } 
 
 province = { id = 1571   # Tiraspol
   landfort = 1 
 } 

province = { id = 233   # Odessa - Odessa - Ukraine
   anti_air = 3 
   landfort = 2 
 } 
 
province = { id = 228   # Vinnitsa
   landfort = 2 
 } 
 
province = { id = 246   # Poltava - Poltava - Ukraine
   anti_air = 2 
 } 
 
province = { id = 258   # Mariupol - Dnepropretovsk - Ukraine
   anti_air = 2 
 } 
 
province = { id = 248   # Kharkov - Kharkov - Ukraine
   anti_air = 1 
 } 

province = { id = 253   # Sevastopol - Krim - Ukraine
   anti_air = 6 
   landfort = 3 
   coastalfort = 5 
 } 
 
province = { id = 263   # Rossosh - Belgorod - Southern Russia
   anti_air = 1 
 } 
 
province = { id = 163   # Stalingrad - Stalingrad - Southern Russia
   landfort = 5 
   anti_air = 3 
 } 
 
province = { id = 1838   # Astrakhan - Astrakhan - Kaukasus
   anti_air = 2 
 } 
 
province = { id = 1848   # Kutaisi - Georgien - Kaukasus
   anti_air = 2 
 } 

province = { id = 1525   # Blagoveshchensk - Amur - Far East Siberia
   anti_air = 2 
 } 
 
province = { id = 1907   # Baku
   anti_air = 1
   air_base = { size = 2 current_size = 2 }
 } 

province = { id = 1372   # Vladivostok - Primorski - Far East Siberia
   anti_air = 7 
   landfort = 1 
   coastalfort = 3 
 } 
 
province = { id = 1175   # Lesozavodsk - Primorski - Far East Siberia
   anti_air = 2 
 } 
 
province = { id = 1410   # Komsomolsk
   anti_air = 2 
   naval_base = { size = 2 current_size = 2 }
 } 

#.#.# Spain 
 
province = { id = 357   # Tarragona - Catalonia - Spain
   anti_air = 2 
 } 
 
province = { id = 334   # Coruna - Cantabric Chain - Spain
   anti_air = 2 
 } 
 
province = { id = 341   # Madrid - Central Spain - Spain
   anti_air = 3 
 } 
 
province = { id = 2244 #Pamplona - Spain
   anti_air = 2 
} 

province = { id = 333 #Burgos - Spain
   anti_air = 1 
} 

province = { id = 1532 #Leon - Spain
   anti_air = 1 
} 

province = { id = 330 #Zaragosa - Spain
   anti_air = 1 
} 
 
province = { id = 354   # Valencia - Levant - Spain
   anti_air = 2 
 } 
 
province = { id = 347   # Sevilla - West Andalucia - Spain
   anti_air = 2 
 } 
 
province = { id = 535   # Palma de Mallorca - Baleares - Spain
   anti_air = 2 
 } 
 
province = { id = 972   # Villa Cisneros - Rio de Oro - Sahara
   anti_air = 2 
 } 
 
#.#.# Sweden 

province = { id = 101   # Stockholm - Oestra Svealand - Sweden
   anti_air = 5 
 } 
 
#.#.# Switzerland 
 
province = { id = 533   # Zurich - Switzerland - Switzerland
   landfort = 5 
   anti_air = 3 
} 
 
province = { id = 372   # Lugano - Switzerland - Switzerland
   landfort = 4 
   anti_air = 3 
 } 
 
province = { id = 530   # Geneva - Switzerland - Switzerland
   landfort = 5 
   anti_air = 3 
} 
 
province ={ id = 532   # Bern - Switzerland - Switzerland
   anti_air = 5 
   landfort = 5 
 } 
  
province ={ id = 6524   # Neuchatel - Switzerland - Switzerland
   anti_air = 5 
   landfort = 3 
 } 
  
province ={ id = 3216   # Basel - Switzerland - Switzerland
   anti_air = 5 
   landfort = 5 
 } 
  
province ={ id = 3215   # Chur - Switzerland - Switzerland
   anti_air = 5 
   landfort = 3 
 } 
  
province ={ id = 3214   # Thun - Switzerland - Switzerland
   anti_air = 5 
   landfort = 3 
 } 
  
province ={ id = 3213   # Lausanne - Switzerland - Switzerland
   anti_air = 5 
   landfort = 3 
 } 

#.#.# Turkey 
 
province = { id = 448   # Ankara - Central Turkey - Anatolia
   anti_air = 4 
 } 
 
province = { id = 439   # Izmit - Bosporus - Anatolia
   anti_air = 4 
 } 

#.#.# United Kingdom 
 
province = { id = 5   # Kirkwall - North Scotland - Scotland
   anti_air = 4 
 } 
 
province = { id = 9   # Dumfries - South Scotland - Scotland
   anti_air = 2 
 } 

province = { id = 13   # Sheffield - North England - England
   anti_air = 2 
 } 

province = { id = 3031   # Exeter - West England - England
   anti_air = 6 
 } 
 
province = { id = 23   # Plymouth - West England - England
   anti_air = 2 
   coastalfort = 1 
 } 
 
province = { id = 17   # Norwich - East England - England
   anti_air = 4 
 } 
 
province = { id = 20   # Dover - East England - England
   anti_air = 5 
   coastalfort = 3 
 } 
 
province = { id = 21   # Portsmouth - East England - England
   anti_air = 6 
 }
 
province = { id = 16   # Oxford - East England - England
   anti_air = 2 
 } 

province = { id = 348   # Gibraltar - West Andalucia - Spain
   anti_air = 4 
   landfort = 3 
 } 
 
province = { id = 444   # Nicosia - Anatolian South Coast - Anatolia
   anti_air = 1 
 } 
 
province = { id = 31   # Malta - Sicilian Gap - Italy
   anti_air = 2 
   coastalfort = 1 
 } 
 
province = { id = 1066   # Khartoum - Upper Nile Valley - Sudan
   anti_air = 1 
 } 
 
province = { id = 1061   # Mombasa - Kenya - East Africa
   anti_air = 1 
 } 
 
province = { id = 900   # Suez - Suez Channel Area - Egypt
   anti_air = 2 
 } 
 
province = { id = 1008   # Lagos - South Nigeria - West Africa
   anti_air = 1 
 } 
 
province = { id = 1002   # Accra - Gold Coast - West Africa
   anti_air = 1 
 } 
 
province = { id = 988   # Freetown - Guinean Coast - West Africa
   anti_air = 1 
 } 
 
province = { id = 1798   # Tel Aviv - Palestine - Middle East
   anti_air = 1 
   province_revoltrisk = 5 } 
 
province = { id = 1799   # Gaza - Palestine - Middle East
   province_revoltrisk = 5 } 
   
province = { id = 7285   # Eilat - Palestine - Middle East
   province_revoltrisk = 5 } 
   
province = { id = 404   # Haifa - Palestine - Middle East
   province_revoltrisk = 5 } 
   
province = { id = 1797   # Jerusalem - Palestine - Middle East
   anti_air = 1 
   province_revoltrisk = 5 } 
   
province = { id = 1881   # an-Nasira - Palestine - Middle East
   province_revoltrisk = 5 } 
   
province = { id = 1796   # Amman - Transjordan - Middle East
   province_revoltrisk = 2 } 
   
province = { id = 1803   # Madaba - Transjordan - Middle East
   province_revoltrisk = 2 } 
   
province = { id = 407   # Azraq - Transjordan - Middle East
   province_revoltrisk = 2 } 
   
province = { id = 1802   # Ma'an - Transjordan - Middle East
   province_revoltrisk = 2 } 
   
province = { id = 4166   # al-Aqaba - Transjordan - Middle East
   province_revoltrisk = 2 } 
 
province = { id = 1813   # Aden - Yemenite Mountains - Middle East
   anti_air = 1 
 } 
 
province = { id = 1315   # Hong Kong - Guangdong - China
   anti_air = 4 
   coastalfort = 1 
 } 
 
province = { id = 1353   # Singapore - Malacka - Indochine
   anti_air = 2 
   coastalfort = 1 
 } 
 
province = { id = 1516   # Maha Nuvara - Ceylon - India
   anti_air = 1 
 } 
 
province = { id = 1517   # Colombo - Ceylon - India
   anti_air = 2 
   coastalfort = 3 
 } 

province = { id = 1817   # Male - Diego Garcia Island - Diego Garcia Island
   anti_air = 2 
 } 
 
province = { id = 1644   # Kuching - North Borneo - Indonesia
   anti_air = 1 
 } 

province = { id = 652   # Nassau - Bahamas Islands - Caribbean
   anti_air = 1 
 } 
 
province = { id = 538   # Hamilton - Bermuda - Bermuda - Caribbean
   anti_air = 1 
 } 
 
province = { id = 873   # Georgetown - Guayana - Grand Colombia
   anti_air = 1 
 } 
 
province = { id = 866   # Stanley - The Falklands - Patagonia
   anti_air = 2 
 } 
 
province = { id = 576   # St. John's - New Foundland - Eastern Canada
   anti_air = 2 
 } 
 
#.#.# Urugay 
 
province = { id = 849   # Montevideo - La Plata - Rio de la Plata
   anti_air = 1 
 } 
 
#.#.# Usa 
 
province = { id = 889   # Balboa - Panaman Ridge - Central America
   anti_air = 3 
 } 
 
province = { id = 1786   # Wake - Marcus_Wake - Asian Pacific
   anti_air = 3 
 } 
 
province = { id = 1624   # Guam - North Marianes - Asian Pacific
   anti_air = 3 
 } 

province = { id = 7242   # Pearl Harbor - Hawaii - American Pacific
   anti_air = 3 
 } 

province = { id = 662   # Midway
   anti_air = 1 
 } 

province = { id = 894   # Guantanamo Bay Naval Base - Cuba - Caribbean
   anti_air = 1 
 } 
 
province = { id = 595   # Concord - New Hampshire - Northeast US
   anti_air = 1 
 } 
 
province = { id = 600   # Boston - Massachussets - Northeast US
   anti_air = 3 
 } 
 
province = { id = 592   # Syracuse - New York - Northeast US
   anti_air = 1 
 } 
 
province = { id = 602   # New York - New York - Northeast US
   anti_air = 4 
 } 

province = { id = 608   # Philadelphia - Pennsylvania - Northeast US
   anti_air = 2 
 } 
 
province = { id = 614   # Pittsburgh - Pennsylvania - Northeast US
   anti_air = 1 
 } 

province = { id = 606   # Washington - Maryland_Delaware - Northeast US
   anti_air = 4 
 } 
 
province = { id = 632   # Norfolk - Virginia - Northeast US
   anti_air = 4 
 } 
 
province = { id = 640   # Lexington - Kentucky - Northeast US
   anti_air = 1 
 } 
 
province = { id = 620   # Chicago - Illinois - Midwest US
   anti_air = 3 
 } 
 
province = { id = 689   # Saint Louis - Missouri - Midwest US
   anti_air = 1 
 } 
 
province = { id = 621   # Milwaukee - Wisconsin - Midwest US
   anti_air = 1 
 } 
 
province = { id = 616   # Detroit - Michigan - Midwest US
   anti_air = 1 
 } 
 
province = { id = 693   # Rochester - Minnesota - Midwest US
   anti_air = 1 
 } 
 
province = { id = 698   # Fargo - North Dakota - Midwest US
   anti_air = 1 
 } 
 
province = { id = 789   # Lincoln - Nebraska - Midwest US
   anti_air = 1 
 } 
 
province = { id = 780   # Seattle - Washington - Northwest US
   anti_air = 1 
 } 
 
province = { id = 783   # Portland - Oregon - Northwest US
   anti_air = 1 
 } 
 
province = { id = 761   # San Diego - California - Southwest US
   anti_air = 1 
 } 
 
province = { id = 762   # Los Angeles - California - Southwest US
   anti_air = 3 
 } 
 
province = { id = 764   # Sacramento - California - Southwest US
   anti_air = 1 
 } 
 
province = { id = 765   # San Francisco - California - Southwest US
   anti_air = 3 
 } 
 
province = { id = 733   # Salt Lake City - Utah - Southwest US
   anti_air = 1 
 } 
 
province = { id = 730   # Tucson - Arizona - Southwest US
   anti_air = 1 
 } 
 
province = { id = 725   # Santa Fe - New Mexico - Southcentral US
   anti_air = 1 
 } 
 
province = { id = 707   # Denver - Colorado - Southcentral US
   anti_air = 1 
 } 
 
province = { id = 793   # Oklahoma City - Oklahoma - Southcentral US
   anti_air = 1 
 } 
 
province = { id = 748   # Corpus Christi - Texas - Southcentral US
   anti_air = 1 
 } 
 
province = { id = 716   # Houston - Texas - Southcentral US
   anti_air = 1 
 } 
 
province = { id = 673   # Memphis - Tennessee - Southeast US
   anti_air = 1 
 } 
 
province = { id = 678   # Mobile - Alabama - Southeast US
   anti_air = 1 
 } 
 
province = { id = 648   # Jacksonville - Florida - Southeast US
   anti_air = 1 
 } 
 
province = { id = 651   # Miami - Florida - Southeast US
   anti_air = 1 
 } 
 
province = { id = 670   # Atlanta - Georgia - Southeast US
   anti_air = 1 
 } 
 
province = { id = 644   # Charleston - South Carolina - Southeast US
   anti_air = 1 
 } 
 
province = { id = 637   # Charlotte - North Carolina - Southeast US
   anti_air = 1 
 } 
 
 
province = { id = 549   # Anchorage - Alaska - Alaska
   anti_air = 1 
 } 
 
province = { id = 3558   # Attu Island - Alaskan Archipelago - Alaska
   anti_air = 1 
 } 
 
#.#.# Venezuela 
 
province = { id = 804   # Maracaibo - Maracaibo - Grand Colombia
   anti_air = 2 
 } 
 
province = { id = 870   # Caracas - Caracas - Grand Colombia
   anti_air = 2 
 } 
 
#.#.# Yugoslavia 

province = { id = 453   # Belgrade - Central Serbia - Balkan
   anti_air = 3 
 } 
 
province = { id = 388   # Dubrovnik - Croatia - Balkan
   anti_air = 2 
 } 
 
province = { id = 384   # Split - Croatia - Balkan
   anti_air = 2 
 } 
 
province = { id = 382   # Zagreb - Croatia - Balkan
   anti_air = 2 
 } 
 
 # Depots
 
#Germany
province = { 
	id = 510 #Konigsberg
	supplypool = 10
	oilpool = 10
}
#Belgium
province = { 
	id = 1095 #Boma
	supplypool = 2
}
#France
province = { 
	id = 950 #Oran
	supplypool = 20
}
province = { 
	id = 1137 #Tamatave
	supplypool = 2
}
#Greece
province = { 
	id = 396 #Irakleio
	supplypool = 3
}
#Italy
province = { 
	id = 545 #Sassari
	supplypool = 2
}
province = { 
	id = 920 #Tobruk
	supplypool = 5
	oilpool = 5
}
province = { 
	id = 398 #Kalymnos
	supplypool = 2
	oilpool = 2
}
province = { 
	id = 1033 #Massawa
	supplypool = 20
	oilpool = 5
}
province = { 
	id = 1056 #Mogadishu
	supplypool = 10
	oilpool = 5
}
#Japan
province = { 
	id = 3090 #Port Arthur
	supplypool = 2
	oilpool = 2
}
province = { 
	id = 2527 #Tangshan
	supplypool = 50
	oilpool = 5
}
province = { 
	id = 1323 #Taipei
	supplypool = 2
}
province = { 
	id = 1193 #Southern Okinawa
	supplypool = 2
}
province = { 
	id = 1599 #Motoyama
	supplypool = 2
}
province = { 
	id = 1784 #Ogasawara
	supplypool = 2
}
province = { 
	id = 1620 #Colonia
	supplypool = 2
}
province = { 
	id = 1619 #Woleai
	supplypool = 2
}
province = { 
	id = 1621 #Koror
	supplypool = 2
}
province = { 
	id = 1601 #Eniwetok
	supplypool = 2
}
province = { 
	id = 1602 #Kwajalein
	supplypool = 2
}
province = { 
	id = 1627 #Chalan Piao
	supplypool = 2
}
#Portugal
province = { 
	id = 983 #Bissau
	supplypool = 2
}
#Spain
province = { 
	id = 535 #Palma de Mallorca
	supplypool = 2
}
province = { 
	id = 2331 #Tangiers
	supplypool = 5
}
province = { 
	id = 963 #Canaria
	supplypool = 5
	oilpool = 5
}
province = { 
	id = 972 #Villa Cisneros
	supplypool = 2
}
province = { 
	id = 1091 #Bata
	supplypool = 2
}
#Sweden
province = { 
	id = 96 #Visby
	supplypool = 2
}
#United Kindgom
province = { 
	id = 348 #Gibraltar
	supplypool = 2
}
province = { 
	id = 31 #Malta
	supplypool = 2
}
province = { 
	id = 4712 #Lamu
	supplypool = 2
}
province = { 
	id = 1008 #Lagos
	supplypool = 2
}
province = { 
	id = 1002 #Accra
	supplypool = 2
}
province = { 
	id = 1798 #Tel Aviv
	supplypool = 2
}
province = { 
	id = 1315 #Hong Kong
	supplypool = 2
}
province = { 
	id = 1353 #Singapore
	supplypool = 2
}
province = { 
	id = 1517 #Colombo
	supplypool = 2
}
province = { 
	id = 538 #The Bermudas
	supplypool = 2
}
#USA
province = { 
	id = 889 #Balboa
	supplypool = 5
	oilpool = 5
}
province = { 
	id = 7242 #Pearl Harbour
	supplypool = 5
	oilpool = 5
}

province = { 
	id = 5583
	supplypool = 5500
	oilpool = 10
}

#CHC/U58

#province = { 
#	id = 7993
#	supplypool = 1000
#	oilpool = 10
#}

#province = { 
#	id = 2333
#	supplypool = 1000
#	oilpool = 10
#}

province = { 
	id = 2345
	supplypool = 1000
	oilpool = 10
}



province = { id = 435 #Ismail
   anti_air = 1 
} 

province = { id = 2240 #Kaluga
   anti_air = 1 
} 

#province = { id = 5626
#   landfort = 3 
#} 

province = { id = 1726
   naval_base = { size = 2 current_size = 2 }
} 


#Great Wall
province = { id = 1396
   landfort = 1
} 
province = { id = 2347
   landfort = 1
} 
province = { id = 2349
   landfort = 1
} 
province = { id = 1394
   landfort = 1
} 
province = { id = 2340
   landfort = 1
} 
province = { id = 2345
   landfort = 1
} 
province = { id = 1203
   landfort = 2
} 
province = { id = 2576
   landfort = 2
} 
province = { id = 1206
   landfort = 3
} 
province = { id = 5626
   landfort = 3
} 
province = { id = 1209
   landfort = 3
} 
province = { id = 2518
   landfort = 2
} 
province = { id = 5566
   landfort = 1
} 
province = { id = 5565
   landfort = 3
} 
province = { id = 2520
   landfort = 3
} 
province = { id = 3751
   landfort = 2
} 
province = { id = 1272
   landfort = 2
} 
province = { id = 1271
   landfort = 5 #CHC
} 
province = { id = 5569
   landfort = 5 #CHC
} 
province = { id = 1274
   landfort = 3 
} 
province = { id = 2504
   landfort = 2 
} 
province = { id = 5551
   landfort = 2 
} 
province = { id = 1276
   landfort = 1
} 
province = { id = 1443
   landfort = 1 
} 
province = { id = 5527
   landfort = 1 
} 
province = { id = 5547
   landfort = 1 
} 

#other CHC
province = { id = 1270   # Yan'an - Shaanxi - China
   landfort = 3 
   anti_air = 1
} 
 
province = { id = 5571   # Suide - Shaanxi - China
   landfort = 2 
   anti_air = 1
} 
 
province = { id = 5570   # Fuxian - Shaanxi - China
   landfort = 2 
}
 
province = { id = 5554   # Qingyang - Gansu - China
   landfort = 2 
} 
