#####################
# Country main data #
#####################

country =
{ tag                    = JAP
  belligerence           = 3
  ai					 = "EXP_0_01.ai"
  capital                = 1184
	manpower               = 886
	# Resource Reserves 
	energy                 = 16000 
	metal                  = 8000 
	rare_materials         = 4000 
	oil                    = 4000 
	supplies               = 500 
	money                  = 100 
	transports             = 600 
	escorts                = 100 
  diplomacy =
  { relation = { tag = BEL value = -25 }
    relation = { tag = CGX value = -75 }
    relation = { tag = CHC value = -200 }
    relation = { tag = CHI value = -100 }
    relation = { tag = CHL value = 20 }
    relation = { tag = CSX value = -75 }
    relation = { tag = CXB value = -75 }
    relation = { tag = CYN value = -75 }
    relation = { tag = ENG value = -25 }
    relation = { tag = ETH value = 35 }
    relation = { tag = FIN value = 20 }
    relation = { tag = FRA value = -20 }
    relation = { tag = GER value = 20 }
    relation = { tag = HOL value = -50 }
    relation = { tag = MAN value = 200 access = yes }
	relation = { tag = U87 value = 200 access = yes }
    relation = { tag = PHI value = 1 }
    relation = { tag = SIA value = 75 }
    relation = { tag = SOV value = -10 }
    relation = { tag = USA value = 15 }
  }
  SpyInfo                = { country = "ENG" NumberOfSpies = 2 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 2 }
  SpyInfo                = { country = "SOV" NumberOfSpies = 5 }
  SpyInfo                = { country = "USA" NumberOfSpies = 3 }
  SpyInfo                = { country = "SIK" NumberOfSpies = 1 }
  SpyInfo                = { country = "TAN" NumberOfSpies = 1 }
  SpyInfo                = { country = "GER" NumberOfSpies = 2 }
  SpyInfo                = { country = "CXB" NumberOfSpies = 2 }
  SpyInfo                = { country = "CYN" NumberOfSpies = 2 }
  SpyInfo                = { country = "LUX" NumberOfSpies = 1 }
  SpyInfo                = { country = "POR" NumberOfSpies = 1 }
  SpyInfo                = { country = "ITA" NumberOfSpies = 2 }
  SpyInfo                = { country = "CHI" NumberOfSpies = 4 }
  SpyInfo                = { country = "CGX" NumberOfSpies = 1 }
  SpyInfo                = { country = "PHI" NumberOfSpies = 2 }
  SpyInfo                = { country = "NZL" NumberOfSpies = 1 }
  SpyInfo                = { country = "AST" NumberOfSpies = 2 }
  # Sakhalin
  nationalprovinces      = { 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1784 1599 1192 1193 1785 1174 1176  
1436 1437 1399
3061 3062 3063 3064 3065 3066 3067 3068 3069 3070 
3071 3072 3073 3074 3075 3076 3077 3078 3079 3080 
3081 3082 3083 3084 3085 3086 3087 3088 3089
5653 5655
7938 7939 7940 7941 7962 7963 7964 7965 7966 7967 7968 7969 7970 7971
}
  ownedprovinces    	 = { 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1784 1599 1192 1193 1785 1627 1626 1625 1619
                             1621 1604 1620 1618 1617 1600 1601 1602 1603 1608 1323 1322 1324 1376 1391
                             1392 1200 1201 1199 1198 1197 1196 1195 1194 1393 1202  1176 1174
							 1436 1437 1399 1923 2226 2219 2231 2236  
							 3061	3062	3063	3064	3065	3066	3067	3068	3069	3070	
3071	3072	3073	3074	3075	3076	3077	3078	3079	3080	
3081	3082	3083	3084	3085	3086	3087	3088	3089	3090	
3091	3092	3093	3094	3095	3096	3097	3098	3099	3100	
3101	3102	3103	3104	3105	3106	3107	3108	3109 3133
5653 5654 5655 5652 7938 7939 7940 7941 7962 7963 7964 7965 7966 7967 7968 7969 7970 7971
7034 7194 7195 7196 7197 7198 7199 7200 7201 7202 1237
#Inner Mongolia
#3753 3754 1386 5627 5628 5629 5630 5631 5632 3770 
#East Hebei China
#2576 2527 1203 6916
1203
}

  controlledprovinces    = { 1177 1178 1179 1180 1181 1182 1183 1184 1185 1186 1187 1188 1189 1190 1191 1784 1599 1192 1193 1785 1627 1626 1625 1619
                             1621 1604 1620 1618 1617 1600 1601 1602 1603 1608 1323 1322 1324 1376 1391
                             1392 1200 1201 1199 1198 1197 1196 1195 1194 1393 1202  1176 1174
							 1436 1437 1399 1923 2226 2219 2231 2236  
							 3061	3062	3063	3064	3065	3066	3067	3068	3069	3070	
3071	3072	3073	3074	3075	3076	3077	3078	3079	3080	
3081	3082	3083	3084	3085	3086	3087	3088	3089	3090	
3091	3092	3093	3094	3095	3096	3097	3098	3099	3100	
3101	3102	3103	3104	3105	3106	3107	3108	3109 3133
5653 5654 5655 5652 7938 7939 7940 7941 7962 7963 7964 7965 7966 7967 7968 7969 7970 7971
7034 7194 7195 7196 7197 7198 7199 7200 7201 7202 1237
#Inner Mongolia
#3753 3754 1386 5627 5628 5629 5630 5631 5632 3770 
#East Hebei China
#2576 2527 1203 6916
1203
}
  claimedprovinces 		 = { 
1202 3090 1324 3133 1322 1923 1323
1199 1376 1392 1391 1393 1201 1200 1198 1196 1197 1195 1194 2236 2231 2219 2226 
3091 3092 3093 3094 3095 3096 3097 3098 3099 3100 3101 3102 3103 3104 3105 3106 3107 3108 3109
5654 5652 7034 1523 7943 7942 7944 1237 2529 5640 
1203
#1206 5626
1206
}
  # JAP 1936 techs
  # ######################
	techapps = { 
		# Infantry Division  
		1010 1020 1030 1040 1050 1060 1070 1080 1090
		# Mountain
		1160 1170 1180 1190 1200 1210 1220 1230 1240
		# Cavalry Division  
		13060 13070 13080 1310 1320 1330 1340 1350 1360 1370
		# Marines
		1560 1570 1580 1590
		# Engineers
		1830 1840 1850 1860
		# Interbellum 1930 Supply 
		1910 1920 1930 1940 1950 1960 1970 1980
		# Tanks 
		7600 7610 2620 2010 2630 2640 2646 2650 
		# Armored Car  
		2860 2870 2880 2020
		# Field Artillery 
		2290 2300 2310 2900 2910 2920
		# Early Anti-Tank Artillery 
		#2400
		# Static Anti-Air Artillery 
		2800 2450 21180 21190
		# Anti-Air Artillery Brigade 
		2810 2820 2510
		# Improved Destroyer 
		3010 3020 3030 3040 3050 3060 
		# Basic Light Cruiser 
		3110 3120 3130 3140 3150 3160
		# Improved Heavy Cruiser 
		3210 3220 3230 3240 3250 3260
		# Battlecruiser
		3310 3320 3330 3340
		# Battleship 
		3410 3420 3430 3440 3450 3456 3460 3470
		# Aircraft Carrier
		3510 3520 3530
		# Improved Light carrier 
		12100 12110 12120 12130
		# Submarine
		3610 3620 3630 3640 3650
		# Torpedos & ASW
		3720 3730 3736 3740 3750 3760 3900
		# Troopships
		3810 3820
		# Close Air support
		4400
		# Early Fighter  
		4500 4510 4520 4530 4540 4550 4010 4020
		# Early Bomber 
		4600 4610 4620 4630 4120 4130
		# Basic Naval Bomber 
		4700 4710 4190
		# Transports
		4290
		# Multirole fighter
		4300 4310 4320 4330 4340
		# Seaplanes
		4740 4750 4760 4770 4780
		# Strategic Bomber
		4800 4810 4820
		# CAG 34
		4900 4910 4920
		# Modern Agriculture
		5700 5710 5010
		# Manufacturing
		5810 5820 5050 5830
		# Construction Engineering 
		5800 5080 5090 
		# Basic Oil Refining 
		#5190 
		# Computers & Cryptography
		5310 54010 54020 54030 
		5316 5326 5327
		# Medicine
		5600 5610 5620
		# Exp. Rocket
		5560
		# Great War Land Doctrines (entente)
		6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
		# Land Doctrines (Light Infantry line)
		6390 6400 6420
		# Hospital System 
		14000 14010
		# Naval Doctrines
		# Engagement Theories
		8010 8020 8030 8040 8050 8060 8070 8080
		# Naval Supremacy
		8100 8110 8120 8150
		# Naval Interdiction
		8500 8510 8520 8550 8560 8600 8610
		# Engagement Tactics - Fleet-in-Being column
		8900 8910 8920 8930 8940 8950
		# Subsidiary Carrier Role
		81650
		# Aerial Supremacy column
		81700 81710
		# Scouting Focus column
		81850 81860
		# Amphibious Warfare
		82300 82310
		# Logistic Support
		82500
		# Air Doctrines - ww2 techs
		27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010 9040      
	} 
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 5 
     political_left    = 3 
     freedom           = 7
     free_market       = 1
     professional_army = 6 
     defense_lobby     = 5 
     interventionism   = 10 
  }
	blueprints = { 81730 81740 } 
	inventions = { 3000027 }

	headofstate            = {  type = 9 id = 50001  } 
	headofgovernment       = {  type = 9 id = 50002  } 
	foreignminister        = {  type = 9 id = 50003  } 
	armamentminister       = {  type = 9 id = 50300  } # Takahashi Korekiyo
	ministerofsecurity     = {  type = 9 id = 50005  } 
	ministerofintelligence = {  type = 9 id = 50006  } 
	chiefofstaff           = {  type = 9 id = 50007  } 
	chiefofarmy            = {  type = 9 id = 50008  } 
	chiefofnavy            = {  type = 9 id = 50009  } 
	chiefofair             = {  type = 9 id = 50010  } 
 
	### Japan Land OOB ### 
	
landunit = 
   {  id       = {  type = 13016 id = 380  } 
     name     = "Dai 5 Gun"
     location = 1202 
     Division = 
     {  id       = {  type = 13016 id = 381  } 
       name     = "Dai 4 Dokuritsu shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 4
       extra    = anti_air 
	   brigade_model = 1
      } 
     Division = 
     {  id       = {  type = 13016 id = 382  } 
       name     = "Dai 5 Dokuritsu shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 4
       extra    = anti_air 
	   brigade_model = 1
      } 
     Division = 
     {  id       = {  type = 13016 id = 383  } 
       name     = "Dai 57 Shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 4
      } 
}
	
landunit = 
   {  id       = {  type = 13016 id = 390  }
     name     = "Chôsen 1 Gun"   
	 location = 1201
     Division = 
     {  id       = {  type = 13016 id = 391  } 
       name     = "Dai 1 Chôsen Shubitai"
       strength  = 60 
       type     = garrison 
       model    = 4
	   locked   = yes
      } 
}
landunit = 
   {  id       = {  type = 13016 id = 392  }
     name     = "Chôsen 2 Gun"
	 location = 1199
     Division = 
     {  id       = {  type = 13016 id = 393  } 
       name     = "Dai 2 Chôsen Shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 4
	   locked   = yes
      } 
}
landunit = 
   {  id       = {  type = 13016 id = 394  }
     name     = "Chôsen 3 Gun"
     location = 1391
     Division = 
     {  id       = {  type = 13016 id = 395  } 
       name     = "Dai 6 Dokuritsu shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 4 
	   locked   = yes
      } 
}
landunit = 
   {  id       = {  type = 13016 id = 396  }
     name     = "Chôsen 4 Gun"
     location = 1197
     Division = 
     {  id       = {  type = 13016 id = 397  } 
       name     = "Dai 7 Shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 4
	   locked   = yes
      } 
}
landunit = 
   {  id       = {  type = 13016 id = 398  }
     name     = "Taiwan 1 Gun"
     location = 1923
     Division = 
     {  id       = {  type = 13016 id = 399  } 
       name     = "Dai 1 Taiwan Shubitai"
       strength  = 60 
       type     = garrison 
       model    = 4
	   locked   = yes
      } 
}
landunit = 
   {  id       = {  type = 13016 id = 400  }
     name     = "Taiwan 2 Gun"
     location = 1322
     Division = 
     {  id       = {  type = 13016 id = 401 } 
       name     = "Dai 2 Taiwan Shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 4
	   locked   = yes
      } 
}
landunit = 
   {  id       = {  type = 13016 id = 402  }
     name     = "Taiwan 3 Gun"
     location = 1323
     Division = 
     {  id       = {  type = 13016 id = 403  } 
       name     = "Dai 3 Taiwan Shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 4
       extra    = anti_air 
	   brigade_model = 1
	   locked   = yes
      } 
}
landunit = 
   {  id       = {  type = 13016 id = 404  }
	 name     = "Shanghai Gun"
     location = 1237
     Division = 
     {  id       = {  type = 13016 id = 405  } 
       name     = "Shanghai 8 Shubitai" 
       strength  = 60 
       type     = garrison 
       model    = 4
       extra    = anti_air 
	   brigade_model = 1
	   locked   = yes
      } 
}
landunit = {
	id       = {  type = 13016 id = 406  }
	name     = "Ryojun Kaigunku"
	location = 1193 
	division = {
		id       = { type = 13016 id = 407 }
		name     = "Ryojun Rikusentai"
		strength = 15
		type     = garrison
		model    = 3
		locked   = yes
	}
}
landunit = 
{  id       = {  type = 13016 id = 3060  } 
	 name     = "Dai 4 Gun"
	 location = 3090 
	 Division = 
	 {  id       = {  type = 13016 id = 3061  } 
	   name     = "Dai 2 Dokuritsu shubitai"
	   strength  = 60 
	   type     = garrison 
	   model    = 4
	   extra    = anti_air 
	   brigade_model = 1
	   locked = yes
	  } 
} 

landunit = 
{  id       = {  type = 13016 id = 3062  } 
	 name     = "Dai 6 Gun"
	 location = 1202 
	 Division = 
	 {  id       = {  type = 13016 id = 3063  } 
	   name     = "Dai 3 Dokuritsu shubitai" 
	   strength  = 60 
	   type     = garrison 
	   model    = 4
	   locked = yes
	  } 
}

	landunit = {
		id       = {  type = 13016 id = 3050  } 
		name     = "Shina chutongun" 
		location = 1397 
		division = {
			id       = {  type = 13016 id = 3003  } 
			name     = "Dai 1 Hoheishidan" 
			strength = 100
			type     = infantry 
			model    = 7 
			extra1   = artillery 
			brigade_model1 = 6
			extra2   = engineer
			brigade_model2 = 2
		} 
		division = {
			id       = {  type = 13016 id = 3006  } 
			name     = "Dai 4 Hoheishidan" 
			strength = 100
			type     = infantry 
			model    = 6
			extra1   = cavalry_brigade
			brigade_model1 = 4
			extra2   = engineer 
			brigade_model2 = 2
		} 
		division = {
			id       = {  type = 13016 id = 3007  } 
			name     = "Dai 5 Hoheishidan" 
			strength = 100
			type     = infantry 
			model    = 7 
			extra1   = cavalry_brigade
			brigade_model1 = 6
			extra2   = engineer
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 3008  } 
			name     = "Dai 6 Hoheishidan" 
			strength = 100 
			type     = infantry 
			model    = 7 
			extra1   = cavalry_brigade
			brigade_model1 = 6
			extra2   = engineer
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 3013  } 
			name     = "Dai 11 Hoheishidan" 
			strength = 100
			type     = infantry 
			model    = 7 
			extra1   = cavalry_brigade
			brigade_model1 = 5
			extra2   = engineer 
			brigade_model2 = 3
		}  
		division = {
			id       = {  type = 13016 id = 3014  } 
			name     = "Dai 12 Hoheishidan" 
			strength = 100
			type     = infantry 
			model    = 7 
			extra1   = light_armor_brigade
			brigade_model1 = 2
			extra2   = engineer
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 3015  } 
			name     = "Dai 14 Hoheishidan" 
			strength = 100
			type     = infantry 
			model    = 7 
			extra1   = cavalry_brigade
			brigade_model1 = 4
			extra2   = engineer 
			brigade_model2 = 2
		}  
		division = {
			id       = {  type = 13016 id = 3017  } 
			name     = "Dai 23 Hoheishidan" 
			strength = 50
			type     = infantry 
			model    = 6
			extra1   = light_armor_brigade
			brigade_model1 = 2
			extra2   = engineer
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 40  } 
			name     = "Dai 20 Hoheishidan" 
			strength = 100
			type     = infantry 
			model    = 7 
			extra1   = cavalry_brigade
			brigade_model1 = 5
			extra2   = engineer 
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 44  } 
			name     = "Dai 27 Hoheishidan" 
			strength = 50
			type     = infantry 
			model    = 6
			extra    = engineer
			brigade_model = 3
		} 
	}
	
	landunit = {
		id       = {  type = 13016 id = 3000  } 
		name     = "Kanto-gun" 
		location = 2241 
		division = {
			id       = {  type = 13016 id = 3001  } 
			name     = "Kanto-gun saiko shireibu" 
			strength = 40 
			type     = hq 
			model    = 2 
		} 
		division = {
			id       = {  type = 13016 id = 3004  } 
			name     = "Dai 2 Hoheishidan" 
			strength = 100 
			type     = infantry 
			model    = 7
			extra1   = cavalry_brigade
			brigade_model1 = 5
 			extra2   = engineer
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 3009  } 
			name     = "Dai 7 Hoheishidan" 
			strength = 100 
			type     = infantry 
			model    = 8 
			extra1   = cavalry_brigade
			brigade_model1 = 5
			extra2   = engineer 
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 3010  } 
			name     = "Dai 8 Hoheishidan" 
			strength = 100
			type     = infantry 
			model    = 7 
			extra    = engineer 
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 3011  } 
			name     = "Dai 9 Hoheishidan" 
			strength = 100
			type     = infantry 
			model    = 7 
			extra1   = cavalry_brigade
			brigade_model1 = 5
			extra2   = engineer 
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 3012  } 
			name     = "Dai 10 Hoheishidan" 
			strength = 100
			type     = infantry 
			model    = 7 
			extra1   = cavalry_brigade
			brigade_model1 = 5
			extra2   = engineer 
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 3016  } 
			name     = "Dai 19 Hoheishidan" 
			strength = 100
			type     = infantry 
			model    = 7 
			extra1   = cavalry_brigade
			brigade_model1 = 5
			extra2   = anti_air
			brigade_model2 = 1
		} 
		division = {
			id       = {  type = 13016 id = 3018  } 
			name     = "Dai 24 Hoheishidan" 
			strength = 50
			type     = infantry 
			model    = 6
			extra    = engineer
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 3019  } 
			name     = "Dai 25 Hoheishidan" 
			strength = 50
			type     = infantry 
			model    = 7 
			extra1   = cavalry_brigade
			brigade_model1 = 5
			extra2   = engineer 
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 3020  } 
			name     = "Dai 26 Hoheishidan" 
			strength = 50
			type     = infantry 
			model    = 6
			extra    = engineer
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 3021  } 
			name     = "Dai 28 Hoheishidan" 
			strength = 50
			type     = infantry 
			model    = 7 
			extra1   = cavalry_brigade
			brigade_model1 = 5
			extra2   = engineer 
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 3022  } 
			name     = "Dai 29 Hoheishidan" 
			strength = 50
			type     = infantry 
			model    = 7 
			extra    = light_armor_brigade
			brigade_model = 2
		} 
		 Division = 
		 {  id       = {  type = 13016 id = 3023  } 
		   name     = "Kantô Bôbitai" # Kwantung Defence Command 
		   strength  = 70 
		   type     = garrison 
		   model    = 4
		   extra    = police 
		   brigade_model = 1
		  } 
		division = {
			id       = {  type = 13016 id = 3024  } 
			name     = "IJA Kihei Shudan" 
			strength = 50
			type     = cavalry 
			model    = 8
		}
	} 
	
	landunit = {
		id       = {  type = 13016 id = 5  } 
		name     = "Kihei gurupu" 
		location = 1184 
		division = {
			id       = {  type = 13016 id = 11  } 
			name     = "Dai 1 Kihei ryodan" 
			strength = 70
			type     = cavalry 
			model    = 9 
		} 
		division = {
			id       = {  type = 13016 id = 13  } 
			name     = "Dai 4 Kihei ryodan" 
			strength = 70
			type     = cavalry 
			model    = 9 
			extra    = engineer 
			brigade_model = 3
		} 
	} 

	landunit = {
		id       = {  type = 13016 id = 8  } 
		name     = "Seibu Gun" 
		location = 1184 
		division = {
			id       = {  type = 13016 id = 33  } 
			name     = "Dai 18 Hoheishidan" 
			strength = 100
			type     = infantry 
			model    = 6 
			extra1   = artillery
			brigade_model1 = 6
			extra2   = engineer 
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 34  } 
			name     = "Dai 21 Hoheishidan" 
			strength = 50
			type     = infantry 
			model    = 6 
			extra    = engineer 
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 737  } 
			name     = "Dai 101 Hoheishidan" 
			strength = 50
			type     = infantry 
			model    = 7 
			extra1   = cavalry_brigade
			brigade_model1 = 6
			extra2   = engineer
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 837  } 
			name     = "Dai 106 Hoheishidan" 
			strength = 50
			type     = infantry 
			model    = 7 
			extra1   = cavalry_brigade
			brigade_model1 = 6
			extra2   = engineer
			brigade_model2 = 3
		} 
	}
	landunit = {
	    id       = {  type = 13016 id = 43  }
		name     = "Akita Gun"
		location = 1184 
		division = {
			id       = {  type = 13016 id = 446  }
			name     = "Dai 108 Hoheishidan"
			strength = 50
			type     = infantry
			model    = 6
			extra    = engineer
			brigade_model = 3
		}
		division = {
			id       = {  type = 13016 id = 449  }
			name     = "Dai 114 Hoheishidan"
			strength = 50
			type     = infantry
			model    = 6
			extra    = engineer
			brigade_model = 3
		}
	}
	landunit = {
	    id       = {  type = 13016 id = 447  }
		name     = "Kanazawa Gun"
		location = 1184 
		division = {
			id       = {  type = 13016 id = 448  }
			name     = "Dai 109 Hoheishidan"
			strength = 50
			type     = infantry
			model    = 6
			extra    = engineer
			brigade_model = 3
		}
	}
	landunit = {
		id       = {  type = 13016 id = 21  } 
		name     = "Tobu gun" 
		location = 1184 
		division = {
			id       = {  type = 13016 id = 45  } 
			name     = "Dai 3 Hoheishidan"  
			strength = 100 
			type     = infantry 
			model    = 7 
			extra1   = artillery
			brigade_model1 = 6
			extra2    = anti_air 
			brigade_model = 1
		} 
		division = {
			id       = {  type = 13016 id = 53  } 
			name     = "Dai 13 Hoheishidan" 
			strength = 50
			type     = infantry 
			model    = 6
			extra1   = cavalry_brigade
			brigade_model1 = 5
 			extra2   = engineer
			brigade_model2 = 3
		} 
		division = {
			id       = {  type = 13016 id = 58  } 
			name     = "Dai 15 Hoheishidan" 
			strength = 50
			type     = infantry 
			model    = 6 
			extra1   = cavalry_brigade
			brigade_model1 = 5
 			extra2   = artillery
			brigade_model2 = 6
		} 
		division = {
			id       = {  type = 13016 id = 60  } 
			name     = "Dai 17 'Ranan' Hoheishidan" 
			strength = 50
			type     = infantry 
			model    = 6 
			extra1   = cavalry_brigade
			brigade_model1 = 5
 			extra2   = artillery
			brigade_model2 = 6
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 24  } 
		name     = "Tokyo keibi shireibu"  
		location = 1184 
		division = {
			id       = {  type = 13016 id = 17  } 
			name     = "Daihon'ei" 
			strength  = 40 
			type     = hq 
			model    = 2 
			extra    = anti_air
			brigade_model = 1
		} 
		division = {
			id       = {  type = 13016 id = 29  } 
			name     = "Dai 22 Hoheishidan" 
			strength = 50
			type     = infantry
			model    = 6
			extra    = engineer 
			brigade_model = 3
		} 
		division = {
			id       = {  type = 13016 id = 30  } 
			name     = "Konoe Shidan" 
			strength = 100
			type     = infantry
			model    = 8
			extra1   = artillery 
			brigade_model1 = 6
			extra2   = anti_air 
			brigade_model2 = 1
		} 
		division = {
			id       = {  type = 13016 id = 31  } 
			name     = "Dai 2 Kihei ryodan" 
			strength = 70
			type     = cavalry 
			model    = 9 
			extra    = light_armor_brigade
			brigade_model = 2
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 28  } 
		name     = "Kure Kaigunku"  
		location = 1184 
		division = {
			id       = {  type = 13016 id = 26  } 
			name     = "Kure Rikusentai"
			strength = 10
			type     = marine
			model    = 2
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 32  } 
		name     = "Maizuru Kaigunku" 
		location = 1184 
		division = {
			id       = {  type = 13016 id = 20  } 
			name     = "Maizuru Rikusentai" 
			strength = 10
			type     = marine
			model    = 2
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 35  } 
		name     = "Sasebo Kaigunku" 
		location = 1184 
		division = {
			id       = {  type = 13016 id = 38  } 
			name     = "Sasebo Rikusentai" 
			strength = 10
			type     = marine
			model    = 2 
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 39  } 
		name     = "Yokosuka Kaigunku" 
		location = 1184 
		division = {
			id       = {  type = 13016 id = 27  } 
			name     = "Yokosuka Rikusentai" 
			strength = 10
			type     = marine
			model    = 2
		} 
		division = {
			id       = {  type = 13016 id = 2097  } 
			name     = "Shanghai Rikusentai" 
			strength = 17
			type     = marine
			model    = 2
		} 
	}
	landunit = {
		id       = {  type = 13016 id = 499  }
		name     = "Chuo Gun"
		location = 1184 
		division = {
			id       = {  type = 13016 id = 19  } 
			name     = "Dai 16 Hoheishidan" 
			strength = 65
			type     = infantry 
			model    = 7 
			extra1   = cavalry_brigade
			brigade_model1 = 5
 			extra2   = engineer
			brigade_model2 = 3
		} 
	}
	landunit = {
		id       = {  type = 13016 id = 42  } 
		name     = "Uchi mouko gun" # Inner Mongolian army
		location = 1184 
		division = {
			id       = {  type = 13016 id = 14  } 
			name     = "Uchi mouko gun" 
			strength = 100 
			type     = cavalry 
			model    = 7 
		} 
	} 
	landunit = {
		id       = {  type = 13016 id = 46  } 
		name     = "Tobu kahoku gun" # Chinese collaborationists 
		location = 1184 
		division = {
			id       = {  type = 13016 id = 50  } 
			name     = "Dai 1 Tai" 
			strength = 80
			type     = militia
			model    = 4
		} 
		division = {
			id       = {  type = 13016 id = 51  } 
			name     = "Dai 2 Tai" 
			strength = 80
			type     = militia
			model    = 4
		} 
		division = {
			id       = {  type = 13016 id = 55  } 
			name     = "Dai 3 Tai" 
			strength = 80
			type     = militia
			model    = 4
		} 
		division = {
			id       = {  type = 13016 id = 56  } 
			name     = "Dai 4 Tai" 
			strength = 80
			type     = militia
			model    = 4
		} 
		division = {
			id       = {  type = 13016 id = 72  } 
			name     = "Kunren tai" 
			strength = 40
			type     = militia
			model    = 3
		} 
	} 


	### Japan Navy OOB ### 
  
	# CarDiv 1
	navalunit = { 
		id = { type = 13016 id = 112 } 
		name = "Dai 1 Koku Sentai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 175 } 
			name = "Akagi" 
			type = carrier 
			model = 0 
			extra1 = cag 
			brigade_model1 = 2 
		} 
		division = { 
			id = { type = 13016 id = 177 } 
			name = "Kaga" 
			type = carrier 
			model = 0 
			extra1 = cag 
			brigade_model1 = 2 
		} 
		division = { 
			id = { type = 13016 id = 163 } 
			name = "Myoko" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 164 } 
			name = "Ashigara" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 131 } 
			name = "Tama" 
			type = light_cruiser 
			model = 2 
		} 
		division = { 
			id = { type = 13016 id = 132 } 
			name = "Kitakami" 
			type = light_cruiser 
			model = 2 
		}  
		division = { 
			id = { type = 13016 id = 127 } 
			name = "Tatsuta" 
			type = light_cruiser 
			model = 2 
		} 
		division = { 
			id = { type = 13016 id = 182 } 
			name = "Dai 1 Kuchikusentai" 
			type = destroyer 
			model = 3 
		} 
	}

	# CarDiv 2 (put Soryu and Hiryu in here)
	navalunit = { 
		id = { type = 13016 id = 116 } 
		name = "Dai 2 Koku Sentai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 179 } 
			name = "Ryujo" 
			type  = light_carrier 
			model = 0 
			extra1 = light_cag
			brigade_model1 = 2
		} 
		division = { 
			id = { type = 13016 id = 170 } 
			name = "Mikuma" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 171 } 
			name = "Mogami" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 150 } 
			name = "Yubari" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 151 } 
			name = "Isuzu" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 197 } 
			name = "Dai 2 Kuchikusentai" 
			type = destroyer 
			model = 5 
		} 
		division = { 
			id = { type = 13016 id = 198 } 
			name = "Dai 3 Kuchikusentai" 
			type = destroyer 
			model = 5 
		} 
		division = { 
			id = { type = 13016 id = 201 } 
			name = "Dai 4 Kuchikusentai" 
			type = destroyer 
			model = 5 
		} 
	} 
	
	# BatDiv 1
	navalunit = { 
		id = { type = 13016 id = 120 } 
		name = "Dai 1 Senkan Sentai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 123 } 
			name = "Nagato" 
			type = battleship 
			model = 5 
			extra1 = naval_anti_air_l
			extra2 = naval_fire_controll_l
			extra3 = floatplane
			brigade_model3 = 4
		} 
		division = { 
			id = { type = 13016 id = 173 } 
			name = "Hosho" 
			type = escort_carrier 
			model = 2 
		} 
		division = { 
			id = { type = 13016 id = 166 } 
			name = "Takao" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 167 } 
			name = "Chokai" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 145 } 
			name = "Natori" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 146 } 
			name = "Kinu" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 207 } 
			name = "Dai 5 Kuchikusentai" 
			type = destroyer 
			model = 5
		} 
		division = { 
			id = { type = 13016 id = 215 } 
			name = "Dai 6 Kuchikusentai" 
			type = destroyer 
			model = 5
		} 
		division = { 
			id = { type = 13016 id = 205 } 
			name = "Dai 7 Kuchikusentai" 
			type = destroyer 
			model = 5 
		} 
	} 
	
	# BatDiv 2
	navalunit = { 
		id = { type = 13016 id = 124 } 
		name = "Dai 2 Senkan Sentai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 121 } 
			name = "Ise" 
			type = battleship 
			model = 4 
			extra1 = naval_improved_hull_l
			extra2 = naval_anti_air_l
			extra3 = floatplane
			brigade_model3 = 4
		} 
		division = { 
			id = { type = 13016 id = 122 } 
			name = "Hyuga" 
			type = battleship 
			model = 4 
			extra1 = naval_improved_hull_l
			extra2 = naval_anti_air_l
			extra3 = floatplane
			brigade_model3 = 4
		} 
		division = {
			id = { type = 13016 id = 260 }
			name = "Kamoi"
			type = escort_carrier
			model = 0
		}
		division = { 
			id = { type = 13016 id = 156 } 
			name = "Kako" 
			type = heavy_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 133 } 
			name = "Furutaka" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 130 } 
			name = "Kuma" 
			type = light_cruiser 
			model = 2 
		} 
		division = { 
			id = { type = 13016 id = 161 } 
			name = "Naka" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 214 } 
			name = "Dai 8 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
		division = { 
			id = { type = 13016 id = 206 } 
			name = "Dai 9 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
		division = { 
			id = { type = 13016 id = 196 } 
			name = "Dai 10 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
	} 
	
	# BatDiv 3 (add the other Kongos here)
	navalunit = { 
		id = { type = 13016 id = 126 } 
		name = "Dai 3 Senkan Sentai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 115 } 
			name = "Haruna" 
			type = battlecruiser 
			model = 3 
			extra1 = naval_improved_hull_l
			extra2 = floatplane
			brigade_model2 = 4
		} 
		division = { 
			id = { type = 13016 id = 165 } 
			name = "Atago" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 169 } 
			name = "Maya" 
			type = heavy_cruiser 
			model = 4 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 213 } 
			name = "Dai 11 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
		division = { 
			id = { type = 13016 id = 186 } 
			name = "Dai 12 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
		division = { 
			id = { type = 13016 id = 200 } 
			name = "Dai 13 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
		division = { 
			id = { type = 13016 id = 199 } 
			name = "Dai 14 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
	}
		
	# BatDiv 4 (not sure it really existed, but whatever)
	navalunit = { 
		id = { type = 13016 id = 172 } 
		name = "Dai 4 Senkan Sentai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 118 } 
			name = "Fuso" 
			type = battleship 
			model = 3 
			extra1 = naval_improved_hull_l
			extra2 = floatplane
			brigade_model2 = 4
		} 
		division = { 
			id = { type = 13016 id = 119 } 
			name = "Yamashiro" 
			type = battleship 
			model = 3 
			extra1 = naval_improved_hull_l
			extra2 = floatplane
			brigade_model2 = 4
		} 
		division = {
			id = { type = 13016 id = 261 }
			name = "Notoro"
			type = escort_carrier
			model = 0
		}
		division = { 
			id = { type = 13016 id = 157 } 
			name = "Aoba" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 158 } 
			name = "Kinugasa" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 137 } 
			name = "Nagara" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 140 } 
			name = "Yura" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 194 } 
			name = "Dai 15 Kuchikusentai" 
			type = destroyer 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 181 } 
			name = "Dai 16 Kuchikusentai" 
			type = destroyer 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 183 } 
			name = "Dai 17 Kuchikusentai" 
			type = destroyer 
			model = 1 
		} 
	} 
			
	navalunit = { 
		id = { type = 13016 id = 193 } 
		name = "Dai 5 Sentai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 159 } 
			name = "Nachi" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 160 } 
			name = "Haguro" 
			type = heavy_cruiser 
			model = 3 
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 135 } 
			name = "Kiso" 
			type = light_cruiser 
			model = 2 
		} 
		division = { 
			id = { type = 13016 id = 136 } 
			name = "Oi" 
			type = light_cruiser 
			model = 2 
		} 
		division = { 
			id = { type = 13016 id = 139 } 
			name = "Tenryu" 
			type = light_cruiser 
			model = 2
		} 
		division = { 
			id = { type = 13016 id = 152 } 
			name = "Sendai" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 153 } 
			name = "Abukuma" 
			type = light_cruiser 
			model = 3 
                        extra1 = floatplane
                        brigade_model1 = 3
                        extra2 = naval_torpedoes_s
                        brigade_model2 = 0
		} 
		division = { 
			id = { type = 13016 id = 154 } 
			name = "Jintsu" 
			type = light_cruiser 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 184 } 
			name = "Dai 18 Kuchikusentai" 
			type = destroyer 
			model = 4 
			} 
		division = { 
			id = { type = 13016 id = 185 } 
			name = "Dai 19 Kuchikusentai" 
			type = destroyer 
			model = 4 
		} 
	} 
	
	# Crappy Reserve Fleet 1
	navalunit = { 
		id = { type = 13016 id = 231 } 
		name = "Dai 7 sentai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 148 } 
			name = "Asama" 
			type = heavy_cruiser 
			model = 1 
		} 
		division = {
			id = { type = 13016 id = 258 }
			name = "Iwate"
			type = heavy_cruiser
			model = 1
		}
		division = { 
			id = { type = 13016 id = 138 } 
			name = "Izumo" 
			type = heavy_cruiser 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 2249 } 
			name = "Dai 20 Kuchikusentai" 
			type = destroyer 
			model = 3
		} 
		division = { 
			id = { type = 13016 id = 2250 } 
			name = "Dai 21 Kuchikusentai" 
			type = destroyer 
			model = 3
		} 
	}

	# Crappy Reserve Fleet 2
	navalunit = { 
		id = { type = 13016 id = 212 } 
		name = "Dai 9 Sentai" 
		location = 1184 
		base = 1184
		division = {
			id = { type = 13016 id = 259 }
			name = "Tokiwa"
			type = heavy_cruiser
			model = 1
		}
		division = {
			id = { type = 13016 id = 262 }
			name = "Yakumo"
			type = heavy_cruiser
			model = 1
		}
		division = { 
			id = { type = 13016 id = 129 } 
			name = "Yahagi" 
			type = light_cruiser 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 128 } 
			name = "Hirado" 
			type = light_cruiser 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 2253 } 
			name = "Dai 22 Kuchikusentai" 
			type = destroyer 
			model = 0
		} 
		division = { 
			id = { type = 13016 id = 2246 } 
			name = "Dai 23 Kuchikusentai" 
			type = destroyer
			model = 0
		} 
		division = { 
			id = { type = 13016 id = 2247 } 
			name = "Dai 24 Kuchikusentai" 
			type = destroyer 
			model = 0
		} 
	} 
	
	# Submarine Fleet 1
	navalunit = { 
		id = { type = 13016 id = 280 } 
		name = "Dai 1 Sensui Kantai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 281 } 
			name = "Dai 1 Sensuisentai" 
			type = submarine 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 282 } 
			name = "Dai 2 Sensuisentai" 
			type = submarine 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 283 } 
			name = "Dai 3 Sensuisentai" 
			type = submarine 
			model = 3 
		} 
		division = { 
			id = { type = 13016 id = 284 } 
			name = "Dai 4 Sensuisentai" 
			type = submarine 
			model = 3 
		} 
	} 

	# Submarine Fleet 2
	navalunit = { 
		id = { type = 13016 id = 285 } 
		name = "Dai 2 Sensui Kantai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 286 } 
			name = "Dai 5 Sensuisentai" 
			type = submarine 
			model = 2
		} 
		division = { 
			id = { type = 13016 id = 287 } 
			name = "Dai 6 Sensuisentai" 
			type = submarine 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 288 } 
			name = "Dai 7 Sensuisentai" 
			type = submarine 
			model = 1
		} 
	}
	
	# Submarine Fleet 3
	navalunit = {
		id = { type = 13016 id = 300 }
		name = "Dai 3 Sensui Kantai"
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 289 } 
			name = "Dai 8 Sensuisentai" 
			type = submarine 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 290 } 
			name = "Dai 9 Sensuisentai" 
			type = submarine 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 291 } 
			name = "Dai 10 Sensuisentai"
			type = submarine 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 292 } 
			name = "Dai 11 Sensuisentai"
			type = submarine 
			model = 1
		} 
	} 
	
	# Submarine Fleet 4
	navalunit = { 
		id = { type = 13016 id = 293 } 
		name = "Dai 4 Sensui Kantai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 294 } 
			name = "I-5" 
			type = nuclear_submarine
			model = 0
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 295 } 
			name = "I-6" 
			type = nuclear_submarine
			model = 0
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 296 } 
			name = "I-7" 
			type = nuclear_submarine
			model = 0
			extra1 = floatplane
			brigade_model1 = 4
		} 
		division = { 
			id = { type = 13016 id = 297 } 
			name = "Dai 13 Sensuisentai" 
			type = submarine 
			model = 4
		} 
	} 

	# Transport Fleet 1
	navalunit = { 
		id = { type = 13016 id = 2211 } 
		name = "Dai 1 Yuso Kantai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 2254 } 
			name = "Dai 25 Kuchikusentai" 
			type = destroyer 
			model = 4
		} 
		division = { 
			id = { type = 13016 id = 187 } 
			name = "Dai 1 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 188 } 
			name = "Dai 2 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 189 } 
			name = "Dai 3 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 221 } 
			name = "Dai 16 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
	} 
	
	# Transport Fleet 2
	navalunit = { 
		id = { type = 13016 id = 1510 } 
		name = "Dai 2 Yuso Kantai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 2255 } 
			name = "Dai 26 Kuchikusentai" 
			type = destroyer 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 192 } 
			name = "Dai 6 Yuso Sentai" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13016 id = 191 } 
			name = "Dai 5 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 190 } 
			name = "Dai 4 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 224 } 
			name = "Dai 19 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
	} 
	
	# Transport Fleet 3
	navalunit = { 
		id = { type = 13016 id = 2244 } 
		name = "Dai 3 Yuso Kantai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 2256 } 
			name = "Dai 27 Kuchikusentai" 
			type = destroyer 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 218 } 
			name = "Dai 14 Yuso Sentai" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13016 id = 219 } 
			name = "Dai 15 Yuso Sentai" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13016 id = 222 } 
			name = "Dai 17 Yuso Sentai" 
			type = transport 
			model = 1 
			} 
		division = { 
			id = { type = 13016 id = 223 } 
			name = "Dai 18 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
	} 
		
	# Transport Fleet 4
	navalunit = { 
		id = { type = 13016 id = 2259 } 
		name = "Dai 4 Yuso Kantai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 2257 } 
			name = "Dai 28 Kuchikusentai" 
			type = destroyer 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 202 } 
			name = "Dai 7 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 203 } 
			name = "Dai 8 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 216 } 
			name = "Dai 20 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 217 } 
			name = "Dai 13 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
	} 
	
	# Transport Fleet 5
	navalunit = { 
		id = { type = 13016 id = 204 } 
		name = "Dai 5 Yuso Kantai" 
		location = 1184 
		base = 1184
		division = { 
			id = { type = 13016 id = 2258 } 
			name = "Dai 29 Kuchikusentai" 
			type = destroyer 
			model = 1
		} 
		division = { 
			id = { type = 13016 id = 211 } 
			name = "Dai 12 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 208 } 
			name = "Dai 9 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 209 } 
			name = "Dai 10 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
		division = { 
			id = { type = 13016 id = 210 } 
			name = "Dai 11 Yuso Sentai" 
			type = transport 
			model = 1 
		} 
	} 
	
#	navalunit = { 
#		id = { type = 13016 id = 180 } 
#		name = "Dai 5 Sentai" 
#		location = 1184 
#		base = 1184
#	} 

	
	### Japan Air OOB ### 
	
	airunit = {
		location = 1184 
		base     = 1552 
		id       = {  type = 13016 id = 236  } 
		name     = "Dai 1 Nihon Kokutai" 
		division = {
			id    = {  type = 13016 id = 237  } 
			name  = "Dai 1 Keibakugeki Hikodan" 
			type  = tactical_bomber 
			model = 4
		} 
	} 
	airunit = {
		location = 1184 
		base     = 1552 
		id       = {  type = 13016 id = 238  } 
		name     = "Dai 2 Nihon Kokutai" 
		division = {
			id    = {  type = 13016 id = 239  } 
			name  = "Dai 2 Keibakugeki Hikodan" 
			type  = tactical_bomber 
			model = 4
		} 
	} 
	airunit = {
		location = 1184 
		base     = 1219 
		id       = {  type = 13016 id = 240  } 
		name     = "Dai 1 Kokutai" 
		division = {
			id    = {  type = 13016 id = 241  } 
			name  = "Dai 3 Keibakugeki Hikodan" 
			type  = tactical_bomber 
			model = 4
		} 
	} 
	airunit = {
		location = 1184 
		base     = 1219 
		id       = {  type = 13016 id = 242  } 
		name     = "Dai 3 Nihon Kokutai" 
		division = {
			id    = {  type = 13016 id = 243  } 
			name  = "Dai 4 Keibakugeki Hikodan" 
			type  = tactical_bomber 
			model = 4
		} 
	} 
	airunit = {
		location = 1184 
		base     = 1219 
		id       = {  type = 13016 id = 244  } 
		name     = "Dai 2 Kokutai" 
		division = {
			id    = {  type = 13016 id = 245  } 
			name  = "Dai 5 Keibakugeki Hikodan" 
			type  = tactical_bomber 
			model = 4 
		} 
	} 
	airunit = {
		location = 1184 
		base     = 1552 
		id       = {  type = 13016 id = 246  } 
		name     = "Dai 4 Nihon Kokutai" 
		division = {
			id    = {  type = 13016 id = 247  } 
			name  = "Dai 13 Kaigunkogeki Hikodan" 
			type  = naval_bomber 
			model = 1
		} 
	} 
	airunit = {
		location = 1184 
		base     = 1219 
		id       = {  type = 13016 id = 248  } 
		name     = "Dai 5 Nihon Kokutai" 
		division = {
			id    = {  type = 13016 id = 249  } 
			name  = "Dai 33 Goraikogeki Hikodan" 
			type  = naval_bomber 
			model = 2
		} 
	} 
	airunit = {
		id       = {  type = 13016 id = 250  } 
		name     = "Dai 1 Kyokuchi Hikodan" 
		location = 1184 
		base     = 1199 
		division = {
			id       = {  type = 13016 id = 251  } 
			name     = "Dai 1 Kyokuchi Hikodan" 
			strength = 85 
			type     = interceptor 
			model    = 7
		} 
	} 
	airunit = {
		id       = {  type = 13016 id = 252  } 
		name     = "Dai 2 Kyokuchi Hikodan" 
		location = 1184 
		base     = 1199 
		division = {
			id       = {  type = 13016 id = 253  } 
			name     = "Dai 2 Kyokuchi Hikodan" 
			strength = 85 
			type     = interceptor 
			model    = 7
		} 
	} 
	airunit = {
		id       = {  type = 13016 id = 254  } 
		name     = "Dai 3 Kyokuchi Hikodan" 
		location = 1184 
		base     = 1219 
		division = {
			id       = {  type = 13016 id = 255  } 
			name     = "Dai 3 Kyokuchi Hikodan" 
			strength = 85 
			type     = interceptor 
			model    = 7
		} 
	} 
	airunit = {
		id       = {  type = 13016 id = 256  } 
		name     = "Dai 4 Kyokuchi Hikodan" 
		location = 1184 
		base     = 1552 
		division = {
			id       = {  type = 13016 id = 257  } 
			name     = "Dai 4 Kyokuchi Hikodan" 
			strength = 85 
			type     = interceptor 
			model    = 6
		} 
	}
	
	
	# ### Under division_development ### 
	
	division_development = {  
		name  = "Soryu" 
		type  = carrier 
		model = 2 
		cost  = 0.1
		id    = {  type = 13016 id = 263  } 
		date  = {  year = 1936 month = december day = 20  } 
		extra = cag 
		brigade_model = 2 
		new_model = no
	} 
	division_development = {  
		name  = "Kumano"
		type  = heavy_cruiser
		model = 4
		cost  = 0.1
		id    = { type = 13016 id = 264 }
		date  = { year = 1937 month = october day = 1 }
		extra1 = floatplane
		brigade_model1 = 4
		new_model = no
	}
	division_development = {  
		name  = "Suzuya"
		type  = heavy_cruiser
		model = 4
		cost  = 0.1
		id    = { type = 13016 id = 265 }
		date  = { year = 1937 month = october day = 29 }
		extra1 = floatplane
		brigade_model1 = 4
		new_model = no
	}
	division_development = {  
		name  = "Tone"
		type  = heavy_cruiser
		model = 5
		cost  = 0.1
		id    = { type = 13016 id = 266 }
		date  = { year = 1938 month = november day = 20 }
		extra1 = floatplane
		brigade_model1 = 4
		new_model = no
	}
	division_development = {  
		name  = "Chikuma"
		type  = heavy_cruiser
		model = 5
		cost  = 0.1
		id    = { type = 13016 id = 267 }
		date  = { year = 1939 month = may day = 20 }
		extra1 = floatplane
		brigade_model1 = 4
		new_model = no
	}
	division_development = {
		name  = "Dai 30 Kuchikusentai" 
		type  = destroyer 
		model = 5 
		cost  = 0.1
		id    = {  type = 13016 id = 268  } 
		date  = {  year = 1936 month = march day = 1  } 
		new_model = no
	} 
	division_development = {
		name  = "Dai 31 Kuchikusentai" 
		type  = destroyer 
		model = 5 
		cost  = 0.1
		id    = {  type = 13016 id = 368  } 
		date  = {  year = 1936 month = june day = 1  } 
		new_model = no
	} 
	division_development = {
		name  = "Dai 32 Kuchikusentai" 
		type  = destroyer 
		model = 5 
		cost  = 0.1
		id    = {  type = 13016 id = 468  } 
		date  = {  year = 1936 month = september day = 1  } 
		new_model = no
	} 
	division_development = { 
		id = { type = 13016 id = 113 } 
		name = "Kongo" 
		type = battlecruiser 
		model = 3 
		cost = 1.1
		unitcost = no
		date = { year = 1937 month = january day = 8 }
		extra1 = naval_improved_hull_l
		extra2 = floatplane
		brigade_model2 = 4
		new_model = no
	} 
	division_development = { 
		id = { type = 13016 id = 117 } 
		name = "Kirishima" 
		type = battlecruiser 
		model = 3 
		cost = 1.1
		unitcost = no
		date = { year = 1936 month = june day = 8 }
		extra1 = naval_improved_hull_l
		extra2 = floatplane
		brigade_model2 = 4
		new_model = no
	} 
	division_development = { 
		id = { type = 13016 id = 114 } 
		name = "Hiei" 
		type = battlecruiser 
		model = 3 
		cost = 1.1
		unitcost = no
		# Date is bogus, Hiei didn't begin rebuild until Apr '37 (finished Jan '40).
		# Starting rebuild in Jan '36 as we have no easy way to model this otherwise.
		# Giving ship an earlier completion date since it has an earlier start date.
		date = { year = 1938 month = may day = 1 } 
		extra1 = naval_improved_hull_l
		extra2 = floatplane
		brigade_model2 = 4
		new_model = no
	} 
	division_development = { 
		id = { type = 13016 id = 125 } 
		name = "Mutsu" 
		type = battleship 
		model = 5 
		cost = 0.5
		unitcost = no
		date = { year = 1936 month = september day = 29 }
		extra1 = naval_anti_air_l
		extra2 = naval_fire_controll_l
		extra3 = naval_improved_hull_l
		extra4 = floatplane
		brigade_model4 = 4
		new_model = no
	} 
	division_development = {
		id = { type = 13016 id = 269 }
		name = "Chitose"
		type = escort_carrier
		cost = 0.1
		date = { year = 1938 month = july day = 25 }
		new_model = no
	}
	division_development = {
		id = { type = 13016 id = 270 }
		name = "Chiyoda"
		type = escort_carrier
		cost = 0.1
		date = { year = 1938 month = july day = 25 }
		new_model = no
	}
	division_development = {
		id = { type = 13016 id = 271 }
		name = "I-8"
		type = nuclear_submarine
		model = 0
		date = { year = 1938 month = december day = 4 }
		cost = 0.1
		extra1 = floatplane
		brigade_model1 = 4
	}
	division_development = {
		id = { type = 13016 id = 272 }
		name = "Dai 13 Sensuisentai"
		type = submarine
		model = 4
		date = { year = 1936 month = may day = 1 }
		cost = 0.1
	}

	landdivision = { dormant = yes id = { type = 13016 id = 2000 } name = "1 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2001 } name = "22 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2002 } name = "2 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2003 } name = "3 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2004 } name = "4 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2005 } name = "5 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2006 } name = "6 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2007 } name = "7 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2008 } name = "8 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2009 } name = "9 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2010 } name = "10 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2011 } name = "11 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2012 } name = "12 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2013 } name = "13 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2014 } name = "14 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2015 } name = "15 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2016 } name = "16 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2017 } name = "17 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2018 } name = "18 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2019 } name = "19 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2020 } name = "20 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2021 } name = "21 Hendan" type = garrison model = 5 extra = artillery brigade_model = 9 locked = yes }
	
	landdivision = { dormant = yes id = { type = 13016 id = 2031 } name = "Dai 1 Indoshina Shubitai" type = garrison model = 5 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2032 } name = "Dai 2 Indoshina Shubitai" type = garrison model = 5 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2033 } name = "Dai 3 Indoshina Shubitai" type = garrison model = 5 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2034 } name = "Dai 4 Indoshina Shubitai" type = garrison model = 5 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2035 } name = "Dai 5 Indoshina Shubitai" type = infantry model = 10 }
	landdivision = { dormant = yes id = { type = 13016 id = 2036 } name = "Dai 6 Indoshina Shubitai" type = infantry model = 10 }
	landdivision = { dormant = yes id = { type = 13016 id = 2037 } name = "Dai 7 Indoshina Shubitai" type = garrison model = 5 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2038 } name = "Dai 8 Indoshina Shubitai" type = infantry model = 10 }
	landdivision = { dormant = yes id = { type = 13016 id = 2039 } name = "Dai 9 Indoshina Shubitai" type = infantry model = 10 }
	landdivision = { dormant = yes id = { type = 13016 id = 2040 } name = "Dai 10 Indoshina Shubitai" type = garrison model = 5 locked = yes }

	
	landdivision = { dormant = yes id = { type = 13016 id = 2060 }  name = "Free Indian Army"	type = garrison model = 4	locked = yes }
	
	landdivision = { dormant = yes id = { type = 13016 id = 2070 } name = "Kanto-gun saiko shireibu" strength = 40 type = hq model  = 2 } 
	landdivision = { dormant = yes id = { type = 13016 id = 2071 } name = "Kantô Bôbitai"      strength = 100 type = garrison model = 4 extra  = police 			brigade_model = 1  										 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2072 } name = "IJA Kihei Shudan"   strength = 100 type = cavalry  model = 8 																					 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2073 } name = "Dai 1 Hoheishidan"  strength = 100 type = infantry model = 7	extra  = light_armor_brigade	brigade_model = 2									 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2074 } name = "Dai 2 Hoheishidan"  strength = 100 type = infantry model = 7	extra1 = cavalry_brigade	brigade_model1 = 5 	extra2 = engineer brigade_model2 = 3 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2075 } name = "Dai 3 Hoheishidan"  strength = 100 type = infantry 																								 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2076 } name = "Dai 4 Hoheishidan"  strength = 100 type = infantry 																								 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2077 } name = "Dai 7 Hoheishidan"  strength = 100 type = infantry model = 8 extra1 = cavalry_brigade	brigade_model1 = 5	extra2 = engineer brigade_model2 = 3 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2078 } name = "Dai 8 Hoheishidan"  strength = 100 type = infantry model = 7 extra  = engineer 			brigade_model  = 3 										 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2079 } name = "Dai 9 Hoheishidan"  strength = 100 type = infantry model = 7 extra1 = cavalry_brigade	brigade_model1 = 5	extra2 = engineer brigade_model2 = 3 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2080 } name = "Dai 10 Hoheishidan" strength = 100 type = infantry model = 7 extra1 = cavalry_brigade	brigade_model1 = 5	extra2 = engineer brigade_model2 = 3 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2081 } name = "Dai 12 Hoheishidan" strength = 100 type = infantry model = 7																						 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2082 } name = "Dai 19 Hoheishidan" strength = 100 type = infantry model = 7 extra1 = cavalry_brigade	brigade_model1 = 5	extra2 = anti_air brigade_model2 = 1 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2083 } name = "Dai 24 Hoheishidan" strength = 100 type = infantry model = 6	extra  = engineer			brigade_model  = 3	locked = yes 						 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2084 } name = "Dai 25 Hoheishidan" strength = 100 type = infantry model = 7 extra1 = cavalry_brigade	brigade_model1 = 5	extra2 = engineer brigade_model2 = 3 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2085 } name = "Dai 26 Hoheishidan" strength = 100 type = infantry model = 6	extra  = engineer			brigade_model = 3 										 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2086 } name = "Dai 28 Hoheishidan" strength = 100 type = infantry model = 7 extra1 = cavalry_brigade	brigade_model1 = 5	extra2 = engineer brigade_model2 = 3 locked = yes }
	landdivision = { dormant = yes id = { type = 13016 id = 2087 } name = "Dai 29 Hoheishidan" strength = 100 type = infantry model = 7 extra  = light_armor_brigade	brigade_model = 2 									 locked = yes }
	
	
	landunit = 
	{  
	 id       = {  type = 13016 id = 1500  } 
     name     = "IJN Shanghai Marine Brigade" 
     location = 1237 
     Division = 
     {  
	   id       = {  type = 13016 id = 1501  } 
       name     = "1st Special Naval Landing Force" 
       strength = 100 
       type     = marine 
       model    = 3
	   locked   = yes
	   experience = 90
     } 
     Division = 
     {  
	   id       = {  type = 13016 id = 1502  } 
       name     = "1st Infantry Reserve Regiment" 
       strength = 30 
       type     = infantry 
       model    = 7
	   locked   = yes
	   experience = 90
     } 
    } 
	landunit = 
	{  
	 id       = {  type = 13016 id = 1503  } 
     name     = "IJA Shanghai Expeditionary Force" 
     location = 1237 
     Division = 
     {  
	   id       = {  type = 13016 id = 1504  } 
       name     = "3rd SEF Division" 
       strength = 100 
       type     = infantry 
       model    = 8
	   #locked   = yes
	   experience = 90
       extra    = artillery 
	   brigade_model = 6
     } 
     Division = 
     {  
	   id       = {  type = 13016 id = 1505  } 
       name     = "11th SEF Division" 
       strength = 100 
       type     = infantry 
       model    = 8
	   #locked   = yes
	   experience = 90
       extra    = artillery 
	   brigade_model = 6
     } 
     Division = 
     {  
	   id       = {  type = 13016 id = 1506  } 
       name     = "101st SEF Division" 
       strength = 100 
       type     = infantry 
       model    = 8
	   #locked   = yes
	   experience = 90
       extra    = artillery 
	   brigade_model = 6
     } 
     Division = 
     { 
	   id       = {  type = 13016 id = 1507  } 
       name     = "9th SEF Division" 
       strength = 100 
       type     = infantry 
       model    = 8
	   #locked   = yes
	   experience = 90
       extra    = artillery 
	   brigade_model = 6
     } 
     Division = 
     { 
	   id       = {  type = 13016 id = 1508  } 
       name     = "13th SEF Division" 
       strength = 100 
       type     = infantry 
       model    = 8
	   #locked   = yes
	   experience = 90
       extra    = artillery 
	   brigade_model = 6
     } 
     Division = 
     { 
	   id       = {  type = 13016 id = 1509 } 
       name     = "Central China Expeditionary HQ" 
       strength = 100 
       type     = hq 
       model    = 2
	   #locked   = yes
	   experience = 20
     } 
    } 
} 
 

 
