country = 
 {  tag                    = REB 
   capital                = 7992 

     # Resource Reserves 
   energy                 = 0 
   metal                  = 0 
   rare_materials         = 0 
   oil                    = 0 
   supplies               = 0 
   money                  = 0 
   manpower               = 0
      
   transports             = 0 
   escorts                = 0 

   diplomacy = 
   {   
   relation = {  tag = GER value = 80 access = no  }  
    } 
 
	nationalprovinces      = {  7992 7994 7995 7996 7997 7998 7999 8003 8004 8005 8006 8007 8008 8009 8010 8011 8012 8013 8014 8015 8016 8017 8018 8019 8020  } 
	ownedprovinces         = {  7992 7994 7995 7996 7997 7998 7999 8003 8004 8005 8006 8007 8008 8009 8010 8011 8012 8013 8014 8015 8016 8017 8018 8019 8020  } 
	controlledprovinces    = {  7992 7994 7995 7996 7997 7998 7999 8003 8004 8005 8006 8007 8008 8009 8010 8011 8012 8013 8014 8015 8016 8017 8018 8019 8020 5644 5620 1243 } 
   
	techapps               = {  }
	inventions = { 3000027 } 
	policy = 
   {  date              = {  year = 0 month = january day = 0  } 
     democratic        = 1 
     political_left    = 2 
     free_market       = 1
     freedom           = 1 
     professional_army = 1 
     defense_lobby     = 1
     interventionism   = 1  
    } 
   landunit = 
   {  location = 5644 # 
     name     = "28th Red Army" 
     id       = {  type = 24001 id = 1  } 
     Division = 
     {  experience = 90 
       id         = {  type = 24001 id = 2  } 
       name       = "82nd Division" 
       type       = bergsjaeger 
       strength  = 35 
       model      = 7 
	   locked     = yes
      } 
     dig_in   = 20.000 
    } 
   landunit = 
   {  location = 5620 # 
     name     = "16th Division" 
     id       = {  type = 24001 id = 3  } 
     Division = 
     {  experience = 90 
       id         = {  type = 24001 id = 4  } 
       name       = "16th Division" 
       type       = bergsjaeger 
       strength  = 22 
       model      = 7 
	   locked     = yes
      } 
    dig_in   = 20.000 
    } 
   landunit = 
   {  location = 1243 # 
     name     = "Fujian Military Command" 
     id       = {  type = 24001 id = 5  } 
     Division = 
     {  experience = 90 
       id         = {  type = 24001 id = 6  } 
       name       = "Fujian Military Command" 
       type       = bergsjaeger 
       strength  = 66 
       model      = 7 
	   locked     = yes
      } 
     dig_in   = 20.000 
    } 
  }