#####################
# Country main data #
#####################

country =
{ tag                    = YUG
	# Resource Reserves 
	energy                 = 1500
	metal                  = 750
	rare_materials         = 375
	transports = 100
	oil                    = 500 
	supplies               = 500 
	money                  = 15 
	manpower 			  = 46
  capital                = 453
  diplomacy =
  { relation = { tag = BUL value = 25 }
    relation = { tag = CZE value = 50 }
    relation = { tag = FIN value = 35 }
    relation = { tag = FRA value = 50 }
    relation = { tag = GER value = 50 }
    relation =
    { tag        = GRE
      value      = 100
    }
    relation = { tag = HUN value = 80 }
    relation = { tag = ITA value = 75 }
    relation =
    { tag        = ROM
      value      = 100
    }
    relation =
    { tag        = TUR
      value      = 100
    }
  }
  SpyInfo                = { country = "ENG" NumberOfSpies = 1 }
  SpyInfo                = { country = "FRA" NumberOfSpies = 1 }
  SpyInfo                = { country = "SOV" NumberOfSpies = 1 }
  SpyInfo                = { country = "CZE" NumberOfSpies = 2 }
  SpyInfo                = { country = "AUS" NumberOfSpies = 2 }
  SpyInfo                = { country = "GER" NumberOfSpies = 1 }
  SpyInfo                = { country = "HUN" NumberOfSpies = 2 }
  SpyInfo                = { country = "BUL" NumberOfSpies = 2 }
  SpyInfo                = { country = "ALB" NumberOfSpies = 2 }
  SpyInfo                = { country = "GRE" NumberOfSpies = 3 }
  SpyInfo                = { country = "ROM" NumberOfSpies = 4 }
  SpyInfo                = { country = "ITA" NumberOfSpies = 3 }
  nationalprovinces      = { 
7268 6563 1057 3373 453 3361 6564 3368 452 3367 5464 3370 493 3371 1893 6505 1895 7315 385 3362 2607 1894 6537 2609 3397 494 383 2608 413 1892 6535 414 6557 7269 7271 1168 6538 1896 3393 389 3374 451 1897
7319 411 
#3357 7124 666
  }
  ownedprovinces         = { 
380 459 455 454 453 382  383 384 385 386 387 388 389 451 452 415 493 494 413 414 
291 1891 1892 1893 1897 1895 1057 1894 1896 1168 1169 2289
2607 2608 2609 3397
3359 3360 3361 3362 3363 3364 3365 3366 3367 3368 3369 3370 3371 3372 3373 3374 3393
5464 6505 6534 6535 6536 6537 6538 6557 6558 6559 6560 6561 6562 6563 6564
7122 7267 7268 7269 7270 7271 7315 7937
  }
  controlledprovinces    = { 
380 459 455 454 453 382  383 384 385 386 387 388 389 451 452 415 493 494 413 414 
291 1891 1892 1893 1897 1895 1057 1894 1896 1168 1169 2289
2607 2608 2609 3397
3359 3360 3361 3362 3363 3364 3365 3366 3367 3368 3369 3370 3371 3372 3373 3374 3393
5464 6505 6534 6535 6536 6537 6538 6557 6558 6559 6560 6561 6562 6563 6564
7122 7267 7268 7269 7270 7271 7315 7937
  }
  claimedprovinces 		 = { 665 456 6514 495 2602 6506 3375 1891 3363 6559 7937 384 381 3358 3364
382 455 3365 454 291 3360 3366 6558 388 6561 2289 459 7122 6560 380 3359 461 2326 7125 2325 3369 3372 415 6562 1169 1819 6536 387 6534 7267 6534 386 7270
6508 412 2319 410 416 7055 7123 7126 668
3357 7124 666
  }

  # Eastern Minor Tech '36
  # Group D 1936 techs
  # ######################
  # GW fighter
   techapps               = {  
#Interwar Fighter  
4500 4510 4520 4530 4540 4550 4010
#Basic Armoured Car  
2860 2870 2880 2020
#Great War Heavy Field Artillery 
2290 2300 2310
#SW Tank 
7600 7610 2620 2010
#Great War Infantry Division  
1010 1020 1030 1040 1050 1060 
#Great War Cavalry Division  
13060 13070 13080 1310 1320 1330 1340
#Early Mountain Division 
1160 1170 1180 1190 1200 1210 1220 1230 1240
#Engineers
1830 1840 
#Early Static Anti-Air Artillery 
2800 2450 21180 21190
#Basic Anti-Air Artillery Brigade 
2810 2820 2510
#Modern Agriculture  
5700 5710 5010
#Manufactoring
5810 5820 5050 5830
#Computers & cryptografi
5310 54010 54020 54030 5316 5326
#Improved Construction Engineering 
5800 5080 5090 
#Basic Oil Refining 
#5190
#Interwar Bomber 
4600 4610 4620 4630 4120
#Improved Destroyer 
3010 3020 3030 3040 3050 3060
#Short Range Submarine 
3610 3620
#Torpedo & ASW 18
3720 3730 3736 3740 3750 3900
#Troopships
3810
#Medicine
5600 5610 #5620
#Interbellum Supply 
1910 1920 1930 1940 1950 1960
#Naval Doctrines
8010 8040 8050
#Air Doctrines - ww2 techs
27480 27490 27500 27510 27520 27530 27540 27550 27570 27580 27590 27600 9030 9020 27560 27460 27470 9010
# Land doctrines WWI - Entente line
6500 6510 6530 6580 6600 6610 6680 6620 6630 6640 6650 6660 6670 6540 6910
#Landdoctrine ww2 - none?
#Improved Great War Hospital System
14000 #14010
} 
  policy =
  { date              = { year = 0 month = january day = 0 }
     democratic        = 1 
     political_left    = 3 
     freedom           = 4
     free_market       = 1
     professional_army = 5 
     defense_lobby     = 3 
     interventionism   = 4 
  }
inventions = { 3000027 }

   headofstate            = {  type = 9 id = 100001  } 
   headofgovernment       = {  type = 9 id = 100002  } 
   foreignminister        = {  type = 9 id = 100003  } 
   armamentminister       = {  type = 9 id = 100004  } 
   ministerofsecurity     = {  type = 9 id = 100005  } 
   ministerofintelligence = {  type = 9 id = 100006  } 
   chiefofstaff           = {  type = 9 id = 100007  } 
   chiefofarmy            = {  type = 9 id = 100008  } 
   chiefofnavy            = {  type = 9 id = 100009  } 
   chiefofair             = {  type = 9 id = 100010  } 
  
   landunit = 
   {  id       = {  type = 19800 id = 1  } 
     location = 453 
     name     = "IV. Kraljevska Jugoslavenska Armija" 
     Division = 
     {  id       = {  type = 19800 id = 2  } 
       name     = "27. Savska Pesadijska Divizija" 
       strength = 50 # 70
       type     = infantry 
	   model    = 7
       extra    = artillery 
	   brigade_model = 6
      } 
    } 
   landunit = 
   {  id       = {  type = 19800 id = 3  } 
     location = 453 
     name     = "VII. Kraljevska Jugoslavenska Armija" 
     Division = 
     {  id       = {  type = 19800 id = 4  } 
       name     = "32. Triglavska Pesadijska Divizija" 
       strength = 50 # 70
       type     = infantry 
	   model    = 6
       extra    = artillery 
	   brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 19800 id = 5  } 
       name     = "Triglavski Odred" 
       strength = 50 # 70
       type     = bergsjaeger 
	   model    = 6
      } 
     Division = 
     {  id       = {  type = 19800 id = 6  } 
       name     = "1. Konjicka Divizija" 
       strength = 50 # 70
       type     = cavalry 
	   model    = 7
      } 
    } 
   landunit = 
   {  id       = {  type = 19800 id = 7  } 
     name     = "I. Kraljevska Jugoslavenska Armija" 
     location = 453 
     Division = 
     {  id       = {  type = 19800 id = 8  } 
       name     = "7. Potiska Pesadijska Divizija" 
       strength = 50 # 70
       type     = infantry 
	   model    = 7
       extra    = artillery 
	   brigade_model = 6
      } 
     Division = 
     {  id       = {  type = 19800 id = 9  } 
       name     = "3. Konjicka Divizija" 
       strength = 50 # 70
       type     = cavalry 
	   model    = 6
      } 
    } 
   landunit = 
   {  id       = {  type = 19800 id = 10  } 
     location = 453 
     name     = "II. Kraljevska Jugoslavenska Armija" 
     Division = 
     {  id       = {  type = 19800 id = 11  } 
       name     = "10. Bosanska Pesadijska Divizija" 
       strength = 50 # 70
       type     = infantry 
	   model    = 7
       extra    = anti_air 
	   brigade_model = 1
      } 
     Division = 
     {  id       = {  type = 19800 id = 12  } 
       name     = "17. Vrbaska Pesadijska Divizija" 
       strength = 50 # 70
       type     = infantry 
	   model    = 7
      } 
    } 
   landunit = 
   {  id       = {  type = 19800 id = 13  } 
     location = 453 
     name     = "III. Kraljevska Jugoslavenska Armija" 
     Division = 
     {  id       = {  type = 19800 id = 14  } 
       name     = "13. Hercegovacka Pesadijska Divizija" 
       strength = 50 # 70
       type     = infantry 
	   model    = 6
      } 
     Division = 
     {  id       = {  type = 19800 id = 15  } 
       name     = "15. Zetska Pesadijska Divizija" 
       strength = 50 # 70
       type     = infantry 
	   model    = 7
      } 
    } 
   landunit = 
   {  id       = {  type = 19800 id = 16  } 
     location = 453 
     name     = "III. Kraljevska Teritorijalna Armija" 
     Division = 
     {  id       = {  type = 19800 id = 17  } 
       name     = "5. Sumadijska Pesadijska Divizija" 
       strength = 50 # 70
       type     = infantry 
	   model    = 7
       extra    = anti_air 
	   brigade_model = 1
      } 
     Division = 
     {  id       = {  type = 19800 id = 18  } 
       name     = "20. Bregalnicka Pesadijska Divizija" 
       strength = 50 # 70
       type     = infantry 
	   model    = 8
      } 
     Division = 
     {  id       = {  type = 19800 id = 19  } 
       name     = "22. Ibarska Pesadijska Divizija" 
       strength = 50 # 70
       type     = infantry 
	   model    = 7
      } 
    } 
   landunit = 
   {  id       = {  type = 19800 id = 20  } 
     location = 453 
     name     = "V. Nezavisna Armija" 
     Division = 
     {  id       = {  type = 19800 id = 21  } 
       name     = "8. Krajinska Pesadijska Divizija" 
       strength = 50 # 70
       type     = infantry 
	   model    = 8
       extra    = artillery 
	   brigade_model = 7
      } 
     Division = 
     {  id       = {  type = 19800 id = 22  } 
       name     = "9. Timocka Pesadijska Divizija" 
       strength = 50 # 70
       type     = infantry 
	   model    = 7
      } 
     Division = 
     {  id       = {  type = 19800 id = 23  } 
       name     = "2. Konjicka Divizija" 
       strength = 50 # 70
       type     = cavalry 
	   model    = 6
      } 
    } 
   landunit = 
   {  id       = {  type = 19800 id = 24  } 
     location = 453 
     name     = "VI. Nezavisna Armija" 
     Division = 
     {  id       = {  type = 19800 id = 25  } 
       name     = "3. Dunavska Pesadijska Divizija" 
       strength = 50 # 70
       type     = infantry 
	   model    = 6
      } 
     Division = 
     {  id       = {  type = 19800 id = 26  } 
       name     = "4. Konjicka Divizija" 
       strength = 50 # 70
       type     = cavalry
	   model    = 7
	   
      } 
    } 
   # ########################## 
   # ########################## 
   navalunit = 
   {  id       = {  type = 19800 id = 30  } 
     name     = "Kraljevska Jugoslavenska Ratna Mornarica" 
     location = 384 
     base     = 384 
	 Division =
	 { id       = {  type = 19800 id = 233 }
	   name     = "Dalmacija"
	   type     = light_cruiser
	   model    = 0
	 }
     Division = 
     { id       = {  type = 19800 id = 32  } 
       name     = "1. Razaracka Flotila" 
       type     = destroyer 
       model    = 3
       strength = 40 
      } 
     Division = 
     {  id       = {  type = 19800 id = 232  } 
       name     = "2. Razaracka Flotila" 
       type     = destroyer 
       model    = 0
      } 
     Division = 
     {  id       = {  type = 19800 id = 234  } 
       name     = "3. Razaracka Flotila" 
       type     = destroyer 
       model    = 0
      } 
     Division = 
     {  id    = {  type = 19800 id = 33  } 
       name  = "1. Podmornicka Flotila" 
       type  = submarine 
       model = 1 
      } 
    } 
   airunit = 
   {  location = 453 
     base     = 453 
     id       = {  type = 19800 id = 27  } 
     name     = "Operativno Zrakoplovstvo" 
     Division = 
     {  id       = {  type = 19800 id = 28  } 
       name     = "2. Vazduhoplovni Lovacki Puk" 
       strength = 30 
       type     = interceptor 
       model    = 5
      } 
     Division = 
     {  id       = {  type = 19800 id = 29  } 
       name     = "26. Takticki Bombarderski Puk" 
       strength = 30 
       type     = tactical_bomber 
       model    = 4 
      } 
    } 
  } 
 
